import { useId } from "react";
import { galoLevels, type GaloLevel } from "../../content/mathematics";
import { useI18n } from "../../i18n/I18nContext";

const LEVEL: GaloLevel = 6;

/** The sub-collection generated by one position under repeated PLUS. */
function generatedBy(level: number, step: number) {
  const members = new Set<number>();
  let cursor = 0;
  do {
    members.add(cursor);
    cursor = (cursor + step) % level;
  } while (cursor !== 0);
  return [...members].sort((left, right) => left - right);
}

const divisorsOf = (level: number) =>
  Array.from({ length: level }, (_, index) => index + 1).filter((candidate) => level % candidate === 0);

/** One node per divisor of 6, positioned by how many positions it holds. */
const nodes = divisorsOf(LEVEL).map((divisor) => {
  // The divisor names the ring; the step that generates it is that divisor read
  // as a position, so at L6 the divisor 6 is the step P0 and the ring is {P0}.
  const step = divisor % LEVEL;
  const members = generatedBy(LEVEL, step);
  return { divisor, step, members, size: members.length };
});

const NODE_WIDTH = 168;
const NODE_HEIGHT = 34;
const WIDTH = 620;
const HEIGHT = 330;
/** Baseline of each node box; the box occupies y − NODE_HEIGHT to y. */
const positions: Record<number, { x: number; y: number }> = {
  6: { x: 226, y: 296 },
  3: { x: 30, y: 188 },
  2: { x: 422, y: 188 },
  1: { x: 226, y: 80 },
};
/** Each pair is [lower node, the node directly above it]. */
const edges: [number, number][] = [
  [6, 3],
  [6, 2],
  [3, 1],
  [2, 1],
];

/**
 * The sub-collections of one level, drawn as the lattice they form.
 *
 * Repeating one PLUS step from P0 closes into a smaller ring, and the rings you
 * can reach are exactly the divisors of the level: at L6 there are four of
 * them, at L7 only two. Both the members of each ring and the divisor counts in
 * the strip are computed rather than listed.
 */
export function SubgroupLatticeFigure() {
  const { t } = useI18n();
  const titleId = useId();
  const descriptionId = useId();

  return (
    <figure className="galo-figure galo-figure--lattice">
      <figcaption className="galo-figure__caption">
        <span className="galo-figure__eyebrow">{t("THE RINGS INSIDE A RING")}</span>
        <strong>{t("Repeat one step from P0 and you land in a smaller closed ring — one for each divisor.")}</strong>
        <span className="galo-figure__note">
          {t(
            "Start at P0 and keep adding the same position. At L6, adding P2 each time visits P0, P2, P4 and returns; adding P3 visits P0 and P3. Those closed rings are the sub-collections, and a line joins one to another when the smaller sits inside the larger.",
          )}
        </span>
      </figcaption>
      <div className="galo-figure__canvas">
        <svg viewBox={`0 0 ${WIDTH} ${HEIGHT}`} role="img" aria-labelledby={`${titleId} ${descriptionId}`}>
          <title id={titleId}>{t("The four closed sub-collections of L6 and how they nest")}</title>
          <desc id={descriptionId}>
            {t(
              "A four-node diagram. At the bottom the single position P0. Above it two rings: P0 with P3, and P0 with P2 and P4. Both rise to the whole level at the top. L6 has four divisors and therefore four rings; a prime level such as L7 has only two.",
            )}
          </desc>

          {edges.map(([lower, upper]) => (
            <line
              key={`${lower}-${upper}`}
              className="galo-lattice__edge"
              x1={positions[lower]!.x + NODE_WIDTH / 2}
              y1={positions[lower]!.y - NODE_HEIGHT}
              x2={positions[upper]!.x + NODE_WIDTH / 2}
              y2={positions[upper]!.y}
            />
          ))}

          {nodes.map((node) => {
            const spot = positions[node.divisor]!;
            return (
              <g key={node.divisor}>
                <rect
                  className={node.size === LEVEL ? "galo-lattice__node is-whole" : "galo-lattice__node"}
                  x={spot.x}
                  y={spot.y - NODE_HEIGHT}
                  width={NODE_WIDTH}
                  height={NODE_HEIGHT}
                  rx={9}
                />
                <text
                  className="galo-lattice__members"
                  x={spot.x + NODE_WIDTH / 2}
                  y={spot.y - 12}
                  textAnchor="middle"
                  direction="ltr"
                >
                  {node.members.map((member) => `P${member}`).join(" ")}
                </text>
                <text
                  className="galo-lattice__step"
                  x={spot.x + NODE_WIDTH / 2}
                  y={spot.y + 16}
                  textAnchor="middle"
                  direction="ltr"
                >
                  {`+P${node.step} · ${node.size}`}
                </text>
              </g>
            );
          })}
        </svg>
      </div>
      <div className="galo-lattice__strip">
        {galoLevels.map((level) => (
          <div key={level}>
            <strong dir="ltr">{`L${level}`}</strong>
            <span dir="ltr">{divisorsOf(level).join(" · ")}</span>
            <small>{t("rings")}</small>
            <b dir="ltr">{divisorsOf(level).length}</b>
          </div>
        ))}
      </div>
      <p className="galo-figure__note galo-figure__note--boundary">
        {t(
          "A prime level has nothing between P0 and the whole ring, which is why L5 and L7 have two sub-collections while the smaller L6 has four. Size is not the same as structure, and this is the clearest place that shows it.",
        )}
      </p>{" "}
    </figure>
  );
}
