/**
 * Academic reference layer: numbered definitions and propositions with proofs.
 *
 * `title`, `prose`, `statement`, and each proof step's `text` are translated.
 * Every `formal` field is a canonical mathematical expression and is rendered
 * left-to-right unchanged in every locale.
 */

export type AcademicDefinition = {
  id: string;
  title: string;
  formal: string;
  prose: string;
};

export type ProofStep = {
  text: string;
  formal?: string;
};

export type AcademicProposition = {
  id: string;
  kind: "Proposition" | "Theorem" | "Corollary" | "Lemma";
  title: string;
  statement: string;
  formal: string;
  proof: readonly ProofStep[];
  boundary?: string;
};

export const academicDefinitions: readonly AcademicDefinition[] = [
  {
    id: "D1",
    title: "Carrier of a level",
    formal: "Q_n = {P0, P1, …, P_(n−1)},  |Q_n| = n,  1 ≤ n ≤ 7",
    prose:
      "The level fixes a finite set of named positions before any operation is defined. Nothing outside this list may appear as an input or as a result.",
  },
  {
    id: "D2",
    title: "Index map",
    formal: "ι : Q_n → Z/nZ,  ι(P_i) = i + nZ",
    prose:
      "Each position is identified with one residue class modulo n. The map is a bijection, which is what lets exact arithmetic be carried out on labels without treating a label as a quantity.",
  },
  {
    id: "D3",
    title: "The law PLUS",
    formal: "PLUS_n : Q_n × Q_n → Q_n,  PLUS_n(P_i, P_j) = P_((i+j) mod n)",
    prose:
      "PLUS is total and closed: it is defined on every ordered pair and its value always lies in the same carrier. Its complete graph is the PLUS Cayley table of that level.",
  },
  {
    id: "D4",
    title: "The law STAR",
    formal: "STAR_n(P_i, P_j) = P0 if i = 0;  STAR_n(P_i, P_j) = P_((i+j) mod n) if i ≠ 0",
    prose:
      "STAR agrees with PLUS on every row except the first, where a single guard on the left operand overrides the sum. This one clause is the source of every asymmetry proved below.",
  },
  {
    id: "D5",
    title: "The three structures",
    formal: "G_n = (Q_n, PLUS_n, P0);  S_n = (Q_n, STAR_n, P0);  A_n = (Q_n, PLUS_n, STAR_n, P0)",
    prose:
      "The same carrier is studied under one law, under the other law, and under both at once. The full expansion has signature (2,2,0): two binary operations and one named constant.",
  },
  {
    id: "D6",
    title: "Typed transition coordinate",
    formal: "c = (n, F, s, a),  F ∈ {PLUS, STAR} × {LEFT, RIGHT};  LEFT(s,a) = F(s,a),  RIGHT(s,a) = F(a,s)",
    prose:
      "A coordinate records the level, the law, and which of the two semantic roles occupies which table axis. Two coordinates with equal targets remain distinct records whenever their roles differ.",
  },
];

export const academicPropositions: readonly AcademicProposition[] = [
  {
    id: "P1",
    kind: "Proposition",
    title: "The PLUS reduct is the cyclic group of order n",
    statement:
      "Under PLUS the carrier is a cyclic group: the operation is associative and commutative, P0 is a two-sided identity, and every position has an inverse.",
    formal: "G_n = (Q_n, PLUS_n, P0) ≅ Z/nZ",
    proof: [
      {
        text: "The index map is a bijection and transports the operation onto residue addition, because the definition of PLUS is stated directly in terms of that addition.",
        formal: "ι(PLUS_n(x,y)) = ι(x) + ι(y)  in Z/nZ",
      },
      {
        text: "Residue addition is associative and commutative, the class of 0 is neutral, and each class has an additive inverse.",
        formal: "(i+j)+k ≡ i+(j+k),  i+j ≡ j+i,  i+0 ≡ i,  i+(n−i) ≡ 0  (mod n)",
      },
      {
        text: "A bijection that preserves the operation transports every group axiom, so the reduct is a cyclic group of order n generated by P1.",
        formal: "ord(P1) = n",
      },
    ],
  },
  {
    id: "P2",
    kind: "Proposition",
    title: "P0 is the unique left zero of STAR",
    statement:
      "For every level with at least two positions, placing P0 on the left forces the result to P0, and no other position has that property.",
    formal: "∀ n ≥ 2:  STAR_n(P0, x) = P0 for all x,  and z★x = z for all x ⟹ z = P0",
    proof: [
      {
        text: "Existence is the first branch of the definition, applied for every right operand.",
        formal: "STAR_n(P0, P_j) = P0",
      },
      {
        text: "For uniqueness, suppose a nonzero position were a left zero and choose the right operand that completes it to a full turn.",
        formal: "z = P_k, k ≠ 0;  take x = P_(n−k)",
      },
      {
        text: "The second branch then returns P0, which differs from the assumed left zero, so no nonzero position qualifies.",
        formal: "STAR_n(P_k, P_(n−k)) = P_((k + n − k) mod n) = P0 ≠ P_k",
      },
    ],
  },
  {
    id: "P3",
    kind: "Proposition",
    title: "P0 is the unique right-neutral element of STAR",
    statement: "Placing P0 on the right leaves every position unchanged, and no other position does so.",
    formal: "∀ n ≥ 2:  STAR_n(x, P0) = x for all x,  and x★e = x for all x ⟹ e = P0",
    proof: [
      {
        text: "Both branches of the definition return the left operand when the right operand is P0.",
        formal: "i = 0 ⟹ P0;  i ≠ 0 ⟹ P_((i+0) mod n) = P_i",
      },
      {
        text: "For uniqueness, test a candidate against the nonzero position P1, which is evaluated by the second branch.",
        formal: "e = P_k;  STAR_n(P1, P_k) = P_((1+k) mod n) = P1",
      },
      {
        text: "The equation forces the index of the candidate to vanish modulo n.",
        formal: "1 + k ≡ 1 (mod n) ⟹ k ≡ 0 ⟹ e = P0",
      },
    ],
  },
  {
    id: "P4",
    kind: "Corollary",
    title: "STAR has no two-sided identity",
    statement: "The two one-sided properties cannot be combined: no position acts neutrally from both sides at once.",
    formal: "∀ n ≥ 2:  ¬∃ e ∈ Q_n such that e★x = x = x★e for all x",
    proof: [
      { text: "By the previous proposition the only candidate for a right-neutral element is P0.", formal: "e = P0" },
      {
        text: "But P0 is a left zero, so from the left it destroys the other operand instead of preserving it.",
        formal: "STAR_n(P0, P1) = P0 ≠ P1",
      },
    ],
    boundary:
      "At the one-element level the two properties collapse into the same equation. That degenerate case is stated separately and is never used to support a claim about n ≥ 2.",
  },
  {
    id: "P5",
    kind: "Proposition",
    title: "STAR is neither commutative nor associative",
    statement:
      "Both failures are witnessed by explicit small counterexamples, so neither property can be assumed anywhere in the theory.",
    formal: "∀ n ≥ 2:  STAR_n(P0,P1) ≠ STAR_n(P1,P0)  and  (P1★P0)★P1 ≠ P1★(P0★P1)",
    proof: [
      {
        text: "Commutativity fails on the pair that puts P0 first on one side and second on the other.",
        formal: "P0★P1 = P0,  P1★P0 = P1",
      },
      {
        text: "For associativity, evaluate the same three operands under both bracketings at a level with three or more positions.",
        formal: "(P1★P0)★P1 = P1★P1 = P2;  P1★(P0★P1) = P1★P0 = P1",
      },
      {
        text: "At the two-element level the same bracketing pair still separates, so the failure holds at every nondegenerate level.",
        formal: "n = 2:  (P1★P0)★P1 = P0,  P1★(P0★P1) = P1",
      },
    ],
  },
  {
    id: "P6",
    kind: "Theorem",
    title: "The automorphism group of the full algebra is the unit group",
    statement:
      "Every reversible relabelling that preserves both laws and the named constant is multiplication of indices by a unit, and every unit gives such a relabelling.",
    formal: "Aut(A_n) ≅ U(n) = (Z/nZ)^×,  σ_u(P_i) = P_((ui) mod n),  |Aut(A_n)| = φ(n)",
    proof: [
      {
        text: "A unit is invertible modulo n, so multiplication by it permutes the positions and fixes P0.",
        formal: "gcd(u,n) = 1 ⟹ σ_u bijective,  σ_u(P0) = P0",
      },
      {
        text: "Multiplication distributes over residue addition, which gives preservation of PLUS.",
        formal: "u(i+j) ≡ ui + uj (mod n)",
      },
      {
        text: "It also preserves the STAR guard, because multiplying by a unit sends a nonzero index to a nonzero index.",
        formal: "ui ≡ 0 (mod n) ⟺ i ≡ 0 (mod n)",
      },
      {
        text: "Conversely PLUS preservation makes any automorphism determined by the image of the generator, and injectivity forces that image to be a unit.",
        formal: "σ(P_i) = P_((ui) mod n) with u = ι(σ(P1));  σ injective ⟹ gcd(u,n) = 1",
      },
    ],
  },
  {
    id: "P7",
    kind: "Proposition",
    title: "The typed catalogue has exactly 560 coordinates",
    statement:
      "The count is a complete finite enumeration, not an estimate: input pairs are counted first, then the two laws, then the two role placements.",
    formal: "Σ_(n=1)^(7) n² = 140;  2 × 140 = 280;  2 × 280 = 560;  560 − 4 = 556",
    proof: [
      {
        text: "A level with n positions has n² ordered input pairs, and the levels are disjoint.",
        formal: "|Q_n × Q_n| = n²",
      },
      {
        text: "Each pair is evaluated once under PLUS and once under STAR, which doubles the count.",
        formal: "2 × Σ n² = 280",
      },
      {
        text: "Each law cell is recorded once with the source on the row and once with the source on the column, which doubles it again.",
        formal: "2 × 280 = 560",
      },
      {
        text: "The current runtime activates the six levels above the degenerate one, leaving the four L1 coordinates as control-only.",
        formal: "560 − 4·1² = 556",
      },
    ],
  },
  {
    id: "P8",
    kind: "Theorem",
    title: "Nonzero embeddings exist exactly when the levels divide",
    statement:
      "A finer level can be carried into a coarser one without merging positions precisely when its size divides the target size.",
    formal: "∀ n, m ≥ 2:  Emb(A_n, A_m) ≠ ∅ ⟺ n ∣ m",
    proof: [
      {
        text: "PLUS preservation makes a homomorphism determined by the image of the generator.",
        formal: "f(P1) = P_k ⟹ f(P_i) = P_((ki) mod m)",
      },
      {
        text: "The map is injective exactly when that image still has full additive order n.",
        formal: "f injective ⟺ ord(P_k) = m / gcd(k,m) = n",
      },
      {
        text: "A cyclic group of order m contains an element of order n exactly when n divides m, which settles the forward direction.",
        formal: "∃ k : ord(P_k) = n ⟺ n ∣ m",
      },
      {
        text: "Conversely the scaled maps preserve STAR as well, because their index is zero only when the source index is zero.",
        formal: "k = u·(m/n), u ∈ U(n);  (ki) mod m = 0 ⟺ i ≡ 0 (mod n)",
      },
    ],
    boundary:
      "A mathematical embedding is a permission to move a distinction, not an authorisation to move data at runtime. Provenance, alignment, loss, and policy remain separate contracts.",
  },
  {
    id: "P9",
    kind: "Proposition",
    title: "The zero map always exists",
    statement:
      "Between any ordered pair of levels there is at least one structure-preserving map, so the phrase there is no map is never correct.",
    formal: "z_(n,m)(P_i) = P0 is a homomorphism A_n → A_m for every ordered pair (n, m)",
    proof: [
      {
        text: "The constant is preserved by construction, and both laws return P0 when both operands are P0.",
        formal: "PLUS_m(P0,P0) = P0 = STAR_m(P0,P0)",
      },
      {
        text: "Therefore both sides of every preservation equation evaluate to P0 regardless of the inputs.",
        formal: "z(F_n(x,y)) = P0 = F_m(z(x), z(y))",
      },
    ],
  },
  {
    id: "P10",
    kind: "Proposition",
    title: "The structural orbit count is 224 by two independent routes",
    statement:
      "Direct enumeration of orbits and the Burnside averaging formula reconstruct the same total, so the figure is checked twice rather than asserted once.",
    formal: "|X/G| = (1/|G|) Σ_(g∈G) |Fix(g)|;  4 × Σ_(n=1)^(7) pair_orbits(n) = 4 × 56 = 224",
    proof: [
      {
        text: "The unit group acts diagonally on ordered pairs, independently inside each level and each of the four family fibres.",
        formal: "u · (P_s, P_a) = (P_((us) mod n), P_((ua) mod n))",
      },
      {
        text: "Averaging fixed points over the group gives the per-level orbit counts, which agree cell for cell with a direct traversal.",
        formal: "pair_orbits(n) = (1/φ(n)) Σ_(u∈U(n)) |Fix(u)|²",
      },
      {
        text: "Adding the fibres gives the tower total; the separate sum of local group orders is a different quantity and is not one global group.",
        formal: "Σ pair_orbits = 1+4+5+10+7+20+9 = 56;  Σ |Aut(A_n)| = 18",
      },
    ],
  },
  {
    id: "P11",
    kind: "Proposition",
    title: "STAR admits no nontrivial congruence",
    statement:
      "Positions cannot be merged into a smaller well-defined quotient: any identification of two distinct positions collapses the entire level.",
    formal: "∀ n ≥ 2:  Con(S_n) = {Δ_(Q_n), Q_n × Q_n}",
    proof: [
      {
        text: "Assume a congruence identifies two distinct positions and use compatibility with STAR on both sides.",
        formal: "P_i ∼ P_j, i ≠ j",
      },
      {
        text: "The reset row separates P0 so sharply that the identification propagates: at L3, identifying P0 with P1 forces P0 with P2 as well.",
        formal: "P0★P1 = P0,  P1★P1 = P2 ⟹ P0 ∼ P2",
      },
      {
        text: "Iterating the argument reaches every position, so the relation is the universal one.",
        formal: "∼ = Q_n × Q_n",
      },
    ],
  },
];

export const academicTranslationKeys = [
  ...new Set([
    ...academicDefinitions.flatMap((entry) => [entry.title, entry.prose]),
    ...academicPropositions.flatMap((entry) => [
      entry.title,
      entry.statement,
      ...entry.proof.map((step) => step.text),
      ...(entry.boundary ? [entry.boundary] : []),
    ]),
  ]),
] as const;
