import type { TranslationDictionary } from "../translations";

export const academicRuExtra: TranslationDictionary = {
  "A Cayley table is the school multiplication table, written for a different rule.":
    "Таблица Кэли — это школьная таблица умножения, записанная для другого правила.",
  "A bijection that preserves the operation transports every group axiom, so the reduct is a cyclic group of order n generated by P1.":
    "Биекция, сохраняющая операцию, переносит все аксиомы группы, поэтому редукт — циклическая группа порядка n, порождённая P1.",
  "A bounded, partner-owned problem where explicit state and exact replay can be measured against an ordinary baseline.":
    "Ограниченная задача на данных партнёра, где явное состояние и точное воспроизведение можно измерить против обычной базовой линии.",
  "A cell holds one named position, never a probability or a score. Two runs on the same inputs cannot differ.":
    "В ячейке стоит одна именованная позиция, а не вероятность и не оценка. Два запуска на одних и тех же входах не могут разойтись.",
  "A cell is recorded together with the roles of its two inputs, so two steps that end on the same result still keep different records. That address is what a receipt can point at.":
    "Ячейка записывается вместе с ролями обоих входов, поэтому два шага, пришедшие к одному результату, сохраняют разные записи. Именно на этот адрес может сослаться протокол.",
  "A coordinate records the level, the law, and which of the two semantic roles occupies which table axis. Two coordinates with equal targets remain distinct records whenever their roles differ.":
    "Координата фиксирует уровень, закон и то, какая из двух семантических ролей стоит на какой оси таблицы. Две координаты с одинаковым результатом остаются разными записями, если их роли различаются.",
  "A cyclic group of order m contains an element of order n exactly when n divides m, which settles the forward direction.":
    "Циклическая группа порядка m содержит элемент порядка n тогда и только тогда, когда n делит m; это доказывает прямое направление.",
  "A finer level can be carried into a coarser one without merging positions precisely when its size divides the target size.":
    "Более дробный уровень можно перенести в более грубый без слияния позиций ровно тогда, когда его размер делит размер целевого уровня.",
  "A finite set of allowed positions": "Конечный набор допустимых позиций",
  "A finite table can be checked completely. A model cannot.":
    "Конечную таблицу можно проверить целиком. Модель — нельзя.",
  "A level with n positions has n² ordered input pairs, and the levels are disjoint.":
    "Уровень с n позициями даёт n² упорядоченных пар входов, и уровни не пересекаются.",
  "A mathematical embedding is a permission to move a distinction, not an authorisation to move data at runtime. Provenance, alignment, loss, and policy remain separate contracts.":
    "Математическое вложение — это разрешение перенести различие, а не право переносить данные во время исполнения. Происхождение, согласование, потери и политика остаются отдельными контрактами.",
  "A record that can be replayed": "Запись, которую можно воспроизвести",
  "A running engine over a fully enumerated finite universe, producing a machine-readable record for every run.":
    "Работающий движок над полностью перечисленным конечным универсумом, который на каждый запуск выдаёт машиночитаемую запись.",
  "A table of results for two inputs": "Таблица результатов для двух входов",
  "A unit is invertible modulo n, so multiplication by it permutes the positions and fixes P0.":
    "Единица обратима по модулю n, поэтому умножение на неё переставляет позиции и оставляет P0 на месте.",
  "A way for a decision-making system to hold its state in a small, named, completely written-out table instead of inside an opaque model.":
    "Способ для системы, принимающей решения, держать своё состояние в небольшой именованной полностью выписанной таблице, а не внутри непрозрачной модели.",
  "ACADEMIC REFERENCE": "АКАДЕМИЧЕСКИЙ СПРАВОЧНИК",
  "Academic reference": "Академический справочник",
  "Adding the fibres gives the tower total; the separate sum of local group orders is a different quantity and is not one global group.":
    "Сложение слоёв даёт итог по всей башне; отдельная сумма порядков локальных групп — другая величина и не является одной глобальной группой.",
  "An address for every cell": "Адрес у каждой ячейки",
  "Any published figure can be followed back down to the exact table cells it came from.":
    "Любую опубликованную величину можно проследить вниз до тех самых ячеек таблицы, из которых она получена.",
  "Assume a congruence identifies two distinct positions and use compatibility with STAR on both sides.":
    "Предположим, что конгруэнция отождествляет две различные позиции, и воспользуемся совместимостью со STAR с обеих сторон.",
  "At the one-element level the two properties collapse into the same equation. That degenerate case is stated separately and is never used to support a claim about n ≥ 2.":
    "На одноэлементном уровне оба свойства сводятся к одному и тому же уравнению. Этот вырожденный случай оговаривается отдельно и никогда не используется как подтверждение утверждения при n ≥ 2.",
  "At the two-element level the same bracketing pair still separates, so the failure holds at every nondegenerate level.":
    "На двухэлементном уровне та же пара расстановок скобок по-прежнему различается, поэтому отказ выполняется на каждом невырожденном уровне.",
  "Averaging fixed points over the group gives the per-level orbit counts, which agree cell for cell with a direct traversal.":
    "Усреднение неподвижных точек по группе даёт число орбит на каждом уровне, и оно ячейка в ячейку совпадает с прямым обходом.",
  "Because the table is finite and written down in advance, every step the system takes has an address, a result, and a record. There is no hidden remainder that only the model knows about.":
    "Поскольку таблица конечна и выписана заранее, у каждого шага системы есть адрес, результат и запись. Скрытого остатка, известного только модели, не остаётся.",
  "Because the table is fixed and the order of steps is recorded, the same run can be reproduced later on a different machine.":
    "Поскольку таблица зафиксирована, а порядок шагов записан, тот же запуск можно позднее воспроизвести на другой машине.",
  "Before any talk of architecture, agents, or evidence, there is a table of results for two inputs — the same object you met at school as the multiplication table. If you follow only this section, you will still know what GALO is made of.":
    "Прежде любых разговоров об архитектуре, агентах и доказательствах есть таблица результатов для двух входов — тот самый объект, который вы встречали в школе как таблицу умножения. Если вы прочитаете только этот раздел, вы всё равно будете знать, из чего сделан GALO.",
  "Between any ordered pair of levels there is at least one structure-preserving map, so the phrase there is no map is never correct.":
    "Между любой упорядоченной парой уровней существует хотя бы одно отображение, сохраняющее структуру, поэтому фраза «отображения не существует» никогда не верна.",
  "Both branches of the definition return the left operand when the right operand is P0.":
    "Обе ветви определения возвращают левый операнд, когда правый операнд равен P0.",
  "Both failures are witnessed by explicit small counterexamples, so neither property can be assumed anywhere in the theory.":
    "Оба отказа подтверждаются явными малыми контрпримерами, поэтому ни одно из этих свойств нельзя предполагать нигде в теории.",
  "Bounded selection": "Ограниченный отбор",
  "Bracketed program": "Программа со скобками",
  "But P0 is a left zero, so from the left it destroys the other operand instead of preserving it.":
    "Но P0 — левый нуль, поэтому слева он уничтожает второй операнд, а не сохраняет его.",
  "By the previous proposition the only candidate for a right-neutral element is P0.":
    "По предыдущему утверждению единственный кандидат на правый нейтральный элемент — P0.",
  "Carrier of a level": "Носитель уровня",
  Checkable: "Проверяемая",
  "Checking a table is not sampling or testing: every entry is inspected, and the check either passes on all of them or fails on a named one. That is what makes a claim about this layer arguable by someone who does not trust us.":
    "Проверка таблицы — это не выборка и не тестирование: просматривается каждая запись, и проверка либо проходит на всех, либо падает на конкретной названной. Именно поэтому утверждение об этом слое может оспорить тот, кто нам не доверяет.",
  "Commutativity fails on the pair that puts P0 first on one side and second on the other.":
    "Коммутативность нарушается на той паре, где P0 стоит первым с одной стороны и вторым с другой.",
  Complete: "Полная",
  "Conversely PLUS preservation makes any automorphism determined by the image of the generator, and injectivity forces that image to be a unit.":
    "Обратно, сохранение PLUS делает любой автоморфизм полностью определённым образом порождающего элемента, а инъективность вынуждает этот образ быть единицей.",
  "Conversely the scaled maps preserve STAR as well, because their index is zero only when the source index is zero.":
    "Обратно, масштабированные отображения сохраняют и STAR, потому что их индекс равен нулю только тогда, когда нулю равен исходный индекс.",
  Corollary: "Следствие",
  Definition: "Определение",
  Definitions: "Определения",
  "Definitions, propositions, and proofs in ordinary mathematical form.":
    "Определения, утверждения и доказательства в обычной математической форме.",
  "Direct enumeration of orbits and the Burnside averaging formula reconstruct the same total, so the figure is checked twice rather than asserted once.":
    "Прямое перечисление орбит и формула усреднения Бёрнсайда дают один и тот же итог, поэтому величина проверена дважды, а не заявлена один раз.",
  "Each bounded run writes what it checked, what it executed, and where it stopped. Anyone with the record can run the same steps again and compare cell by cell.":
    "Каждый ограниченный запуск записывает, что он проверил, что исполнил и где остановился. Любой, у кого есть эта запись, может повторить те же шаги и сравнить их ячейка за ячейкой.",
  "Each law cell is recorded once with the source on the row and once with the source on the column, which doubles it again.":
    "Каждая ячейка закона записывается один раз с источником в строке и один раз с источником в столбце, что снова удваивает число.",
  "Each layer is built only from what the layer below has already established.":
    "Каждый слой построен только из того, что уже установил слой под ним.",
  "Each pair is evaluated once under PLUS and once under STAR, which doubles the count.":
    "Каждая пара вычисляется один раз по PLUS и один раз по STAR, что удваивает число.",
  "Each position is identified with one residue class modulo n. The map is a bijection, which is what lets exact arithmetic be carried out on labels without treating a label as a quantity.":
    "Каждая позиция отождествляется с одним классом вычетов по модулю n. Это отображение биективно, и именно оно позволяет вести точную арифметику на метках, не считая метку величиной.",
  "End of proof": "Конец доказательства",
  "Every allowed pair of inputs has a row, a column, and one filled cell. There is no case the table forgot to cover.":
    "У каждой допустимой пары входов есть строка, столбец и одна заполненная ячейка. Нет случая, который таблица забыла бы покрыть.",
  "Every number published on this site traces back to a finite table.":
    "Каждое число, опубликованное на этом сайте, восходит к конечной таблице.",
  "Every reversible relabelling that preserves both laws and the named constant is multiplication of indices by a unit, and every unit gives such a relabelling.":
    "Каждое обратимое переименование, сохраняющее оба закона и именованную константу, есть умножение индексов на единицу группы обратимых элементов, и каждая такая единица задаёт такое переименование.",
  "Everything on this site is built on one finite table.": "Всё на этом сайте построено на одной конечной таблице.",
  Exact: "Точная",
  "Existence is the first branch of the definition, applied for every right operand.":
    "Существование — это первая ветвь определения, применённая для любого правого операнда.",
  "For associativity, evaluate the same three operands under both bracketings at a level with three or more positions.":
    "Для ассоциативности вычислите одни и те же три операнда при обеих расстановках скобок на уровне с тремя и более позициями.",
  "For every level with at least two positions, placing P0 on the left forces the result to P0, and no other position has that property.":
    "На каждом уровне не менее чем с двумя позициями размещение P0 слева заставляет результат стать P0, и никакая другая позиция таким свойством не обладает.",
  "For uniqueness, suppose a nonzero position were a left zero and choose the right operand that completes it to a full turn.":
    "Для единственности предположим, что левым нулём была бы ненулевая позиция, и выберем правый операнд, который доводит её до полного оборота.",
  "For uniqueness, test a candidate against the nonzero position P1, which is evaluated by the second branch.":
    "Для единственности проверьте кандидата на ненулевой позиции P1, которая вычисляется по второй ветви.",
  "Four properties a table has and a trained model does not.":
    "Четыре свойства, которые есть у таблицы и которых нет у обученной модели.",
  "GALO first declares how many positions exist. Three positions give a three-by-three table; seven give a seven-by-seven one. Nothing outside the declared list can ever appear.":
    "GALO сначала объявляет, сколько существует позиций. Три позиции дают таблицу три на три, семь — семь на семь. Ничто вне объявленного списка появиться не может.",
  "GALO is built so the trace is the product: what state the system was in, which rule fired, what it was allowed to do, and what it recorded. That is the artefact a reviewer, an auditor, or a counterparty can actually examine.":
    "GALO построен так, что продуктом является сам след: в каком состоянии была система, какое правило сработало, что ей было разрешено и что она записала. Именно этот артефакт может изучить рецензент, аудитор или контрагент.",
  "IN PLAIN LANGUAGE": "ПРОСТЫМИ СЛОВАМИ",
  "If you read one section on this site, read this one.":
    "Если вы прочитаете на этом сайте только один раздел — прочитайте этот.",
  "In long-running and regulated work, the expensive failure is not a wrong answer — it is a wrong answer nobody can trace.":
    "В долгих и регулируемых процессах дорого обходится не ошибочный ответ, а ошибочный ответ, который никто не может проследить.",
  "Index map": "Отображение индексов",
  "It also preserves the STAR guard, because multiplying by a unit sends a nonzero index to a nonzero index.":
    "Оно сохраняет и охранное условие STAR, потому что умножение на единицу переводит ненулевой индекс в ненулевой.",
  "It is narrow on purpose: two fixed input patterns, one step per run, no learning. Everything inside that boundary is checked on every build; nothing outside it is claimed.":
    "Он намеренно узок: два фиксированных входных шаблона, один шаг на запуск, никакого обучения. Всё внутри этой границы проверяется при каждой сборке; ничто вне её не заявляется.",
  "Iterating the argument reaches every position, so the relation is the universal one.":
    "Повторение этого рассуждения достигает каждой позиции, поэтому отношение оказывается универсальным.",
  "Layer stack from the Cayley table to published evidence":
    "Стопка слоёв от таблицы Кэли до опубликованных доказательств",
  "Learning, a trained world model, and any measured result outside our own accounting.":
    "Обучение, обученная модель мира и любой измеренный результат за пределами нашего собственного учёта.",
  "Multiplication distributes over residue addition, which gives preservation of PLUS.":
    "Умножение дистрибутивно относительно сложения вычетов, что и даёт сохранение PLUS.",
  "Multiplication, three by three": "Умножение, три на три",
  "No mathematics, no acronyms. Six questions a non-technical reader asks first, answered in the order they are usually asked.":
    "Без математики и без аббревиатур. Шесть вопросов, которые нетехнический читатель задаёт первыми, в том порядке, в каком их обычно задают.",
  "Nonzero embeddings exist exactly when the levels divide":
    "Ненулевые вложения существуют ровно тогда, когда уровни делятся",
  "Notation is fixed once and used throughout. Positions are written P with a subscript, the level is written L with a subscript, and every formula is displayed left to right in every language of this site.":
    "Обозначения задаются один раз и используются далее без изменений. Позиции пишутся как P с нижним индексом, уровень — как L с нижним индексом, и любая формула во всех языках этого сайта отображается слева направо.",
  "P0 is the unique left zero of STAR": "P0 — единственный левый нуль STAR",
  "P0 is the unique right-neutral element of STAR": "P0 — единственный правый нейтральный элемент STAR",
  "PLUS is total and closed: it is defined on every ordered pair and its value always lies in the same carrier. Its complete graph is the PLUS Cayley table of that level.":
    "PLUS всюду определён и замкнут: он задан на каждой упорядоченной паре, и его значение всегда лежит в том же носителе. Его полный график — это таблица Кэли PLUS данного уровня.",
  "PLUS on three positions": "PLUS на трёх позициях",
  "PLUS preservation makes a homomorphism determined by the image of the generator.":
    "Сохранение PLUS делает гомоморфизм полностью определённым образом порождающего элемента.",
  "Pick a row, pick a column, read the cell where they cross. That is the whole reading procedure, and it is identical on both sides below.":
    "Выберите строку, выберите столбец, прочитайте ячейку на их пересечении. Это вся процедура чтения, и слева и справа ниже она одна и та же.",
  "Placing P0 on the right leaves every position unchanged, and no other position does so.":
    "Размещение P0 справа оставляет любую позицию неизменной, и никакая другая позиция так не делает.",
  "Positions cannot be merged into a smaller well-defined quotient: any identification of two distinct positions collapses the entire level.":
    "Позиции нельзя слить в меньшее корректно определённое факторпространство: любое отождествление двух различных позиций схлопывает весь уровень.",
  Proof: "Доказательство",
  Proposition: "Утверждение",
  "Propositions and proofs": "Утверждения и доказательства",
  "Published evidence": "Опубликованные доказательства",
  "Read the plain-language briefing": "Прочитать объяснение простыми словами",
  "Read the stack from the bottom. Each layer only adds what the layer beneath it can already support, and no layer may be quoted as if it were a higher one.":
    "Читайте стопку снизу вверх. Каждый слой добавляет только то, что уже способен выдержать слой под ним, и ни один слой нельзя цитировать так, будто он более высокий.",
  "Reading downward": "Чтение сверху вниз",
  "Reading upward": "Чтение снизу вверх",
  Replayable: "Воспроизводимая",
  "Residue addition is associative and commutative, the class of 0 is neutral, and each class has an additive inverse.":
    "Сложение вычетов ассоциативно и коммутативно, класс нуля нейтрален, и у каждого класса есть аддитивный обратный.",
  "Row 2, column 3, cell 6.": "Строка 2, столбец 3, ячейка 6.",
  "Row P1, column P2, cell P0.": "Строка P1, столбец P2, ячейка P0.",
  "STAR admits no nontrivial congruence": "STAR не допускает нетривиальных конгруэнций",
  "STAR agrees with PLUS on every row except the first, where a single guard on the left operand overrides the sum. This one clause is the source of every asymmetry proved below.":
    "STAR совпадает с PLUS на каждой строке, кроме первой, где единственное охранное условие на левом операнде перекрывает сумму. Из этого одного условия вытекают все асимметрии, доказанные ниже.",
  "STAR has no two-sided identity": "У STAR нет двустороннего нейтрального элемента",
  "STAR is neither commutative nor associative": "STAR не коммутативен и не ассоциативен",
  "START WITH THE TABLE": "НАЧНИТЕ С ТАБЛИЦЫ",
  "Scope of this result:": "Область действия этого результата:",
  "See the table everything is built on": "Посмотреть таблицу, на которой всё построено",
  "Six stacked bars read from the bottom upward: the Cayley table, the typed coordinate, the bracketed program, the bounded selection, the execution receipt, and the published evidence. An arrow runs upward through all of them.":
    "Шесть полос, лежащих друг на друге и читаемых снизу вверх: таблица Кэли, типизированная координата, программа со скобками, ограниченный отбор, протокол исполнения и опубликованные доказательства. Сквозь все них проходит стрелка вверх.",
  "Start with the table": "Начните с таблицы",
  "Steps composed into a program": "Шаги, собранные в программу",
  "THE WHOLE PROJECT RESTS ON ONE OBJECT": "ВЕСЬ ПРОЕКТ ДЕРЖИТСЯ НА ОДНОМ ОБЪЕКТЕ",
  "That evaluation has not been run. Until it is, no claim about external gain appears anywhere on this site, and the numbers published here describe internal structure only.":
    "Такая оценка не проводилась. Пока она не проведена, на сайте нигде не появляется утверждение о внешнем выигрыше, а публикуемые здесь числа описывают только внутреннюю структуру.",
  "The PLUS reduct is the cyclic group of order n": "Редукт по PLUS — циклическая группа порядка n",
  "The automorphism group of the full algebra is the unit group":
    "Группа автоморфизмов полной алгебры — это группа обратимых элементов",
  "The constant is preserved by construction, and both laws return P0 when both operands are P0.":
    "Константа сохраняется по построению, и оба закона возвращают P0, когда оба операнда равны P0.",
  "The count is a complete finite enumeration, not an estimate: input pairs are counted first, then the two laws, then the two role placements.":
    "Подсчёт — это полное конечное перечисление, а не оценка: сначала считаются пары входов, затем два закона, затем два размещения ролей.",
  "The current runtime activates the six levels above the degenerate one, leaving the four L1 coordinates as control-only.":
    "Текущая среда исполнения активирует шесть уровней выше вырожденного, оставляя четыре координаты L1 только управляющими.",
  "The entries are names of positions rather than quantities, and the count wraps: after the last position it returns to the first.":
    "Записи — это названия позиций, а не величины, и счёт замыкается: после последней позиции он возвращается к первой.",
  "The equation forces the index of the candidate to vanish modulo n.":
    "Уравнение вынуждает индекс кандидата обратиться в нуль по модулю n.",
  "The index map is a bijection and transports the operation onto residue addition, because the definition of PLUS is stated directly in terms of that addition.":
    "Отображение индексов биективно и переносит операцию в сложение вычетов, потому что само определение PLUS сформулировано через это сложение.",
  "The law PLUS": "Закон PLUS",
  "The law STAR": "Закон STAR",
  "The level fixes a finite set of named positions before any operation is defined. Nothing outside this list may appear as an input or as a result.":
    "Уровень задаёт конечное множество именованных позиций ещё до определения любой операции. Ничто вне этого списка не может появиться ни на входе, ни в результате.",
  "The map is injective exactly when that image still has full additive order n.":
    "Отображение инъективно ровно тогда, когда этот образ сохраняет полный аддитивный порядок n.",
  "The one technical fact worth carrying away": "Один технический факт, который стоит унести с собой",
  "The reset row separates P0 so sharply that the identification propagates: at L3, identifying P0 with P1 forces P0 with P2 as well.":
    "Строка сброса отделяет P0 настолько резко, что отождествление распространяется: на L3 отождествление P0 с P1 вынуждает отождествить P0 и с P2.",
  "The result of one cell can be the input of the next. Because STAR is order-sensitive, the bracketing is part of the program and has to be written down rather than assumed.":
    "Результат одной ячейки может стать входом следующей. Поскольку STAR чувствителен к порядку, расстановка скобок — часть программы, и её нужно записать, а не подразумевать.",
  "The same carrier is studied under one law, under the other law, and under both at once. The full expansion has signature (2,2,0): two binary operations and one named constant.":
    "Один и тот же носитель изучается под одним законом, под другим и под обоими сразу. Полное расширение имеет сигнатуру (2,2,0): две бинарные операции и одна именованная константа.",
  "The second branch then returns P0, which differs from the assumed left zero, so no nonzero position qualifies.":
    "Тогда вторая ветвь возвращает P0, что отличается от предполагаемого левого нуля, поэтому ни одна ненулевая позиция не подходит.",
  "The structural orbit count is 224 by two independent routes":
    "Структурное число орбит равно 224 по двум независимым путям",
  "The table GALO starts from": "Таблица, с которой начинается GALO",
  "The table you already know": "Таблица, которую вы уже знаете",
  "The three structures": "Три структуры",
  "The two one-sided properties cannot be combined: no position acts neutrally from both sides at once.":
    "Два односторонних свойства нельзя соединить: ни одна позиция не действует нейтрально сразу с обеих сторон.",
  "The typed catalogue has exactly 560 coordinates": "В типизированном каталоге ровно 560 координат",
  "The unit group acts diagonally on ordered pairs, independently inside each level and each of the four family fibres.":
    "Группа обратимых элементов действует диагонально на упорядоченных парах — независимо внутри каждого уровня и каждого из четырёх слоёв семейств.",
  "The whole table can be regenerated from the formula and compared entry by entry, so a disagreement points at a specific cell.":
    "Всю таблицу можно заново получить из формулы и сравнить запись за записью, поэтому расхождение указывает на конкретную ячейку.",
  "The zero map always exists": "Нулевое отображение существует всегда",
  Theorem: "Теорема",
  "Therefore both sides of every preservation equation evaluate to P0 regardless of the inputs.":
    "Поэтому обе части любого уравнения сохранения дают P0 независимо от входов.",
  "These are stated as open work with named preconditions, not implied as done. The evidence page lists each one and the milestone it has actually reached.":
    "Они заявлены как открытая работа с названными предусловиями, а не поданы как сделанные. На странице доказательств перечислено каждое из них и достигнутый рубеж.",
  "This is the entire technical bet. A finite table is a weaker object than a learned model, and that weakness is exactly what makes each of the four properties below hold without exception.":
    "В этом и состоит вся техническая ставка. Конечная таблица — более слабый объект, чем обученная модель, и именно эта слабость заставляет каждое из четырёх свойств ниже выполняться без исключений.",
  "This section states the kernel the way a referee would expect to read it: numbered definitions first, then each structural claim with a complete proof. Every statement here is also re-derived by the automated checks that run on each build, so the prose and the machine agree by construction.":
    "Этот раздел излагает ядро так, как ожидал бы прочитать рецензент: сначала нумерованные определения, затем каждое структурное утверждение с полным доказательством. Каждое утверждение здесь заново выводится автоматическими проверками при каждой сборке, поэтому текст и машина согласованы по построению.",
  "Two inputs go in, one result comes out, and every possible pair of inputs already has its own filled cell.":
    "Два входа входят, один результат выходит, и у каждой возможной пары входов уже есть своя заполненная ячейка.",
  "Two laws fill the same grid. PLUS moves around the ring. STAR does the same except that one input on the left resets the answer. Both tables are written out in full, not approximated.":
    "Одну и ту же сетку заполняют два закона. PLUS движется по кольцу. STAR делает то же самое, за исключением того, что один вход слева обнуляет ответ. Обе таблицы выписаны полностью, а не приближённо.",
  "Two rules, filled in completely": "Два правила, заполненных до конца",
  "Under PLUS the carrier is a cyclic group: the operation is associative and commutative, P0 is a two-sided identity, and every position has an inverse.":
    "Под действием PLUS носитель является циклической группой: операция ассоциативна и коммутативна, P0 — двусторонний нейтральный элемент, и у каждой позиции есть обратная.",
  "Underneath every diagram, number, and record on this site there is a finite table of results for two inputs — a Cayley table. It is written out completely in advance, so it can be checked entry by entry rather than trusted.":
    "Под каждой схемой, каждым числом и каждой записью на этом сайте лежит конечная таблица результатов для двух входов — таблица Кэли. Она выписана полностью и заранее, поэтому её можно проверить запись за записью, а не принимать на веру.",
  "WHY A FINITE TABLE AND NOT A MODEL": "ПОЧЕМУ КОНЕЧНАЯ ТАБЛИЦА, А НЕ МОДЕЛЬ",
  "What does not work yet?": "Что пока не работает?",
  "What is actually being built?": "Что на самом деле строится?",
  "What is different": "Что отличается",
  "What is the same": "Что совпадает",
  "What these results do not establish:": "Чего эти результаты не устанавливают:",
  "What works today?": "Что работает сегодня?",
  "What would change your mind?": "Что могло бы изменить вашу оценку?",
  "Where is the commercial value?": "В чём коммерческая ценность?",
  "Why does a table matter?": "Почему важна именно таблица?",
  "YOU HAVE READ ONE OF THESE BEFORE": "ВЫ УЖЕ ЧИТАЛИ ТАКУЮ ТАБЛИЦУ",
  "You already know one: the multiplication table. Choose a row, choose a column, read the cell. A Cayley table is the same idea applied to any rule that takes two inputs.":
    "Одну вы уже знаете — таблицу умножения. Выберите строку, выберите столбец, прочитайте ячейку. Таблица Кэли — та же идея, применённая к любому правилу с двумя входами.",
  "a declared filter chain over a finite universe": "объявленная цепочка фильтров над конечным универсумом",
  "cells composed into an explicit tree": "ячейки, собранные в явное дерево",
  "counts and boundaries anyone can recompute": "числа и границы, которые каждый может пересчитать",
  "one filled cell per input pair": "по одной заполненной ячейке на пару входов",
  "same procedure": "одна и та же процедура",
  "the cell plus the roles of its inputs": "ячейка плюс роли её входов",
  "they are theorems about a finite algebra. They do not by themselves establish semantics, learning, a trained world model, external operational gain, or general intelligence — each of those needs its own evidence and is listed separately with its current status.":
    "это теоремы о конечной алгебре. Сами по себе они не устанавливают семантику, обучение, обученную модель мира, внешний операционный выигрыш или общий интеллект — каждому из этих пунктов нужны собственные доказательства, и каждый указан отдельно со своим текущим статусом.",
  "what ran, in what scope, with what status": "что выполнялось, в какой области и с каким статусом",
};

export const academicZhExtra: TranslationDictionary = {
  "A Cayley table is the school multiplication table, written for a different rule.":
    "凯莱表就是学校里的乘法表，只不过写的是另一条规则。",
  "A bijection that preserves the operation transports every group axiom, so the reduct is a cyclic group of order n generated by P1.":
    "保持运算的双射会把每一条群公理都搬运过去，因此该约化结构是由 P1 生成的 n 阶循环群。",
  "A bounded, partner-owned problem where explicit state and exact replay can be measured against an ordinary baseline.":
    "一个范围受限、由合作方掌握数据的问题，在那里显式状态与精确重放可以与一条普通基线相比较并被测量。",
  "A cell holds one named position, never a probability or a score. Two runs on the same inputs cannot differ.":
    "单元格里放的是一个有名字的位置，而不是概率或评分。相同输入的两次运行不可能给出不同结果。",
  "A cell is recorded together with the roles of its two inputs, so two steps that end on the same result still keep different records. That address is what a receipt can point at.":
    "单元格是连同两个输入的角色一起被记录的，因此两个落到同一结果的步骤依然保有不同的记录。回执能指向的正是这个地址。",
  "A coordinate records the level, the law, and which of the two semantic roles occupies which table axis. Two coordinates with equal targets remain distinct records whenever their roles differ.":
    "坐标记录了层级、法则，以及两个语义角色各自占据表格的哪一条轴。两个结果相同的坐标，只要角色不同，就仍是不同的记录。",
  "A cyclic group of order m contains an element of order n exactly when n divides m, which settles the forward direction.":
    "m 阶循环群含有 n 阶元素，当且仅当 n 整除 m；这就证明了正向。",
  "A finer level can be carried into a coarser one without merging positions precisely when its size divides the target size.":
    "只有当细层级的规模整除粗层级的规模时，细层级才能被搬进粗层级而不合并任何位置。",
  "A finite set of allowed positions": "一组有限的、被允许的位置",
  "A finite table can be checked completely. A model cannot.": "有限的表格可以被完整检查。模型不能。",
  "A level with n positions has n² ordered input pairs, and the levels are disjoint.":
    "含 n 个位置的层级有 n² 个有序输入对，而各层级互不相交。",
  "A mathematical embedding is a permission to move a distinction, not an authorisation to move data at runtime. Provenance, alignment, loss, and policy remain separate contracts.":
    "数学上的嵌入，是搬运一个区分的许可，而不是在运行时搬运数据的授权。来源、对齐、损失与策略仍是各自独立的契约。",
  "A record that can be replayed": "一条可以被重放的记录",
  "A running engine over a fully enumerated finite universe, producing a machine-readable record for every run.":
    "一个运行在完全枚举的有限全集之上的引擎，每一次运行都产出一条机器可读的记录。",
  "A table of results for two inputs": "一张给两个输入用的结果表",
  "A unit is invertible modulo n, so multiplication by it permutes the positions and fixes P0.":
    "单位元素在模 n 意义下可逆，因此乘以它会置换各个位置，并让 P0 保持不动。",
  "A way for a decision-making system to hold its state in a small, named, completely written-out table instead of inside an opaque model.":
    "一种让决策系统把自身状态放进一张小而有名字、且已完整写出的表格里的办法，而不是放进一个不透明的模型里。",
  "ACADEMIC REFERENCE": "学术参考",
  "Academic reference": "学术参考",
  "Adding the fibres gives the tower total; the separate sum of local group orders is a different quantity and is not one global group.":
    "把各纤维相加得到整座塔的总数；而各局部群阶数的那个单独求和是另一个量，并不是一个全局的群。",
  "An address for every cell": "每个单元格都有地址",
  "Any published figure can be followed back down to the exact table cells it came from.":
    "任何已发布的数字，都可以沿着这条链向下追溯到它所出自的那些表格单元。",
  "Assume a congruence identifies two distinct positions and use compatibility with STAR on both sides.":
    "假设某个同余把两个不同的位置等同起来，然后从两侧使用与 STAR 的相容性。",
  "At the one-element level the two properties collapse into the same equation. That degenerate case is stated separately and is never used to support a claim about n ≥ 2.":
    "在只有一个元素的层级上，这两条性质塌缩成同一个等式。这个退化情形被单独说明，且从不用来支持关于 n ≥ 2 的任何断言。",
  "At the two-element level the same bracketing pair still separates, so the failure holds at every nondegenerate level.":
    "在两个元素的层级上，同一对加括号方式依然给出不同结果，因此这一失败在每个非退化层级上都成立。",
  "Averaging fixed points over the group gives the per-level orbit counts, which agree cell for cell with a direct traversal.":
    "对群求不动点的平均，给出各层级的轨道数，并与逐格的直接遍历完全一致。",
  "Because the table is finite and written down in advance, every step the system takes has an address, a result, and a record. There is no hidden remainder that only the model knows about.":
    "由于这张表是有限的、并且事先就已写出，系统走的每一步都有地址、有结果、有记录。不会留下只有模型自己知道的隐藏余量。",
  "Because the table is fixed and the order of steps is recorded, the same run can be reproduced later on a different machine.":
    "由于表格是固定的、步骤顺序也被记录下来，同一次运行可以稍后在另一台机器上重现。",
  "Before any talk of architecture, agents, or evidence, there is a table of results for two inputs — the same object you met at school as the multiplication table. If you follow only this section, you will still know what GALO is made of.":
    "在谈架构、谈智能体、谈证据之前，先有一张给两个输入用的结果表——正是你在学校里见过的那个东西：乘法表。哪怕你只读这一节，你也已经知道 GALO 是由什么做成的。",
  "Between any ordered pair of levels there is at least one structure-preserving map, so the phrase there is no map is never correct.":
    "在任意一对有序的层级之间，至少存在一个保持结构的映射，因此「不存在映射」这句话从来都不成立。",
  "Both branches of the definition return the left operand when the right operand is P0.":
    "当右操作数是 P0 时，定义的两个分支都返回左操作数。",
  "Both failures are witnessed by explicit small counterexamples, so neither property can be assumed anywhere in the theory.":
    "两处失败都由明确的小反例作证，因此在整套理论中的任何地方都不能预设这两条性质。",
  "Bounded selection": "受限的候选选择",
  "Bracketed program": "带括号的程序",
  "But P0 is a left zero, so from the left it destroys the other operand instead of preserving it.":
    "但 P0 是左零元，因此放在左边时它摧毁另一个操作数，而不是保留它。",
  "By the previous proposition the only candidate for a right-neutral element is P0.":
    "由上一条命题，右中性元的唯一候选是 P0。",
  "Carrier of a level": "层级的载体",
  Checkable: "可核查",
  "Checking a table is not sampling or testing: every entry is inspected, and the check either passes on all of them or fails on a named one. That is what makes a claim about this layer arguable by someone who does not trust us.":
    "检查一张表不是抽样，也不是测试：每一条记录都被查看，检查要么在全部记录上通过，要么在某一条被点名的记录上失败。正因如此，关于这一层的论断，一个并不信任我们的人也能提出异议。",
  "Commutativity fails on the pair that puts P0 first on one side and second on the other.":
    "在把 P0 放在一侧的第一位、又放在另一侧的第二位的那一对上，交换律失效。",
  Complete: "完整",
  "Conversely PLUS preservation makes any automorphism determined by the image of the generator, and injectivity forces that image to be a unit.":
    "反过来，对 PLUS 的保持使任何自同构完全由生成元的像所决定，而单射性迫使这个像必须是一个单位。",
  "Conversely the scaled maps preserve STAR as well, because their index is zero only when the source index is zero.":
    "反过来，那些按比例缩放的映射同样保持 STAR，因为只有当源索引为零时它们的索引才为零。",
  Corollary: "推论",
  Definition: "定义",
  Definitions: "定义",
  "Definitions, propositions, and proofs in ordinary mathematical form.": "以通常的数学形式给出的定义、命题与证明。",
  "Direct enumeration of orbits and the Burnside averaging formula reconstruct the same total, so the figure is checked twice rather than asserted once.":
    "对轨道的直接枚举与伯恩赛德平均公式重建出同一个总数，因此这个数字是被核对了两次，而不是被断言了一次。",
  "Each bounded run writes what it checked, what it executed, and where it stopped. Anyone with the record can run the same steps again and compare cell by cell.":
    "每一次受限运行都会写下它检查了什么、执行了什么、在哪里停下。任何拿到这条记录的人，都可以再跑一遍同样的步骤并逐格比对。",
  "Each law cell is recorded once with the source on the row and once with the source on the column, which doubles it again.":
    "每个法则单元格都被记录两次：一次源在行上，一次源在列上，于是数目再翻一倍。",
  "Each layer is built only from what the layer below has already established.":
    "每一层都只用下面那一层已经确立的东西来搭建。",
  "Each pair is evaluated once under PLUS and once under STAR, which doubles the count.":
    "每个输入对分别在 PLUS 与 STAR 下各求值一次，于是数目翻倍。",
  "Each position is identified with one residue class modulo n. The map is a bijection, which is what lets exact arithmetic be carried out on labels without treating a label as a quantity.":
    "每个位置都与模 n 的一个同余类相对应。这个映射是双射，正是它让我们能在标签上做精确的算术，而不必把标签当成数量。",
  "End of proof": "证毕",
  "Every allowed pair of inputs has a row, a column, and one filled cell. There is no case the table forgot to cover.":
    "每一对被允许的输入都有行、有列，以及一个被填好的单元格。不存在被表格遗漏的情形。",
  "Every number published on this site traces back to a finite table.":
    "本站发布的每一个数字，都可以追溯回一张有限的表格。",
  "Every reversible relabelling that preserves both laws and the named constant is multiplication of indices by a unit, and every unit gives such a relabelling.":
    "每一个既保持两条法则、又保持那个有名字的常量的可逆重命名，都是把索引乘以一个单位；反过来每个单位也给出这样一个重命名。",
  "Everything on this site is built on one finite table.": "本站的一切，都建立在一张有限的表格之上。",
  Exact: "精确",
  "Existence is the first branch of the definition, applied for every right operand.":
    "存在性就是定义的第一个分支，对任意右操作数都适用。",
  "For associativity, evaluate the same three operands under both bracketings at a level with three or more positions.":
    "关于结合律：在一个至少有三个位置的层级上，用两种加括号方式对同样三个操作数求值。",
  "For every level with at least two positions, placing P0 on the left forces the result to P0, and no other position has that property.":
    "在任何至少含两个位置的层级上，把 P0 放在左边就迫使结果成为 P0，而没有别的位置具备这一性质。",
  "For uniqueness, suppose a nonzero position were a left zero and choose the right operand that completes it to a full turn.":
    "为证唯一性，假设某个非零位置是左零元，并选取那个把它补足成整整一圈的右操作数。",
  "For uniqueness, test a candidate against the nonzero position P1, which is evaluated by the second branch.":
    "为证唯一性，用非零位置 P1 来检验候选者，它由第二个分支求值。",
  "Four properties a table has and a trained model does not.": "表格具备、而训练出来的模型不具备的四条性质。",
  "GALO first declares how many positions exist. Three positions give a three-by-three table; seven give a seven-by-seven one. Nothing outside the declared list can ever appear.":
    "GALO 首先声明存在多少个位置。三个位置给出一张三乘三的表，七个给出七乘七。已声明清单之外的东西永远不会出现。",
  "GALO is built so the trace is the product: what state the system was in, which rule fired, what it was allowed to do, and what it recorded. That is the artefact a reviewer, an auditor, or a counterparty can actually examine.":
    "GALO 的构建方式，使得「痕迹」本身就是产品：系统当时处在什么状态、哪条规则触发了、它被允许做什么、它记录了什么。这正是评审者、审计师或交易对手真正能够查验的东西。",
  "IN PLAIN LANGUAGE": "用大白话说",
  "If you read one section on this site, read this one.": "如果你在本站只读一节，就读这一节。",
  "In long-running and regulated work, the expensive failure is not a wrong answer — it is a wrong answer nobody can trace.":
    "在长期运行的、受监管的工作里，代价高昂的不是一个错误答案，而是一个谁也追溯不了的错误答案。",
  "Index map": "索引映射",
  "It also preserves the STAR guard, because multiplying by a unit sends a nonzero index to a nonzero index.":
    "它同样保持 STAR 的那个守卫条件，因为乘以一个单位会把非零索引仍然送成非零索引。",
  "It is narrow on purpose: two fixed input patterns, one step per run, no learning. Everything inside that boundary is checked on every build; nothing outside it is claimed.":
    "它是刻意做窄的：两个固定的输入模式、每次运行一步、没有学习。这条边界之内的一切在每次构建时都被检查；边界之外的一切都不作声称。",
  "Iterating the argument reaches every position, so the relation is the universal one.":
    "把这个论证反复施行，就会覆盖每一个位置，于是该关系成为全域关系。",
  "Layer stack from the Cayley table to published evidence": "从凯莱表到已发布证据的层级堆叠",
  "Learning, a trained world model, and any measured result outside our own accounting.":
    "学习、一个训练好的世界模型，以及任何超出我们自身记账范围的、被测量出来的结果。",
  "Multiplication distributes over residue addition, which gives preservation of PLUS.":
    "乘法对同余加法满足分配律，这就给出了对 PLUS 的保持。",
  "Multiplication, three by three": "乘法，三乘三",
  "No mathematics, no acronyms. Six questions a non-technical reader asks first, answered in the order they are usually asked.":
    "没有数学，也没有缩写。六个非技术读者最先会问的问题，按人们通常提问的顺序作答。",
  "Nonzero embeddings exist exactly when the levels divide": "非零嵌入恰好在层级之间整除时存在",
  "Notation is fixed once and used throughout. Positions are written P with a subscript, the level is written L with a subscript, and every formula is displayed left to right in every language of this site.":
    "记号只约定一次，此后通篇沿用。位置写作带下标的 P，层级写作带下标的 L；在本站的所有语言中，每一条公式都按从左到右显示。",
  "P0 is the unique left zero of STAR": "P0 是 STAR 唯一的左零元",
  "P0 is the unique right-neutral element of STAR": "P0 是 STAR 唯一的右中性元",
  "PLUS is total and closed: it is defined on every ordered pair and its value always lies in the same carrier. Its complete graph is the PLUS Cayley table of that level.":
    "PLUS 是全定义且封闭的：它在每一个有序对上都有定义，其取值也始终落在同一个载体之内。它的完整图像就是该层级的 PLUS 凯莱表。",
  "PLUS on three positions": "三个位置上的 PLUS",
  "PLUS preservation makes a homomorphism determined by the image of the generator.":
    "对 PLUS 的保持，使一个同态完全由生成元的像所决定。",
  "Pick a row, pick a column, read the cell where they cross. That is the whole reading procedure, and it is identical on both sides below.":
    "选一行，选一列，读它们相交处的那个格子。这就是全部的读法，下面左右两边完全一样。",
  "Placing P0 on the right leaves every position unchanged, and no other position does so.":
    "把 P0 放在右边，会让任何位置保持不变，而没有别的位置能做到这一点。",
  "Positions cannot be merged into a smaller well-defined quotient: any identification of two distinct positions collapses the entire level.":
    "位置不可能被合并成一个更小的、良定义的商结构：任何把两个不同位置等同起来的做法，都会让整个层级塌缩。",
  Proof: "证明",
  Proposition: "命题",
  "Propositions and proofs": "命题与证明",
  "Published evidence": "已发布的证据",
  "Read the plain-language briefing": "阅读大白话说明",
  "Read the stack from the bottom. Each layer only adds what the layer beneath it can already support, and no layer may be quoted as if it were a higher one.":
    "从下往上读这一摞。每一层只添加它下面那层已经能够支撑的东西，而任何一层都不得被当作更高的一层来引用。",
  "Reading downward": "自上而下地读",
  "Reading upward": "自下而上地读",
  Replayable: "可重放",
  "Residue addition is associative and commutative, the class of 0 is neutral, and each class has an additive inverse.":
    "同余加法既结合又交换，零的类是中性元，每个类都有加法逆元。",
  "Row 2, column 3, cell 6.": "第 2 行，第 3 列，格中是 6。",
  "Row P1, column P2, cell P0.": "第 P1 行，第 P2 列，格中是 P0。",
  "STAR admits no nontrivial congruence": "STAR 不容许任何非平凡的同余",
  "STAR agrees with PLUS on every row except the first, where a single guard on the left operand overrides the sum. This one clause is the source of every asymmetry proved below.":
    "除第一行外，STAR 与 PLUS 在每一行上都一致；在第一行，一个作用于左操作数的守卫条件盖过了求和。下面证明的一切不对称，都源自这一个条款。",
  "STAR has no two-sided identity": "STAR 没有双边单位元",
  "STAR is neither commutative nor associative": "STAR 既不可交换也不结合",
  "START WITH THE TABLE": "从表格开始",
  "Scope of this result:": "本结论的适用范围：",
  "See the table everything is built on": "看看这一切所依托的那张表",
  "Six stacked bars read from the bottom upward: the Cayley table, the typed coordinate, the bracketed program, the bounded selection, the execution receipt, and the published evidence. An arrow runs upward through all of them.":
    "六条自下而上阅读的堆叠横条：凯莱表、类型化坐标、带括号的程序、受限的候选选择、执行回执，以及已发布的证据。一支向上的箭头贯穿它们。",
  "Start with the table": "从表格开始",
  "Steps composed into a program": "把步骤组合成程序",
  "THE WHOLE PROJECT RESTS ON ONE OBJECT": "整个项目立在同一个对象之上",
  "That evaluation has not been run. Until it is, no claim about external gain appears anywhere on this site, and the numbers published here describe internal structure only.":
    "这样的评估尚未开展。在它开展之前，本站任何地方都不会出现关于外部收益的说法，此处公布的数字只描述内部结构。",
  "The PLUS reduct is the cyclic group of order n": "PLUS 约化结构是 n 阶循环群",
  "The automorphism group of the full algebra is the unit group": "整个代数的自同构群就是单位群",
  "The constant is preserved by construction, and both laws return P0 when both operands are P0.":
    "常量按构造被保持，而当两个操作数都是 P0 时，两条法则都返回 P0。",
  "The count is a complete finite enumeration, not an estimate: input pairs are counted first, then the two laws, then the two role placements.":
    "这个计数是一次完整的有限枚举，而不是估算：先数输入对，再数两条法则，最后数两种角色摆放。",
  "The current runtime activates the six levels above the degenerate one, leaving the four L1 coordinates as control-only.":
    "当前运行时激活退化层级之上的那六个层级，把 L1 的四个坐标留作仅供控制之用。",
  "The entries are names of positions rather than quantities, and the count wraps: after the last position it returns to the first.":
    "格中的条目是位置的名字，而不是数量，而且计数会绕回：走过最后一个位置就回到第一个。",
  "The equation forces the index of the candidate to vanish modulo n.": "这个等式迫使候选者的索引在模 n 意义下为零。",
  "The index map is a bijection and transports the operation onto residue addition, because the definition of PLUS is stated directly in terms of that addition.":
    "索引映射是双射，并把该运算搬运成同余加法，因为 PLUS 的定义本来就是用这种加法写出来的。",
  "The law PLUS": "法则 PLUS",
  "The law STAR": "法则 STAR",
  "The level fixes a finite set of named positions before any operation is defined. Nothing outside this list may appear as an input or as a result.":
    "在定义任何运算之前，层级就先固定了一组有名字的位置。清单之外的东西既不能作为输入出现，也不能作为结果出现。",
  "The map is injective exactly when that image still has full additive order n.":
    "该映射为单射，当且仅当那个像仍具有完整的加法阶 n。",
  "The one technical fact worth carrying away": "值得带走的那一个技术事实",
  "The reset row separates P0 so sharply that the identification propagates: at L3, identifying P0 with P1 forces P0 with P2 as well.":
    "重置行把 P0 分离得如此彻底，以至于等同关系会蔓延：在 L3 上，把 P0 与 P1 等同，就迫使 P0 也与 P2 等同。",
  "The result of one cell can be the input of the next. Because STAR is order-sensitive, the bracketing is part of the program and has to be written down rather than assumed.":
    "一个单元格的结果可以成为下一个的输入。由于 STAR 对顺序敏感，加括号的方式是程序的一部分，必须写下来，而不能默认。",
  "The same carrier is studied under one law, under the other law, and under both at once. The full expansion has signature (2,2,0): two binary operations and one named constant.":
    "同一个载体分别在一条法则下、在另一条法则下，以及在两条法则同时之下被研究。完整扩张的签名是 (2,2,0)：两个二元运算和一个有名字的常量。",
  "The second branch then returns P0, which differs from the assumed left zero, so no nonzero position qualifies.":
    "于是第二个分支返回 P0，与假设的那个左零元并不相同，因此没有任何非零位置合格。",
  "The structural orbit count is 224 by two independent routes": "结构性轨道数经由两条独立路径都得出 224",
  "The table GALO starts from": "GALO 由之出发的那张表",
  "The table you already know": "你已经认识的那张表",
  "The three structures": "三个结构",
  "The two one-sided properties cannot be combined: no position acts neutrally from both sides at once.":
    "这两条单侧性质无法合到一起：没有任何位置能同时从两边都表现为中性。",
  "The typed catalogue has exactly 560 coordinates": "类型化目录恰好含有 560 个坐标",
  "The unit group acts diagonally on ordered pairs, independently inside each level and each of the four family fibres.":
    "单位群对有序对施行对角作用——在每个层级内部、以及四个族纤维中的每一个内部，都是各自独立进行的。",
  "The whole table can be regenerated from the formula and compared entry by entry, so a disagreement points at a specific cell.":
    "整张表都可以由公式重新生成，并逐条比对，因此一处分歧会直接指向某一个具体的格子。",
  "The zero map always exists": "零映射总是存在",
  Theorem: "定理",
  "Therefore both sides of every preservation equation evaluate to P0 regardless of the inputs.":
    "因此，无论输入是什么，每一条保持性等式的两边都等于 P0。",
  "These are stated as open work with named preconditions, not implied as done. The evidence page lists each one and the milestone it has actually reached.":
    "它们被写明为带有具名前置条件的、尚未完成的工作，而不是被暗示为已经完成。证据页逐条列出了每一项及其实际到达的里程碑。",
  "This is the entire technical bet. A finite table is a weaker object than a learned model, and that weakness is exactly what makes each of the four properties below hold without exception.":
    "这就是全部的技术赌注。有限表格是一个比训练模型更弱的对象，而正是这种弱，让下面四条性质无一例外地成立。",
  "This section states the kernel the way a referee would expect to read it: numbered definitions first, then each structural claim with a complete proof. Every statement here is also re-derived by the automated checks that run on each build, so the prose and the machine agree by construction.":
    "本节以审稿人期待看到的方式陈述内核：先是编号的定义，然后是每一条结构性论断及其完整证明。此处的每一条陈述都会被每次构建时运行的自动检查重新推导一遍，因此文字与机器在构造上就是一致的。",
  "Two inputs go in, one result comes out, and every possible pair of inputs already has its own filled cell.":
    "两个输入进去，一个结果出来，而每一对可能的输入都已经有了属于自己的、被填好的格子。",
  "Two laws fill the same grid. PLUS moves around the ring. STAR does the same except that one input on the left resets the answer. Both tables are written out in full, not approximated.":
    "两条法则填满同一张网格。PLUS 沿着环移动。STAR 做同样的事，只不过左边的某一个输入会把答案重置。两张表都是完整写出的，而不是近似的。",
  "Two rules, filled in completely": "两条规则，完整填好",
  "Under PLUS the carrier is a cyclic group: the operation is associative and commutative, P0 is a two-sided identity, and every position has an inverse.":
    "在 PLUS 之下，载体是一个循环群：运算既结合又交换，P0 是双边单位元，每个位置都有逆元。",
  "Underneath every diagram, number, and record on this site there is a finite table of results for two inputs — a Cayley table. It is written out completely in advance, so it can be checked entry by entry rather than trusted.":
    "本站的每一张图、每一个数字、每一条记录之下，都躺着一张给两个输入用的有限结果表——凯莱表。它是事先完整写出的，因此可以被逐条核查，而不必被信任。",
  "WHY A FINITE TABLE AND NOT A MODEL": "为什么是有限表格，而不是模型",
  "What does not work yet?": "还有什么尚未奏效？",
  "What is actually being built?": "究竟在建造什么？",
  "What is different": "有什么不同",
  "What is the same": "有什么相同",
  "What these results do not establish:": "这些结论没有确立什么：",
  "What works today?": "今天什么在运行？",
  "What would change your mind?": "什么会改变你的判断？",
  "Where is the commercial value?": "商业价值在哪里？",
  "Why does a table matter?": "为什么偏偏是表格重要？",
  "YOU HAVE READ ONE OF THESE BEFORE": "这样的表你早就读过",
  "You already know one: the multiplication table. Choose a row, choose a column, read the cell. A Cayley table is the same idea applied to any rule that takes two inputs.":
    "你已经认识其中一张：乘法表。选一行，选一列，读那个格子。凯莱表就是把同样的想法用到任何一条双输入规则上。",
  "a declared filter chain over a finite universe": "作用在有限全集上的一串已声明的过滤器",
  "cells composed into an explicit tree": "把单元格组合成一棵显式的树",
  "counts and boundaries anyone can recompute": "任何人都能重新算一遍的计数与边界",
  "one filled cell per input pair": "每个输入对对应一个填好的格子",
  "same procedure": "同样的读法",
  "the cell plus the roles of its inputs": "格子，再加上它两个输入的角色",
  "they are theorems about a finite algebra. They do not by themselves establish semantics, learning, a trained world model, external operational gain, or general intelligence — each of those needs its own evidence and is listed separately with its current status.":
    "它们是关于一个有限代数的定理。它们本身并不确立语义、学习、训练好的世界模型、外部运行增益或通用智能——其中每一项都需要各自的证据，并且都被单独列出且注明当前状态。",
  "what ran, in what scope, with what status": "跑了什么、在什么范围内、以什么状态结束",
};

export const academicArExtra: TranslationDictionary = {
  "A Cayley table is the school multiplication table, written for a different rule.":
    "جدول كايلي هو جدول الضرب المدرسي نفسه، مكتوبًا لقاعدة أخرى.",
  "A bijection that preserves the operation transports every group axiom, so the reduct is a cyclic group of order n generated by P1.":
    "التقابل الذي يحافظ على العملية ينقل كل بديهيات الزمرة، فيكون هذا التخفيض زمرة دورية من الرتبة n مولَّدة بـ P1.",
  "A bounded, partner-owned problem where explicit state and exact replay can be measured against an ordinary baseline.":
    "مسألة محدودة النطاق ببيانات يملكها الشريك، حيث يمكن قياس الحالة الصريحة وإعادة التشغيل الدقيقة مقابل خط أساس اعتيادي.",
  "A cell holds one named position, never a probability or a score. Two runs on the same inputs cannot differ.":
    "تحمل الخلية موضعًا مُسمّى واحدًا، لا احتمالًا ولا درجة. ولا يمكن أن يختلف تشغيلان على المدخلات نفسها.",
  "A cell is recorded together with the roles of its two inputs, so two steps that end on the same result still keep different records. That address is what a receipt can point at.":
    "تُسجَّل الخلية مع دورَي مدخليها، فتظل خطوتان انتهتا إلى النتيجة نفسها محتفظتين بسجلين مختلفين. وهذا العنوان هو ما يمكن للإيصال أن يشير إليه.",
  "A coordinate records the level, the law, and which of the two semantic roles occupies which table axis. Two coordinates with equal targets remain distinct records whenever their roles differ.":
    "يسجّل الإحداثي المستوى والقانون وأيّ الدورين الدلاليين يشغل أيّ محور في الجدول. ويبقى إحداثيان لهما الهدف نفسه سجلين متمايزين ما دام دوراهما مختلفين.",
  "A cyclic group of order m contains an element of order n exactly when n divides m, which settles the forward direction.":
    "الزمرة الدورية من الرتبة m تحوي عنصرًا من الرتبة n إذا وفقط إذا كان n يقسم m، وبهذا يثبت الاتجاه الأول.",
  "A finer level can be carried into a coarser one without merging positions precisely when its size divides the target size.":
    "يمكن نقل مستوى أدقّ إلى مستوى أخشن دون دمج المواضع تحديدًا حين يقسم حجمه حجم المستوى الهدف.",
  "A finite set of allowed positions": "مجموعة منتهية من المواضع المسموح بها",
  "A finite table can be checked completely. A model cannot.": "الجدول المنتهي يمكن فحصه بالكامل. أما النموذج فلا.",
  "A level with n positions has n² ordered input pairs, and the levels are disjoint.":
    "المستوى الذي يضم n موضعًا يملك n² زوجًا مرتبًا من المدخلات، والمستويات منفصلة بعضها عن بعض.",
  "A mathematical embedding is a permission to move a distinction, not an authorisation to move data at runtime. Provenance, alignment, loss, and policy remain separate contracts.":
    "التضمين الرياضي إذن بنقل تمييز، لا تفويض بنقل بيانات وقت التشغيل. ويبقى المصدر والمواءمة والفقد والسياسة عقودًا منفصلة.",
  "A record that can be replayed": "سجل قابل لإعادة التشغيل",
  "A running engine over a fully enumerated finite universe, producing a machine-readable record for every run.":
    "محرّك يعمل فوق كون منتهٍ مُعدَّد بالكامل، وينتج سجلًا مقروءًا آليًا عن كل تشغيل.",
  "A table of results for two inputs": "جدول نتائج لمدخلين",
  "A unit is invertible modulo n, so multiplication by it permutes the positions and fixes P0.":
    "العنصر الوحدوي قابل للعكس بالمقياس n، فالضرب به يبدّل المواضع ويُبقي P0 في مكانه.",
  "A way for a decision-making system to hold its state in a small, named, completely written-out table instead of inside an opaque model.":
    "طريقة تجعل نظام اتخاذ القرار يحفظ حالته في جدول صغير مُسمّى مكتوب بالكامل، بدل أن يحفظها داخل نموذج غير شفاف.",
  "ACADEMIC REFERENCE": "المرجع الأكاديمي",
  "Academic reference": "المرجع الأكاديمي",
  "Adding the fibres gives the tower total; the separate sum of local group orders is a different quantity and is not one global group.":
    "جمع الألياف يعطي مجموع البرج كله؛ أما مجموع رتب الزمر المحلية فهو كمية أخرى وليس زمرة عامة واحدة.",
  "An address for every cell": "عنوان لكل خلية",
  "Any published figure can be followed back down to the exact table cells it came from.":
    "يمكن تتبّع أي رقم منشور نزولًا حتى خلايا الجدول التي جاء منها بالضبط.",
  "Assume a congruence identifies two distinct positions and use compatibility with STAR on both sides.":
    "افترض أن تطابقًا يوحّد موضعين متمايزين، ثم استعمل التوافق مع STAR من الجهتين.",
  "At the one-element level the two properties collapse into the same equation. That degenerate case is stated separately and is never used to support a claim about n ≥ 2.":
    "عند المستوى ذي العنصر الواحد تنهار الخاصيتان إلى المعادلة نفسها. وتُذكر هذه الحالة المنحلّة على حدة ولا تُستخدم أبدًا لدعم ادعاء عن n ≥ 2.",
  "At the two-element level the same bracketing pair still separates, so the failure holds at every nondegenerate level.":
    "وعند المستوى ذي العنصرين يظل زوج التقويس نفسه مفترقًا، فيثبت الإخفاق عند كل مستوى غير منحلّ.",
  "Averaging fixed points over the group gives the per-level orbit counts, which agree cell for cell with a direct traversal.":
    "أخذ متوسط النقاط الثابتة على الزمرة يعطي عدد المدارات في كل مستوى، وهو يطابق المسح المباشر خلية بخلية.",
  "Because the table is finite and written down in advance, every step the system takes has an address, a result, and a record. There is no hidden remainder that only the model knows about.":
    "لأن الجدول منتهٍ ومكتوب مسبقًا، فإن لكل خطوة يخطوها النظام عنوانًا ونتيجة وسجلًا. ولا يبقى فائض خفي لا يعرفه إلا النموذج.",
  "Because the table is fixed and the order of steps is recorded, the same run can be reproduced later on a different machine.":
    "لأن الجدول ثابت وترتيب الخطوات مسجَّل، يمكن إعادة إنتاج التشغيل نفسه لاحقًا على آلة أخرى.",
  "Before any talk of architecture, agents, or evidence, there is a table of results for two inputs — the same object you met at school as the multiplication table. If you follow only this section, you will still know what GALO is made of.":
    "قبل أي حديث عن البنية أو الوكلاء أو الأدلة، ثمة جدول نتائج لمدخلين — وهو الشيء نفسه الذي عرفته في المدرسة باسم جدول الضرب. وإن قرأت هذا القسم وحده فستعرف مع ذلك مما يتكوّن GALO.",
  "Between any ordered pair of levels there is at least one structure-preserving map, so the phrase there is no map is never correct.":
    "بين أي زوج مرتب من المستويات يوجد تطبيق واحد على الأقل يحافظ على البنية، فلا تصح أبدًا عبارة «لا يوجد تطبيق».",
  "Both branches of the definition return the left operand when the right operand is P0.":
    "يعيد فرعا التعريف كلاهما المعامل الأيسر حين يكون المعامل الأيمن هو P0.",
  "Both failures are witnessed by explicit small counterexamples, so neither property can be assumed anywhere in the theory.":
    "يشهد على الإخفاقين أمثلة مضادة صغيرة صريحة، فلا يجوز افتراض أيٍّ من الخاصيتين في أي موضع من النظرية.",
  "Bounded selection": "اختيار مقيَّد",
  "Bracketed program": "برنامج مقوَّس",
  "But P0 is a left zero, so from the left it destroys the other operand instead of preserving it.":
    "لكن P0 صفر أيسر، فهو من اليسار يمحو المعامل الآخر بدل أن يحفظه.",
  "By the previous proposition the only candidate for a right-neutral element is P0.":
    "بحسب القضية السابقة، المرشح الوحيد للعنصر المحايد من اليمين هو P0.",
  "Carrier of a level": "حامل المستوى",
  Checkable: "قابل للفحص",
  "Checking a table is not sampling or testing: every entry is inspected, and the check either passes on all of them or fails on a named one. That is what makes a claim about this layer arguable by someone who does not trust us.":
    "فحص الجدول ليس معاينة عيّنة ولا اختبارًا: فكل مدخلة تُفحص، وإما أن ينجح الفحص عليها جميعًا أو يفشل عند مدخلة مُسمّاة. ولهذا يستطيع من لا يثق بنا أن يجادل في أي ادعاء عن هذه الطبقة.",
  "Commutativity fails on the pair that puts P0 first on one side and second on the other.":
    "تخفق الإبدالية عند الزوج الذي يضع P0 أولًا في جهة وثانيًا في الأخرى.",
  Complete: "كامل",
  "Conversely PLUS preservation makes any automorphism determined by the image of the generator, and injectivity forces that image to be a unit.":
    "وبالعكس، فإن الحفاظ على PLUS يجعل أي تشاكل ذاتي محددًا بصورة المولّد، ويفرض التباين أن تكون تلك الصورة عنصرًا وحدويًا.",
  "Conversely the scaled maps preserve STAR as well, because their index is zero only when the source index is zero.":
    "وبالعكس تحافظ التطبيقات المُحجَّمة على STAR أيضًا، لأن دليلها لا يكون صفرًا إلا حين يكون دليل المصدر صفرًا.",
  Corollary: "نتيجة",
  Definition: "تعريف",
  Definitions: "التعريفات",
  "Definitions, propositions, and proofs in ordinary mathematical form.":
    "تعريفات وقضايا وبراهين بالصيغة الرياضية المعتادة.",
  "Direct enumeration of orbits and the Burnside averaging formula reconstruct the same total, so the figure is checked twice rather than asserted once.":
    "التعداد المباشر للمدارات وصيغة متوسط برنسايد يعيدان بناء المجموع نفسه، فيكون الرقم مفحوصًا مرتين لا مُدّعى مرة واحدة.",
  "Each bounded run writes what it checked, what it executed, and where it stopped. Anyone with the record can run the same steps again and compare cell by cell.":
    "يكتب كل تشغيل مقيَّد ما فحصه وما نفّذه وأين توقف. ومن بيده هذا السجل يستطيع إعادة الخطوات نفسها ومقارنتها خلية بخلية.",
  "Each law cell is recorded once with the source on the row and once with the source on the column, which doubles it again.":
    "تُسجَّل كل خلية قانون مرة والمصدر في الصف ومرة والمصدر في العمود، فيتضاعف العدد ثانية.",
  "Each layer is built only from what the layer below has already established.":
    "كل طبقة مبنية فقط مما أرسته الطبقة التي تحتها.",
  "Each pair is evaluated once under PLUS and once under STAR, which doubles the count.":
    "يُحسب كل زوج مرة تحت PLUS ومرة تحت STAR، فيتضاعف العدد.",
  "Each position is identified with one residue class modulo n. The map is a bijection, which is what lets exact arithmetic be carried out on labels without treating a label as a quantity.":
    "يُطابَق كل موضع مع فئة بواقٍ واحدة بالمقياس n. والتطبيق تقابل، وهو ما يتيح إجراء حساب دقيق على التسميات دون معاملة التسمية بوصفها كمية.",
  "End of proof": "نهاية البرهان",
  "Every allowed pair of inputs has a row, a column, and one filled cell. There is no case the table forgot to cover.":
    "لكل زوج مدخلات مسموح به صف وعمود وخلية واحدة مملوءة. ولا توجد حالة نسي الجدول تغطيتها.",
  "Every number published on this site traces back to a finite table.":
    "كل رقم منشور في هذا الموقع يعود إلى جدول منتهٍ.",
  "Every reversible relabelling that preserves both laws and the named constant is multiplication of indices by a unit, and every unit gives such a relabelling.":
    "كل إعادة تسمية عكوسة تحافظ على القانونين وعلى الثابت المُسمّى هي ضرب الأدلة في عنصر وحدوي، وكل عنصر وحدوي يعطي إعادة تسمية كهذه.",
  "Everything on this site is built on one finite table.": "كل ما في هذا الموقع مبني على جدول منتهٍ واحد.",
  Exact: "دقيق",
  "Existence is the first branch of the definition, applied for every right operand.":
    "الوجود هو الفرع الأول من التعريف، مطبَّقًا على كل معامل أيمن.",
  "For associativity, evaluate the same three operands under both bracketings at a level with three or more positions.":
    "أما التجميعية فاحسب المعاملات الثلاثة نفسها بالتقويسين معًا عند مستوى فيه ثلاثة مواضع أو أكثر.",
  "For every level with at least two positions, placing P0 on the left forces the result to P0, and no other position has that property.":
    "في كل مستوى فيه موضعان على الأقل، يفرض وضع P0 على اليسار أن تكون النتيجة P0، ولا يملك أي موضع آخر هذه الخاصية.",
  "For uniqueness, suppose a nonzero position were a left zero and choose the right operand that completes it to a full turn.":
    "ولإثبات الوحدانية، افترض أن موضعًا غير صفري صفرٌ أيسر، واختر المعامل الأيمن الذي يكمله دورةً كاملة.",
  "For uniqueness, test a candidate against the nonzero position P1, which is evaluated by the second branch.":
    "ولإثبات الوحدانية، اختبر المرشح على الموضع غير الصفري P1 الذي يُحسب بالفرع الثاني.",
  "Four properties a table has and a trained model does not.": "أربع خصائص يملكها الجدول ولا يملكها نموذج مدرَّب.",
  "GALO first declares how many positions exist. Three positions give a three-by-three table; seven give a seven-by-seven one. Nothing outside the declared list can ever appear.":
    "يعلن GALO أولًا عدد المواضع الموجودة. فثلاثة مواضع تعطي جدولًا ثلاثة في ثلاثة، وسبعة تعطي سبعة في سبعة. ولا يمكن أن يظهر شيء خارج القائمة المعلَنة.",
  "GALO is built so the trace is the product: what state the system was in, which rule fired, what it was allowed to do, and what it recorded. That is the artefact a reviewer, an auditor, or a counterparty can actually examine.":
    "بُني GALO بحيث يكون الأثر نفسه هو المنتج: في أي حالة كان النظام، وأي قاعدة عملت، وبماذا كان مسموحًا له، وماذا سجّل. وهذا هو الأثر الذي يستطيع مراجع أو مدقق أو طرف مقابل أن يفحصه فعلًا.",
  "IN PLAIN LANGUAGE": "بلغة بسيطة",
  "If you read one section on this site, read this one.": "إن قرأت قسمًا واحدًا في هذا الموقع، فليكن هذا القسم.",
  "In long-running and regulated work, the expensive failure is not a wrong answer — it is a wrong answer nobody can trace.":
    "في الأعمال الطويلة والخاضعة للتنظيم، ليس الجواب الخاطئ هو ما يكلّف غاليًا، بل الجواب الخاطئ الذي لا يستطيع أحد تتبّعه.",
  "Index map": "تطبيق الأدلة",
  "It also preserves the STAR guard, because multiplying by a unit sends a nonzero index to a nonzero index.":
    "وهو يحافظ أيضًا على شرط الحراسة في STAR، لأن الضرب في عنصر وحدوي يرسل الدليل غير الصفري إلى دليل غير صفري.",
  "It is narrow on purpose: two fixed input patterns, one step per run, no learning. Everything inside that boundary is checked on every build; nothing outside it is claimed.":
    "وهو ضيّق عن قصد: نمطا إدخال ثابتان، وخطوة واحدة لكل تشغيل، وبلا تعلّم. وكل ما داخل هذا الحد يُفحص مع كل بناء، ولا يُدَّعى شيء خارجه.",
  "Iterating the argument reaches every position, so the relation is the universal one.":
    "وتكرار الحجة يبلغ كل موضع، فتصير العلاقة هي العلاقة الشاملة.",
  "Layer stack from the Cayley table to published evidence": "كومة الطبقات من جدول كايلي إلى الأدلة المنشورة",
  "Learning, a trained world model, and any measured result outside our own accounting.":
    "التعلّم، ونموذج عالم مدرَّب، وأي نتيجة مقيسة خارج حساباتنا الداخلية.",
  "Multiplication distributes over residue addition, which gives preservation of PLUS.":
    "الضرب توزيعي على جمع البواقي، وهذا يعطي الحفاظ على PLUS.",
  "Multiplication, three by three": "الضرب، ثلاثة في ثلاثة",
  "No mathematics, no acronyms. Six questions a non-technical reader asks first, answered in the order they are usually asked.":
    "بلا رياضيات وبلا اختصارات. ستة أسئلة يطرحها القارئ غير التقني أولًا، بالترتيب الذي تُطرح به عادة.",
  "Nonzero embeddings exist exactly when the levels divide":
    "التضمينات غير الصفرية توجد تحديدًا حين يقسم أحد المستويين الآخر",
  "Notation is fixed once and used throughout. Positions are written P with a subscript, the level is written L with a subscript, and every formula is displayed left to right in every language of this site.":
    "تُثبَّت الرموز مرة واحدة وتُستعمل في كل ما يلي. فالمواضع تُكتب P مع دليل سفلي، والمستوى يُكتب L مع دليل سفلي، وكل صيغة تُعرض من اليسار إلى اليمين في جميع لغات هذا الموقع.",
  "P0 is the unique left zero of STAR": "P0 هو الصفر الأيسر الوحيد لـ STAR",
  "P0 is the unique right-neutral element of STAR": "P0 هو العنصر المحايد الوحيد من اليمين لـ STAR",
  "PLUS is total and closed: it is defined on every ordered pair and its value always lies in the same carrier. Its complete graph is the PLUS Cayley table of that level.":
    "PLUS كليّ ومنغلق: فهو معرَّف على كل زوج مرتب، وقيمته تقع دائمًا في الحامل نفسه. ورسمه الكامل هو جدول كايلي لـ PLUS في ذلك المستوى.",
  "PLUS on three positions": "PLUS على ثلاثة مواضع",
  "PLUS preservation makes a homomorphism determined by the image of the generator.":
    "الحفاظ على PLUS يجعل التشاكل محددًا بصورة المولّد.",
  "Pick a row, pick a column, read the cell where they cross. That is the whole reading procedure, and it is identical on both sides below.":
    "اختر صفًا واختر عمودًا واقرأ الخلية عند تقاطعهما. هذا هو إجراء القراءة كله، وهو نفسه على الجانبين أدناه.",
  "Placing P0 on the right leaves every position unchanged, and no other position does so.":
    "وضع P0 على اليمين يترك كل موضع دون تغيير، ولا يفعل ذلك أي موضع آخر.",
  "Positions cannot be merged into a smaller well-defined quotient: any identification of two distinct positions collapses the entire level.":
    "لا يمكن دمج المواضع في خارج قسمة أصغر معرَّف تعريفًا سليمًا: فأي توحيد بين موضعين متمايزين يُسقط المستوى كله.",
  Proof: "البرهان",
  Proposition: "قضية",
  "Propositions and proofs": "القضايا والبراهين",
  "Published evidence": "الأدلة المنشورة",
  "Read the plain-language briefing": "اقرأ الشرح بلغة بسيطة",
  "Read the stack from the bottom. Each layer only adds what the layer beneath it can already support, and no layer may be quoted as if it were a higher one.":
    "اقرأ الكومة من الأسفل. فكل طبقة لا تضيف إلا ما تستطيع الطبقة التي تحتها أن تحمله، ولا يجوز اقتباس طبقة كأنها طبقة أعلى.",
  "Reading downward": "القراءة نزولًا",
  "Reading upward": "القراءة صعودًا",
  Replayable: "قابل لإعادة التشغيل",
  "Residue addition is associative and commutative, the class of 0 is neutral, and each class has an additive inverse.":
    "جمع البواقي تجميعي وإبدالي، وفئة الصفر محايدة، ولكل فئة نظير جمعي.",
  "Row 2, column 3, cell 6.": "الصف 2، العمود 3، الخلية 6.",
  "Row P1, column P2, cell P0.": "الصف P1، العمود P2، الخلية P0.",
  "STAR admits no nontrivial congruence": "لا يقبل STAR أي تطابق غير بديهي",
  "STAR agrees with PLUS on every row except the first, where a single guard on the left operand overrides the sum. This one clause is the source of every asymmetry proved below.":
    "يتفق STAR مع PLUS في كل صف إلا الأول، حيث يتجاوز شرطُ حراسة واحد على المعامل الأيسر عمليةَ الجمع. ومن هذا الشرط وحده تنبع كل اللاتماثلات المبرهنة أدناه.",
  "STAR has no two-sided identity": "لا يملك STAR عنصرًا محايدًا من الجهتين",
  "STAR is neither commutative nor associative": "STAR ليس إبداليًا ولا تجميعيًا",
  "START WITH THE TABLE": "ابدأ من الجدول",
  "Scope of this result:": "نطاق هذه النتيجة:",
  "See the table everything is built on": "انظر الجدول الذي بُني عليه كل شيء",
  "Six stacked bars read from the bottom upward: the Cayley table, the typed coordinate, the bracketed program, the bounded selection, the execution receipt, and the published evidence. An arrow runs upward through all of them.":
    "ستة أشرطة متراصّة تُقرأ من الأسفل إلى الأعلى: جدول كايلي، والإحداثي محدد النوع، والبرنامج المقوَّس، والاختيار المقيَّد، وإيصال التنفيذ، والأدلة المنشورة. ويمر سهم صاعد عبرها جميعًا.",
  "Start with the table": "ابدأ من الجدول",
  "Steps composed into a program": "خطوات مركَّبة في برنامج",
  "THE WHOLE PROJECT RESTS ON ONE OBJECT": "المشروع كله يقوم على كائن واحد",
  "That evaluation has not been run. Until it is, no claim about external gain appears anywhere on this site, and the numbers published here describe internal structure only.":
    "لم يُجرَ هذا التقييم بعد. وإلى أن يُجرى، لا يظهر في أي موضع من الموقع ادعاء عن مكسب خارجي، والأرقام المنشورة هنا تصف البنية الداخلية وحدها.",
  "The PLUS reduct is the cyclic group of order n": "تخفيض PLUS هو الزمرة الدورية من الرتبة n",
  "The automorphism group of the full algebra is the unit group":
    "زمرة التشاكلات الذاتية للجبر الكامل هي زمرة العناصر الوحدوية",
  "The constant is preserved by construction, and both laws return P0 when both operands are P0.":
    "الثابت محفوظ بحكم البناء، ويعيد القانونان كلاهما P0 حين يكون المعاملان P0.",
  "The count is a complete finite enumeration, not an estimate: input pairs are counted first, then the two laws, then the two role placements.":
    "العدّ تعداد منتهٍ كامل لا تقدير: تُعدّ أزواج المدخلات أولًا، ثم القانونان، ثم ترتيبا الدور.",
  "The current runtime activates the six levels above the degenerate one, leaving the four L1 coordinates as control-only.":
    "تُفعِّل بيئة التشغيل الحالية المستويات الستة فوق المستوى المنحلّ، وتترك إحداثيات L1 الأربعة للتحكم فقط.",
  "The entries are names of positions rather than quantities, and the count wraps: after the last position it returns to the first.":
    "المدخلات أسماء مواضع لا كميات، والعدّ يلتف: فبعد الموضع الأخير يعود إلى الأول.",
  "The equation forces the index of the candidate to vanish modulo n.":
    "تفرض المعادلة أن ينعدم دليل المرشح بالمقياس n.",
  "The index map is a bijection and transports the operation onto residue addition, because the definition of PLUS is stated directly in terms of that addition.":
    "تطبيق الأدلة تقابل، وهو ينقل العملية إلى جمع البواقي، لأن تعريف PLUS مصوغ مباشرة بهذا الجمع.",
  "The law PLUS": "القانون PLUS",
  "The law STAR": "القانون STAR",
  "The level fixes a finite set of named positions before any operation is defined. Nothing outside this list may appear as an input or as a result.":
    "يثبّت المستوى مجموعة منتهية من المواضع المُسمّاة قبل تعريف أي عملية. ولا يجوز أن يظهر شيء خارج هذه القائمة مدخلًا ولا نتيجة.",
  "The map is injective exactly when that image still has full additive order n.":
    "يكون التطبيق متباينًا تحديدًا حين تحتفظ تلك الصورة بالرتبة الجمعية الكاملة n.",
  "The one technical fact worth carrying away": "الحقيقة التقنية الوحيدة الجديرة بأن تحملها معك",
  "The reset row separates P0 so sharply that the identification propagates: at L3, identifying P0 with P1 forces P0 with P2 as well.":
    "يفصل صف إعادة الضبط P0 فصلًا حادًا إلى حد أن التوحيد ينتشر: فعند L3، توحيد P0 مع P1 يفرض توحيد P0 مع P2 أيضًا.",
  "The result of one cell can be the input of the next. Because STAR is order-sensitive, the bracketing is part of the program and has to be written down rather than assumed.":
    "يمكن أن تصير نتيجة خلية مدخلًا للخلية التالية. ولأن STAR حساس للترتيب، فالتقويس جزء من البرنامج يجب كتابته لا افتراضه.",
  "The same carrier is studied under one law, under the other law, and under both at once. The full expansion has signature (2,2,0): two binary operations and one named constant.":
    "يُدرَس الحامل نفسه تحت قانون واحد، ثم تحت الآخر، ثم تحتهما معًا. وللتوسيع الكامل التوقيع (2,2,0): عمليتان ثنائيتان وثابت مُسمّى واحد.",
  "The second branch then returns P0, which differs from the assumed left zero, so no nonzero position qualifies.":
    "عندئذٍ يعيد الفرع الثاني P0، وهو يخالف الصفر الأيسر المفترض، فلا يصلح أي موضع غير صفري.",
  "The structural orbit count is 224 by two independent routes": "عدد المدارات البنيوية يساوي 224 عبر طريقين مستقلين",
  "The table GALO starts from": "الجدول الذي يبدأ منه GALO",
  "The table you already know": "الجدول الذي تعرفه أصلًا",
  "The three structures": "البنى الثلاث",
  "The two one-sided properties cannot be combined: no position acts neutrally from both sides at once.":
    "لا يمكن الجمع بين الخاصيتين أحاديتي الجهة: فلا يوجد موضع يتصرف تصرفًا محايدًا من الجهتين معًا.",
  "The typed catalogue has exactly 560 coordinates": "الفهرس محدد النوع يضم 560 إحداثيًا بالضبط",
  "The unit group acts diagonally on ordered pairs, independently inside each level and each of the four family fibres.":
    "تعمل زمرة العناصر الوحدوية قطريًا على الأزواج المرتبة، وذلك باستقلال داخل كل مستوى وداخل كل ليفة من ليفات العائلات الأربع.",
  "The whole table can be regenerated from the formula and compared entry by entry, so a disagreement points at a specific cell.":
    "يمكن إعادة توليد الجدول كله من الصيغة ومقارنته مدخلة بمدخلة، فيشير أي اختلاف إلى خلية بعينها.",
  "The zero map always exists": "التطبيق الصفري موجود دائمًا",
  Theorem: "مبرهنة",
  "Therefore both sides of every preservation equation evaluate to P0 regardless of the inputs.":
    "لذا يساوي طرفا كل معادلة حفظ P0 مهما كانت المدخلات.",
  "These are stated as open work with named preconditions, not implied as done. The evidence page lists each one and the milestone it has actually reached.":
    "وهي مذكورة بوصفها عملًا مفتوحًا بشروط مسبقة مُسمّاة، لا بوصفها منجزة. وتسرد صفحة الأدلة كلًا منها والمعلم الذي بلغه فعلًا.",
  "This is the entire technical bet. A finite table is a weaker object than a learned model, and that weakness is exactly what makes each of the four properties below hold without exception.":
    "هذا هو الرهان التقني كله. فالجدول المنتهي كائن أضعف من نموذج مدرَّب، وهذا الضعف بالذات هو ما يجعل كلًا من الخصائص الأربع أدناه يتحقق بلا استثناء.",
  "This section states the kernel the way a referee would expect to read it: numbered definitions first, then each structural claim with a complete proof. Every statement here is also re-derived by the automated checks that run on each build, so the prose and the machine agree by construction.":
    "يعرض هذا القسم النواة بالطريقة التي يتوقع محكِّم أن يقرأها: تعريفات مرقّمة أولًا، ثم كل ادعاء بنيوي ببرهان كامل. وكل عبارة هنا يعاد اشتقاقها بالفحوص الآلية التي تعمل مع كل بناء، فيتفق النص والآلة بحكم البناء.",
  "Two inputs go in, one result comes out, and every possible pair of inputs already has its own filled cell.":
    "يدخل مدخلان وتخرج نتيجة واحدة، ولكل زوج ممكن من المدخلات خليته المملوءة مسبقًا.",
  "Two laws fill the same grid. PLUS moves around the ring. STAR does the same except that one input on the left resets the answer. Both tables are written out in full, not approximated.":
    "يملأ قانونان الشبكة نفسها. PLUS يتحرك حول الحلقة، وSTAR يفعل الشيء ذاته إلا أن مدخلًا واحدًا على اليسار يُعيد ضبط الجواب. والجدولان مكتوبان بالكامل لا مقرَّبَين.",
  "Two rules, filled in completely": "قاعدتان مملوءتان بالكامل",
  "Under PLUS the carrier is a cyclic group: the operation is associative and commutative, P0 is a two-sided identity, and every position has an inverse.":
    "تحت PLUS يكون الحامل زمرة دورية: العملية تجميعية وإبدالية، وP0 عنصر محايد من الجهتين، ولكل موضع نظير.",
  "Underneath every diagram, number, and record on this site there is a finite table of results for two inputs — a Cayley table. It is written out completely in advance, so it can be checked entry by entry rather than trusted.":
    "تحت كل رسم ورقم وسجل في هذا الموقع يقبع جدول نتائج منتهٍ لمدخلين — جدول كايلي. وهو مكتوب بالكامل ومسبقًا، فيمكن فحصه مدخلة بمدخلة بدل الوثوق به.",
  "WHY A FINITE TABLE AND NOT A MODEL": "لماذا جدول منتهٍ لا نموذج",
  "What does not work yet?": "ما الذي لا يعمل بعد؟",
  "What is actually being built?": "ما الذي يُبنى فعلًا؟",
  "What is different": "ما المختلف",
  "What is the same": "ما المتطابق",
  "What these results do not establish:": "ما لا تُثبته هذه النتائج:",
  "What works today?": "ما الذي يعمل اليوم؟",
  "What would change your mind?": "ما الذي قد يغيّر رأيك؟",
  "Where is the commercial value?": "أين القيمة التجارية؟",
  "Why does a table matter?": "لماذا يهمّ الجدول تحديدًا؟",
  "YOU HAVE READ ONE OF THESE BEFORE": "لقد قرأت واحدًا من هذه من قبل",
  "You already know one: the multiplication table. Choose a row, choose a column, read the cell. A Cayley table is the same idea applied to any rule that takes two inputs.":
    "أنت تعرف واحدًا منها أصلًا: جدول الضرب. اختر صفًا واختر عمودًا واقرأ الخلية. وجدول كايلي هو الفكرة نفسها مطبَّقة على أي قاعدة ذات مدخلين.",
  "a declared filter chain over a finite universe": "سلسلة مرشِّحات معلَنة فوق كون منتهٍ",
  "cells composed into an explicit tree": "خلايا مركَّبة في شجرة صريحة",
  "counts and boundaries anyone can recompute": "أعداد وحدود يستطيع أي شخص إعادة حسابها",
  "one filled cell per input pair": "خلية مملوءة واحدة لكل زوج مدخلات",
  "same procedure": "الإجراء نفسه",
  "the cell plus the roles of its inputs": "الخلية مع دورَي مدخليها",
  "they are theorems about a finite algebra. They do not by themselves establish semantics, learning, a trained world model, external operational gain, or general intelligence — each of those needs its own evidence and is listed separately with its current status.":
    "هي مبرهنات عن جبر منتهٍ. وهي بذاتها لا تُثبت دلالة ولا تعلّمًا ولا نموذج عالم مدرَّبًا ولا مكسبًا تشغيليًا خارجيًا ولا ذكاءً عامًا — فكل واحد من هذه يحتاج أدلته الخاصة، وكلٌّ منها مذكور على حدة مع حالته الراهنة.",
  "what ran, in what scope, with what status": "ما الذي جرى، وفي أي نطاق، وبأي حالة",
};
