import type { TranslationDictionary } from "../translations";

export const routeItemsRu: TranslationDictionary = {
  "It is not, and the gap is published rather than glossed. What a public run exercises is one bounded step: a closed set of possible answers, a ranking over it, the three conditions an answer has to meet, and a typed route that has to pass. The phases around that step — taking a probe, waiting for an outside disclosure, revising a persistent Atlas — are not in the measured path, so the architecture's joint contribution is unestablished rather than demonstrated. An end-to-end run that would settle it is the next registered step.":
    "Нет, и этот разрыв публикуется, а не заглаживается. Публичный прогон задействует один ограниченный шаг: замкнутое множество возможных ответов, ранжирование по нему, три условия, которым обязан удовлетворять ответ, и типизированный маршрут, который обязан пройти. Фазы вокруг этого шага — взять зонд, дождаться внешнего раскрытия, пересмотреть постоянный Атлас — в измеряемый путь не входят, поэтому совместный вклад архитектуры не установлен, а не продемонстрирован. Сквозной прогон, который это решит, — следующий зарегистрированный шаг.",
  "One evaluated row with concrete values": "Одна оценённая строка с конкретными значениями",
  "One held-out row carried through one bounded step":
    "Одна отложенная строка, проведённая через один ограниченный шаг",
  "One row is evaluated in one bounded step, and every value in it can be recomputed.":
    "Одна строка оценивается за один ограниченный шаг, и каждое значение в нём можно пересчитать.",
  "Reaching a decision here is not a hidden chain of reasoning. It is a closed set of phases with two lawful ways out, a budget counted in units as it is spent, and a learning phase that opens only after somebody outside the system discloses what actually happened. This page walks the whole of it, then shows one evaluated row of a public run inside it — and ends with the part of the route the published results did not measure.":
    "Прийти к решению здесь — не скрытая цепочка рассуждений. Это замкнутый набор фаз с двумя законными выходами, бюджет, который считается в единицах по мере расходования, и фаза обучения, открывающаяся только после того, как кто-то вне системы раскроет, что произошло на самом деле. Эта страница проходит весь набор целиком, затем показывает внутри него одну оценённую строку публичного прогона — и заканчивается той частью маршрута, которую опубликованные результаты не измеряли.",
  "Separable is the operative word. The volume is learned from the training data, then frozen and digested before the split that tests it is opened. Nothing in it is a weight, and nothing in it can widen what is permitted: removing it changes how quickly an answer is found, never which answers are lawful.":
    "Ключевое слово — отделимость. Том выучивается по обучающим данным, затем замораживается и сворачивается в дайджест до того, как открывается выборка, которая его проверяет. Ничто в нём не является весом, и ничто в нём не может расширить дозволенное: если его убрать, изменится то, насколько быстро находится ответ, но не то, какие ответы законны.",
  "The interesting question about any decision-making system is what it carries forward, because that is what a later behaviour depends on. Two of the three carried registers hold something that was learned, and the second is kept apart from the engine on purpose: what the system learned can be inspected, replaced or removed without touching what it is allowed to conclude.":
    "Интересный вопрос о любой системе принятия решений — что она проносит дальше, потому что именно от этого зависит её последующее поведение. Два из трёх проносимых регистров держат нечто выученное, и второй намеренно держится в стороне от движка: то, что система выучила, можно осмотреть, заменить или убрать, не трогая того, какие выводы ей дозволены.",
  "There are no weights, and there is learning. What is learned is where to look and in what order, held in a volume kept apart from the engine; what may never be learned is the verdict. The public runs measure that learned state on data it was never fitted to, and the coverage that belongs beside each accuracy is published with it on the evidence page.":
    "Весов нет, а обучение есть. Выучивается то, куда смотреть и в каком порядке; это держится в томе, отделённом от движка. Чему нельзя научиться никогда — это вердикту. Публичные прогоны измеряют именно это выученное состояние на данных, под которые оно не подгонялось, и покрытие, которое обязано стоять рядом с каждой точностью, публикуется вместе с ней на странице свидетельств.",
  "This is not the route above; it is one evaluated row of a public run, which takes one bounded step and writes one receipt. It is here because it is the part of the system with the hardest numbers attached: the set of possible answers is closed before the split that tests it is opened, every cut is a rule anybody can read, and the ordering can be recomputed from the record alone.":
    "Это не маршрут выше; это одна оценённая строка публичного прогона, которая делает один ограниченный шаг и пишет один протокол. Она здесь потому, что это часть системы с самыми твёрдыми числами: множество возможных ответов замыкается до того, как открывается проверяющая его выборка, каждое отсечение — правило, которое всякий может прочесть, а порядок пересчитывается из одной только записи.",
};

export const routeItemsZh: TranslationDictionary = {
  "It is not, and the gap is published rather than glossed. What a public run exercises is one bounded step: a closed set of possible answers, a ranking over it, the three conditions an answer has to meet, and a typed route that has to pass. The phases around that step — taking a probe, waiting for an outside disclosure, revising a persistent Atlas — are not in the measured path, so the architecture's joint contribution is unestablished rather than demonstrated. An end-to-end run that would settle it is the next registered step.":
    "不是，而且这个落差是公布出来的，不是被抹平的。一次公开运行所动用的是一个有界的步骤：一个封闭的可能答案集合、在它之上的一次排序、答案必须满足的三个条件，以及一条必须通过的类型化路线。围绕这一步的那些阶段——取一次探测、等待外部揭示、修订常驻的图册——都不在被测量的路径里，所以这套架构的联合贡献是未被确立的，而不是已被演示的。能了结此事的端到端运行，是下一个已登记的步骤。",
  "One evaluated row with concrete values": "一条被评测的行，附具体数值",
  "One held-out row carried through one bounded step": "一条留出的行，走完一个有界的步骤",
  "One row is evaluated in one bounded step, and every value in it can be recomputed.":
    "一条行在一个有界的步骤里被评测完，而其中每一个数值都可以重算出来。",
  "Reaching a decision here is not a hidden chain of reasoning. It is a closed set of phases with two lawful ways out, a budget counted in units as it is spent, and a learning phase that opens only after somebody outside the system discloses what actually happened. This page walks the whole of it, then shows one evaluated row of a public run inside it — and ends with the part of the route the published results did not measure.":
    "在这里作出决定，不是一条藏起来的推理链。它是一组封闭的阶段，带两个合法的出口，一份边花边记、以单位计数的预算，以及一个只有在系统之外的某个人揭示了真实发生了什么之后才打开的学习阶段。本页把整条路走一遍，然后在其中展示一次公开运行里被评测的某一行——最后落在这条路上那些公开结果并没有测量到的部分。",
  "Separable is the operative word. The volume is learned from the training data, then frozen and digested before the split that tests it is opened. Nothing in it is a weight, and nothing in it can widen what is permitted: removing it changes how quickly an answer is found, never which answers are lawful.":
    "关键词是「可分离」。这个卷宗由训练数据学出，随后在那份用来检验它的分片被打开之前就已冻结并做成摘要。它里面没有任何东西是权重，也没有任何东西能扩大被允许的范围：把它拿掉，改变的是答案被找到的快慢，而不是哪些答案是合法的。",
  "The interesting question about any decision-making system is what it carries forward, because that is what a later behaviour depends on. Two of the three carried registers hold something that was learned, and the second is kept apart from the engine on purpose: what the system learned can be inspected, replaced or removed without touching what it is allowed to conclude.":
    "关于任何一个作决定的系统，有意思的问题是它把什么带到了下一次，因为后来的行为正是靠这个。三个被带走的寄存器里有两个装着学到的东西，而第二个是被刻意放在引擎之外的：系统学到的东西可以被查看、替换或移除，而不触碰它被允许得出什么结论。",
  "There are no weights, and there is learning. What is learned is where to look and in what order, held in a volume kept apart from the engine; what may never be learned is the verdict. The public runs measure that learned state on data it was never fitted to, and the coverage that belongs beside each accuracy is published with it on the evidence page.":
    "没有权重，但有学习。学到的是往哪儿看、按什么顺序看；这些放在一个与引擎分开的卷宗里。永远学不到的，是判定。公开运行测的正是这个学到的状态，用的是从未被拿来拟合它的数据；而每一个准确率旁边理应站着的覆盖率，也和它一起公布在证据页上。",
  "This is not the route above; it is one evaluated row of a public run, which takes one bounded step and writes one receipt. It is here because it is the part of the system with the hardest numbers attached: the set of possible answers is closed before the split that tests it is opened, every cut is a rule anybody can read, and the ordering can be recomputed from the record alone.":
    "这不是上面那条路；这是一次公开运行中被评测的某一行，它走一个有界的步骤，写下一份回执。它出现在这里，是因为这是整个系统里数字最硬的部分：可能答案的集合在那份用来检验它的分片被打开之前就已封闭，每一次筛除都是一条谁都能读的规则，而顺序仅凭记录就能重算出来。",
};

export const routeItemsAr: TranslationDictionary = {
  "It is not, and the gap is published rather than glossed. What a public run exercises is one bounded step: a closed set of possible answers, a ranking over it, the three conditions an answer has to meet, and a typed route that has to pass. The phases around that step — taking a probe, waiting for an outside disclosure, revising a persistent Atlas — are not in the measured path, so the architecture's joint contribution is unestablished rather than demonstrated. An end-to-end run that would settle it is the next registered step.":
    "لا، والفجوةُ منشورةٌ لا مُلمَّعة. ما يُشغّله التشغيلُ العامّ خطوةٌ واحدةٌ محدودة: مجموعةٌ مغلقةٌ من الأجوبة الممكنة، وترتيبٌ عليها، والشروطُ الثلاثة التي على الجواب أن يستوفيها، ومسارٌ محدَّدُ النوع عليه أن يجتاز. أمّا الأطوارُ المحيطة بتلك الخطوة — أخذُ مِسبار، وانتظارُ كشفٍ خارجيّ، ومراجعةُ أطلسٍ دائم — فليست في المسار المقيس، ولذلك فإسهامُ البنية مجتمعةً غيرُ مُثبَتٍ لا مُبرهَن. والتشغيلُ الشاملُ الذي يحسم ذلك هو الخطوةُ المسجَّلة التالية.",
  "One evaluated row with concrete values": "سطرٌ واحدٌ مُقيَّمٌ بقيمٍ محدَّدة",
  "One held-out row carried through one bounded step": "سطرٌ واحدٌ محجوزٌ مَسوقٌ عبر خطوةٍ واحدةٍ محدودة",
  "One row is evaluated in one bounded step, and every value in it can be recomputed.":
    "يُقيَّم سطرٌ واحدٌ في خطوةٍ واحدةٍ محدودة، وكلُّ قيمةٍ فيها قابلةٌ لإعادة الحساب.",
  "Reaching a decision here is not a hidden chain of reasoning. It is a closed set of phases with two lawful ways out, a budget counted in units as it is spent, and a learning phase that opens only after somebody outside the system discloses what actually happened. This page walks the whole of it, then shows one evaluated row of a public run inside it — and ends with the part of the route the published results did not measure.":
    "بلوغُ القرار هنا ليس سلسلةَ استدلالٍ مخفيّة. إنّه مجموعةٌ مغلقةٌ من الأطوار لها مخرجان مشروعان، وميزانيّةٌ تُحسَب بالوحدات وهي تُنفَق، وطورُ تعلّمٍ لا ينفتح إلّا بعد أن يكشف أحدٌ من خارج النظام ما جرى فعلًا. تمشي هذه الصفحةُ الطريقَ كلَّه، ثمّ تُري بداخله سطرًا واحدًا مُقيَّمًا من تشغيلٍ عامّ — وتنتهي عند الجزء من الطريق الذي لم تَقِسْه النتائجُ المنشورة.",
  "Separable is the operative word. The volume is learned from the training data, then frozen and digested before the split that tests it is opened. Nothing in it is a weight, and nothing in it can widen what is permitted: removing it changes how quickly an answer is found, never which answers are lawful.":
    "الكلمةُ المفتاح هي القابليّةُ للفصل. يُتعلَّم هذا المُجلَّد من بيانات التدريب، ثمّ يُجمَّد ويُبصَم قبل أن تُفتَح الشريحةُ التي تختبره. ولا شيءَ فيه وزنٌ، ولا شيءَ فيه يستطيع توسيعَ المسموح: نزعُه يغيّر سرعةَ بلوغِ الجواب، لا أيَّ الأجوبةِ مشروع.",
  "The interesting question about any decision-making system is what it carries forward, because that is what a later behaviour depends on. Two of the three carried registers hold something that was learned, and the second is kept apart from the engine on purpose: what the system learned can be inspected, replaced or removed without touching what it is allowed to conclude.":
    "السؤالُ المثيرُ عن أيّ نظامِ قرارٍ هو ما الذي يحمله إلى ما بعد، لأنّ السلوكَ اللاحق يقوم عليه. اثنان من السجلّات الثلاثة المحمولة يحملان شيئًا مُتعلَّمًا، والثاني مُبقًى بعيدًا عن المحرّك عن قصد: ما تعلَّمه النظام يمكن فحصُه أو استبدالُه أو نزعُه دون المساسِ بما يُسمح له أن يستنتجه.",
  "There are no weights, and there is learning. What is learned is where to look and in what order, held in a volume kept apart from the engine; what may never be learned is the verdict. The public runs measure that learned state on data it was never fitted to, and the coverage that belongs beside each accuracy is published with it on the evidence page.":
    "لا أوزانَ هناك، وهناك تعلُّم. المُتعلَّمُ هو أين يُنظَر وبأيّ ترتيب، وهو محفوظٌ في مُجلَّدٍ مُبقًى بعيدًا عن المحرّك؛ أمّا ما لا يُتعلَّم أبدًا فهو الحُكم. والتشغيلاتُ العامّة تقيس تلك الحالةَ المتعلَّمة على بياناتٍ لم تُلاءَم عليها قطّ، والتغطيةُ التي يجب أن تقف بجانب كلّ دقّةٍ تُنشَر معها في صفحة الأدلّة.",
  "This is not the route above; it is one evaluated row of a public run, which takes one bounded step and writes one receipt. It is here because it is the part of the system with the hardest numbers attached: the set of possible answers is closed before the split that tests it is opened, every cut is a rule anybody can read, and the ordering can be recomputed from the record alone.":
    "هذا ليس الطريقَ أعلاه؛ إنّه سطرٌ واحدٌ مُقيَّمٌ من تشغيلٍ عامّ، يخطو خطوةً واحدةً محدودة ويكتب إيصالًا واحدًا. وهو هنا لأنّه الجزءُ الذي تتعلّق به أصلبُ الأرقام في المنظومة: مجموعةُ الأجوبة الممكنة تُغلَق قبل أن تُفتَح الشريحةُ التي تختبرها، وكلُّ استبعادٍ قاعدةٌ يستطيع أيُّ أحدٍ قراءتها، والترتيبُ يُعاد حسابُه من السجلّ وحده.",
};
