import type { TranslationDictionary } from "../translations";

export const termAcademicRu: TranslationDictionary = {
  "What the word means in mathematics, before it means anything here.":
    "Что это слово значит в математике — прежде чем оно начнёт что-то значить здесь.",
  "A bijection of the carrier onto itself that commutes with every operation. The automorphisms form a group under composition. For the full expansion the group is isomorphic to the unit group U(n) = (Z/nZ)^×, acting by multiplication of indices; the constant P_0 is fixed by every element, which is what rules out the additive translations.":
    "Биекция носителя на себя, перестановочная с каждой операцией сигнатуры. Автоморфизмы образуют группу относительно композиции. Для полного обогащения эта группа изоморфна группе обратимых элементов U(n) = (Z/nZ)^×, действующей умножением индексов; константа P_0 неподвижна относительно любого автоморфизма, что и исключает аддитивные сдвиги.",
  "A derived statement, not a further axiom: it follows from P_0 being a left zero that any left-normed term whose leftmost leaf is P_0 evaluates to P_0 regardless of the remaining operands. The rule is stated separately only because it is the form in which the fact is used.":
    "Выводимое утверждение, а не дополнительная аксиома: из того, что P_0 — левый нуль, следует, что любой левонормированный терм с крайним левым листом P_0 принимает значение P_0 независимо от остальных операндов. Правило выделено отдельно лишь потому, что именно в такой форме оно применяется.",
  "A description of a software release, not a mathematical statement. The counts are cardinalities of declared finite sets fixed by the release contract, and they are reported for auditability. No theorem in this glossary depends on any of them.":
    "Описание программного выпуска, а не математическое утверждение. Приведённые числа — мощности объявленных конечных множеств, зафиксированных контрактом выпуска, и публикуются они ради проверяемости. Ни одна теорема этого глоссария от них не зависит.",
  "A homomorphism from a group into the symmetric group of a set. Here Aut(Q_n) acts on Q_n and, diagonally, on ordered pairs. The orbit–stabiliser theorem then gives |G| = |Orb(x)| · |Stab(x)| for every x, which is the identity all orbit counts on this site reduce to.":
    "Гомоморфизм группы в симметрическую группу множества. Здесь Aut(Q_n) действует на Q_n, а также диагонально на упорядоченных парах. Теорема об орбите и стабилизаторе даёт |G| = |Orb(x)| · |Stab(x)| для любого x — тождество, к которому сводятся все подсчёты орбит на этом сайте.",
  "A homomorphism from a structure to itself. Endomorphisms form a monoid under composition, and the automorphisms are exactly its invertible elements. An endomorphism need not be injective, so it may collapse distinct elements while still preserving both laws.":
    "Гомоморфизм структуры в себя. Эндоморфизмы образуют моноид относительно композиции, а автоморфизмы — в точности его обратимые элементы. Эндоморфизм не обязан быть инъективным, поэтому он может склеивать различные элементы, сохраняя при этом оба закона.",
  "A homomorphism from the additive group into the multiplicative group of the complex numbers. The characters of a finite abelian group form a dual group of the same order, and orthogonality of characters supplies a second, independent route to counts obtained combinatorially.":
    "Гомоморфизм аддитивной группы в мультипликативную группу комплексных чисел. Характеры конечной абелевой группы образуют двойственную группу того же порядка, а соотношения ортогональности характеров дают второй, независимый путь к величинам, полученным комбинаторно.",
  "A map from the Cartesian square of the carrier into the carrier, hence total and single-valued by definition. Totality is what makes the Cayley table complete, and single-valuedness is what makes the entry at a given row and column unique. Both laws of the signature are binary operations in exactly this sense.":
    "Отображение декартова квадрата носителя в носитель, а значит, всюду определённое и однозначное по определению. Всюду определённость делает таблицу Кэли полной, однозначность — запись в данной строке и данном столбце единственной. Оба закона сигнатуры являются бинарными операциями именно в этом смысле.",
  "A map preserving every operation of the signature. Composites of homomorphisms are homomorphisms, and the image of a homomorphism is a closed subset of the codomain. Preservation is required for all laws simultaneously; a map preserving ⊕ but not ★ is not a homomorphism of the expansion.":
    "Отображение, сохраняющее каждую операцию сигнатуры. Композиция гомоморфизмов есть гомоморфизм, а образ гомоморфизма — замкнутое подмножество кообласти. Сохранение требуется одновременно для всех законов: отображение, сохраняющее ⊕, но не ★, гомоморфизмом обогащения не является.",
  "A project name for a binary operation obtained from ⊕_n by overriding the row indexed 0. The resulting structure (Q_n, ★_n) is a magma which for n ≥ 2 is neither associative nor commutative and possesses no two-sided identity; it is the deviation from the group law that carries all of the asymmetry the project relies on.":
    "Проектное название бинарной операции, полученной из ⊕_n переопределением строки с индексом 0. Полученная структура (Q_n, ★_n) — магма, которая при n ≥ 2 не ассоциативна, не коммутативна и не имеет двустороннего нейтрального элемента; именно это отклонение от группового закона несёт всю асимметрию, на которую опирается проект.",
  "A project name for an element of the carrier. The label P_i is in bijective correspondence with the residue class i modulo n, so the labelling carries no order, magnitude, or metric: P_2 is not a larger object than P_1, and no expression on this site treats it as one.":
    "Проектное название для элемента носителя. Метка P_i взаимно однозначно отвечает классу вычетов i по модулю n, и потому в разметке нет ни порядка, ни величины, ни метрики: P_2 не больше, чем P_1, и ни одно выражение на этом сайте так его не трактует.",
  "A project name for the group operation of the cyclic group Z/nZ transported onto Q_n along the labelling. The reduct (Q_n, ⊕_n) is therefore an abelian group of order n generated by P_1, and every group-theoretic statement about cyclic groups applies to it verbatim.":
    "Проектное название групповой операции циклической группы Z/nZ, перенесённой на Q_n вдоль разметки. Поэтому обеднение (Q_n, ⊕_n) есть абелева группа порядка n с образующим P_1, и всякое теоретико-групповое утверждение о циклических группах применимо к нему дословно.",
  "A project name for the index n of the family, equivalently for the order of the carrier. The seven levels form a family of algebras rather than a chain of subalgebras: an inclusion between two of them exists only when the associated structure-preserving map does, which is a separate question settled by divisibility.":
    "Проектное название для индекса n семейства, то есть для порядка носителя. Семь уровней образуют семейство алгебр, а не цепь подалгебр: вложение одного в другой существует лишь тогда, когда существует соответствующее сохраняющее структуру отображение, а это отдельный вопрос, решаемый делимостью.",
  "A project name for the left argument of the operation in the intended reading of a step. Mathematically it is simply the first coordinate of the ordered pair; the name records the operational role the project assigns to it and carries no additional algebraic content.":
    "Проектное название для левого аргумента операции при подразумеваемом прочтении шага. Математически это просто первая координата упорядоченной пары; название фиксирует операционную роль, которую ему приписывает проект, и не несёт дополнительного алгебраического содержания.",
  "A project name for the right argument and, by extension, for the value of the operation on the pair. The distinction between the two argument positions is not algebraic — both are elements of Q_n — but it is recorded, because the operations are non-commutative and the ordered pair is therefore not recoverable from the unordered one.":
    "Проектное название для правого аргумента и, по расширению, для значения операции на паре. Различие между двумя позициями аргументов не алгебраическое — оба суть элементы Q_n, — но оно фиксируется, поскольку операции некоммутативны и упорядоченная пара не восстанавливается по неупорядоченной.",
  "A project-defined index consisting of a level, a law, an operand-role tag, and an ordered pair. It is not an algebraic invariant: two distinct typed coordinates may evaluate to the same element of Q_n. Counting typed coordinates therefore counts labelled records, not equivalence classes of behaviour.":
    "Определённый проектом индекс, состоящий из уровня, закона, метки роли операнда и упорядоченной пары. Это не алгебраический инвариант: две различные типизированные координаты могут давать один и тот же элемент Q_n. Поэтому подсчёт типизированных координат считает помеченные записи, а не классы эквивалентности поведения.",
  "A publication convention marking the limit of an asserted claim. In logical terms it is the explicit restriction of a quantifier: assertions are made over a stated domain, and nothing is asserted outside it. The convention exists because unrestricted readings of restricted results are the project's main misuse risk.":
    "Издательское соглашение, отмечающее предел заявленного утверждения. В логических терминах это явное ограничение квантора: утверждения делаются над названной областью, и вне её ничего не утверждается. Соглашение существует потому, что неограниченное прочтение ограниченных результатов — главный риск неверного использования проекта.",
  "A reduct is obtained by deleting operations from the signature while keeping the carrier; an expansion is the converse. Truth is not preserved upwards: a sentence valid in the reduct need not be valid in the expansion, because the expansion admits terms the reduct cannot form. Every result on this site therefore names the signature it was proved over.":
    "Обеднение получается удалением операций из сигнатуры при сохранении носителя; обогащение — обратная процедура. Истинность не переносится вверх: предложение, истинное в обеднении, не обязано быть истинным в обогащении, поскольку обогащение допускает термы, невыразимые в обеднении. Поэтому каждый результат на этом сайте называет сигнатуру, над которой он доказан.",
  "A separation of three distinct kinds of assertion: theorems about the algebras, verified properties of a running implementation, and specified but unimplemented architecture. None entails another. Conflating them is a category error, and the site is organised to make the error visible rather than convenient.":
    "Разграничение трёх различных видов утверждений: теорем об алгебрах, проверенных свойств работающей реализации и специфицированной, но не реализованной архитектуры. Ни одно из них не влечёт другое. Их смешение — ошибка категории, и сайт устроен так, чтобы эта ошибка была заметна, а не удобна.",
  "A signature is a set of operation symbols with declared arities; a constant is an operation of arity zero. The signature fixes which terms are well formed and therefore which statements are expressible at all. Naming P_0 as a constant is what makes it available to automorphism conditions.":
    "Сигнатура — это множество операционных символов с объявленными арностями; константа есть операция арности нуль. Сигнатура фиксирует, какие термы корректно построены, а тем самым — какие утверждения вообще выразимы. Именно объявление P_0 константой делает его доступным для условий на автоморфизмы.",
  "A subset closed under all operations of the signature; equivalently, the carrier of a subalgebra. Closed subsets form a lattice under intersection, and the closure of a set is the least closed subset containing it. For ⊕_n the closed subsets are exactly the subgroups, one for each divisor of n.":
    "Подмножество, замкнутое относительно всех операций сигнатуры; эквивалентно — носитель подалгебры. Замкнутые подмножества образуют решётку относительно пересечения, а замыкание множества есть наименьшее содержащее его замкнутое подмножество. Для ⊕_n замкнутые подмножества — в точности подгруппы, по одной на каждый делитель n.",
  "A torsor over a group is a set with a free and transitive action but no preferred base point; the holomorph is the semidirect product of the group with its automorphism group. The additive reduct is a torsor under translation, and naming the constant P_0 in the signature is exactly what selects a base point and reduces the symmetry group.":
    "Торсор над группой — это множество со свободным транзитивным действием, но без выделенной точки; голоморф есть полупрямое произведение группы с её группой автоморфизмов. Аддитивное обеднение является торсором относительно сдвигов, и именно объявление константы P_0 в сигнатуре выбирает базовую точку и уменьшает группу симметрий.",
  "A two-sided identity is neutral from both sides, and it is unique whenever it exists: two identities e and e′ satisfy e = e ∘ e′ = e′. P_0 is a two-sided identity for ⊕_n; for ★_n it is right neutral only, so ★_n has no identity for n ≥ 2.":
    "Двусторонний нейтральный элемент нейтрален с обеих сторон и единствен, если существует: два нейтральных элемента e и e′ удовлетворяют e = e ∘ e′ = e′. Элемент P_0 является двусторонним нейтральным для ⊕_n; для ★_n он лишь правый нейтральный, поэтому при n ≥ 2 у ★_n нейтрального элемента нет.",
  "A universally quantified identity in the two arguments. It holds for ⊕_n, so the additive reduct is abelian, and fails for ★_n at every level n ≥ 2. Failure is what makes the ordered pair, rather than the unordered pair, the correct index of a step.":
    "Тождество, универсально квантифицированное по обоим аргументам. Оно выполняется для ⊕_n, поэтому аддитивное обеднение абелево, и нарушается для ★_n на каждом уровне n ≥ 2. Именно нарушение делает упорядоченную, а не неупорядоченную пару правильным индексом шага.",
  "A universally quantified identity. Where it holds, bracketing may be omitted and the generalised associative law licenses any parenthesisation of a product. It holds for ⊕_n and fails for ★_n, so bracket structure is semantically significant in the expansion.":
    "Универсально квантифицированное тождество. Там, где оно выполняется, скобки можно опускать, а обобщённый закон ассоциативности допускает любую расстановку скобок в произведении. Оно выполняется для ⊕_n и нарушается для ★_n, поэтому в обогащении скобочная структура семантически значима.",
  "A worked application of the orbit-counting lemma to the diagonal action of Aut on ordered pairs at level three. The automorphism group has order two, the identity fixes all nine pairs and the involution fixes one, so the number of orbits is five. Restoring the four role tags multiplies this to twenty.":
    "Разобранное применение леммы о числе орбит к диагональному действию Aut на упорядоченных парах на третьем уровне. Группа автоморфизмов имеет порядок два: тождественное отображение оставляет неподвижными все девять пар, инволюция — одну, поэтому число орбит равно пяти. Восстановление четырёх меток ролей умножает это число до двадцати.",
  "An element e is right neutral when x ∘ e = x for every x. For ★_n the element P_0 is right neutral and simultaneously a left zero, so it is not a two-sided identity for n ≥ 2 — the two one-sided conditions are satisfied by the same element in opposite directions, which is precisely why the structure is not a monoid.":
    "Элемент e называется правым нейтральным, если x ∘ e = x для всех x. Для ★_n элемент P_0 является правым нейтральным и одновременно левым нулём, поэтому при n ≥ 2 он не двусторонний нейтральный: два односторонних условия выполняются одним и тем же элементом в противоположных направлениях, из-за чего структура и не является моноидом.",
  "An element z is a left zero (left absorbing element) when z ∘ y = z for every y in the carrier. For n ≥ 2 the element P_0 is the unique left zero of ★_n, and ⊕_n has none. Uniqueness follows immediately: two left zeros z and z′ satisfy z = z ∘ z′ = z′.":
    "Элемент z называется левым нулём (левым поглощающим элементом), если z ∘ y = z для всякого y из носителя. При n ≥ 2 элемент P_0 — единственный левый нуль операции ★_n, а у ⊕_n левых нулей нет. Единственность следует немедленно: два левых нуля z и z′ дают z = z ∘ z′ = z′.",
  "An elementary enumeration of the labelled index set defined above: the number of ordered pairs summed over the family, multiplied by the number of laws and of role tags. The figure is a cardinality of a syntactic set. It bounds no complexity measure and expresses no capability claim.":
    "Элементарное перечисление помеченного индексного множества, определённого выше: число упорядоченных пар, просуммированное по семейству и умноженное на число законов и меток ролей. Эта величина есть мощность синтаксического множества. Она не ограничивает никакой меры сложности и не выражает никакого утверждения о возможностях.",
  "An engineering artefact rather than a mathematical object: a record sufficient to reproduce a bounded execution. It has no algebraic content, and no theorem on this site depends on it. It is listed among the concepts because the project's evidence claims are stated in terms of it.":
    "Инженерный артефакт, а не математический объект: запись, достаточная для воспроизведения ограниченного исполнения. Алгебраического содержания она не имеет, и ни одна теорема на этом сайте от неё не зависит. В перечень понятий она включена потому, что доказательные утверждения проекта формулируются в её терминах.",
  "An equivalence relation compatible with every operation of the signature. Congruences are exactly the kernels of homomorphisms, and the quotient Q_n/θ carries a well-defined induced structure. The congruence lattice of the full expansion is trivial for n prime, which is why coarsening the state is not generally available.":
    "Отношение эквивалентности, согласованное с каждой операцией сигнатуры. Конгруэнции суть в точности ядра гомоморфизмов, а факторалгебра Q_n/θ несёт корректно определённую индуцированную структуру. Решётка конгруэнций полного обогащения тривиальна при простом n — поэтому огрубление состояния в общем случае недоступно.",
  "An equivalence relation partitions its domain, and the quotient is the set of classes. A quotient of an algebra carries a well-defined induced structure exactly when the relation is a congruence; without that compatibility the coarser view is a set-level construction only and proves nothing about the operations.":
    "Отношение эквивалентности разбивает свою область, а фактор-множество — это множество классов. Индуцированная структура на факторе определена корректно ровно тогда, когда отношение оказывается конгруэнцией. Без такой согласованности более грубое представление остаётся теоретико-множественной конструкцией и ничего об операциях не доказывает.",
  "An injective homomorphism, equivalently an isomorphism onto a subalgebra of the codomain. For the additive reducts this is Lagrange's criterion for cyclic groups: a copy of Z/mZ sits inside Z/nZ exactly when m divides n, and the subgroup realising it is unique.":
    "Инъективный гомоморфизм, эквивалентно — изоморфизм на подалгебру кообласти. Для аддитивных обеднений это критерий Лагранжа для циклических групп: копия Z/mZ лежит внутри Z/nZ в точности тогда, когда m делит n, и реализующая её подгруппа единственна.",
  "An operation is associative when (x ∘ y) ∘ z = x ∘ (y ∘ z) holds identically. A single counterexample refutes the identity, and the triple displayed above supplies one at every level n ≥ 2. Consequently (Q_n, ★_n) is a magma and not a semigroup, and no theorem requiring associativity may be invoked for it.":
    "Операция ассоциативна, если тождество (x ∘ y) ∘ z = x ∘ (y ∘ z) выполняется всюду. Одного контрпримера достаточно для опровержения тождества, и приведённая выше тройка даёт его на каждом уровне n ≥ 2. Следовательно, (Q_n, ★_n) — магма, а не полугруппа, и ни одна теорема, требующая ассоциативности, к ней неприменима.",
  Combinatorics: "Комбинаторика",
  "Congruence modulo n is the equivalence relation on Z whose classes are the residues 0, …, n−1. The quotient ring Z/nZ inherits a well-defined addition, and it is that addition which the first law realises. Finiteness of Q_n is a consequence of passing to the quotient, not an additional stipulation.":
    "Сравнение по модулю n — это отношение эквивалентности на Z, классами которого являются вычеты 0, …, n−1. Факторкольцо Z/nZ наследует корректно определённое сложение, и именно это сложение реализует первый закон. Конечность Q_n есть следствие перехода к фактору, а не дополнительное условие.",
  "For a self-map of a finite set, the rank is the cardinality of its image. Fixing the left argument of a law yields such a map, and its rank measures how many elements remain distinguishable after one application. Rank is non-increasing under composition, which is the precise sense in which information can only be lost.":
    "Для отображения конечного множества в себя ранг есть мощность его образа. Фиксация левого аргумента закона даёт такое отображение, и его ранг измеряет, сколько элементов остаются различимыми после одного применения. Ранг не возрастает при композиции — в этом и состоит точный смысл того, что информация может только теряться.",
  "For an odd prime p, the non-zero squares form an index-two subgroup of the unit group, and multiplication by a fixed residue either preserves or interchanges the two cosets according to the Legendre symbol. The block structure of the action follows, and it is a property of the modulus rather than of any design decision.":
    "Для нечётного простого p ненулевые квадраты образуют подгруппу индекса два в группе обратимых элементов, а умножение на фиксированный вычет либо сохраняет, либо меняет местами два смежных класса — в зависимости от значения символа Лежандра. Отсюда и блочная структура действия: она определяется модулем, а не каким-либо проектным решением.",
  "Group theory": "Теория групп",
  "In a group every element has a unique inverse, and a generator is an element whose cyclic subgroup is the whole group. Q_n under ⊕_n is generated by P_1, so the additive reduct is cyclic and reachability of one element from another is never an obstruction.":
    "В группе каждый элемент имеет единственный обратный, а образующей называется элемент, циклическая подгруппа которого совпадает со всей группой. Множество Q_n относительно ⊕_n порождается элементом P_1, поэтому аддитивное обеднение циклично, и достижимость одного элемента из другого никогда не является препятствием.",
  "Isomorphism is a bijective homomorphism and is strictly weaker than identity of objects: isomorphic structures satisfy the same sentences of the signature while remaining distinct as sets. Reporting an isomorphism as an equality would overstate the result, so the site uses the word only in its exact sense.":
    "Изоморфизм — это биективный гомоморфизм, и он строго слабее равенства объектов: изоморфные структуры удовлетворяют одним и тем же предложениям сигнатуры, оставаясь при этом различными как множества. Объявить изоморфизм равенством значило бы усилить результат сверх доказанного, поэтому на сайте это слово употребляется только в точном смысле.",
  "Number theory": "Теория чисел",
  "Project convention": "Соглашение проекта",
  "Project term, not standard mathematics": "Термин проекта, а не стандартной математики",
  "Sets, maps, and relations": "Множества, отображения и отношения",
  "Standard term, narrowed to this setting": "Стандартный термин, суженный до данной конструкции",
  "Standard term, standard meaning": "Стандартный термин в стандартном значении",
  "Standing of the word": "Статус термина",
  "Summation over the fibres of a map. Since the fibres of a function partition its domain, a total computed fibrewise is exact and admits decomposition back into its parts. Aggregates published on this site are computed this way so that any total can be audited against its summands.":
    "Суммирование по слоям отображения. Поскольку слои функции разбивают её область определения, итог, вычисленный послойно, точен и допускает обратное разложение на составляющие. Все сводные величины на сайте вычисляются именно так, чтобы любой итог можно было сверить со своими слагаемыми.",
  "THE DEFINITION AS A MATHEMATICIAN WOULD STATE IT": "ОПРЕДЕЛЕНИЕ В ТОМ ВИДЕ, В КАКОМ ЕГО СФОРМУЛИРОВАЛ БЫ МАТЕМАТИК",
  "The Catalan numbers count the parenthesisations of a sequence of k+1 operands, equivalently the binary trees with k internal nodes. Because the second law is non-associative, distinct parenthesisations may denote distinct values, so this count bounds the number of syntactically distinct terms of a given length.":
    "Числа Каталана подсчитывают расстановки скобок в последовательности из k+1 операндов — равносильно, бинарные деревья с k внутренними вершинами. Так как второй закон неассоциативен, различные расстановки скобок могут обозначать различные значения, и потому это число ограничивает сверху количество синтаксически различных термов заданной длины.",
  "The Chinese remainder theorem gives a ring isomorphism whenever the moduli are coprime, so composite levels decompose as direct products while prime levels are indecomposable. The distinction is a hard limit on what a single level can express and is not affected by any choice made in the project.":
    "Китайская теорема об остатках даёт изоморфизм колец всякий раз, когда модули взаимно просты, поэтому составные уровни разлагаются в прямое произведение, а простые уровни неразложимы. Это различие — жёсткий предел выразительной силы отдельного уровня, и оно не зависит ни от одного решения, принятого в проекте.",
  "The affine group of Z/nZ, equal to the holomorph of the cyclic group, acts on the additive reduct by structure-preserving maps. Adjoining the constant P_0 to the signature forces v = 0, so the automorphism group of the expansion is the point stabiliser U(n) rather than the full affine group.":
    "Аффинная группа кольца Z/nZ, совпадающая с голоморфом циклической группы, действует на аддитивном обеднении структурно сохраняющими отображениями. Включение константы P_0 в сигнатуру вынуждает v = 0, поэтому группа автоморфизмов обогащения есть стабилизатор точки U(n), а не полная аффинная группа.",
  "The carrier (underlying set) of an algebraic structure is the set on which its operations are defined. Here it is the finite set Q_n of cardinality n, indexed by the residues 0 through n−1. An algebra is the pair (Q_n, {⊕_n, ★_n}); statements about the algebra are statements about that pair, never about the carrier alone.":
    "Носитель (основное множество) алгебраической структуры — это множество, на котором определены её операции. Здесь это конечное множество Q_n мощности n, проиндексированное вычетами от 0 до n−1. Алгеброй называется пара (Q_n, {⊕_n, ★_n}); утверждения об алгебре суть утверждения об этой паре, но никогда — об одном лишь носителе.",
  "The constant map onto the named element. It preserves both laws trivially, hence Hom(Q_m, Q_n) is non-empty for every ordered pair of levels. Consequently the statement that two levels admit no homomorphism is false in general; the substantive question is whether a non-constant one exists.":
    "Постоянное отображение в указанный элемент. Оно тривиально сохраняет оба закона, поэтому Hom(Q_m, Q_n) непусто для любой упорядоченной пары уровней. Следовательно, утверждение, что между двумя уровнями нет гомоморфизма, в общем случае ложно; содержательный вопрос — существует ли непостоянный гомоморфизм.",
  "The equivalence class of an integer under congruence modulo n. The classes partition Z and inherit well-defined addition and multiplication, making Z/nZ a commutative ring. Elements of the carrier are identified with these classes, which is what makes the wrap-around an identity rather than a truncation.":
    "Класс эквивалентности целого числа по сравнению по модулю n. Классы разбивают Z и наследуют корректно определённые сложение и умножение, что превращает Z/nZ в коммутативное кольцо. Элементы носителя отождествляются с этими классами — именно поэтому переход через край есть тождество, а не усечение.",
  "The formation of terms by substituting the value of one operation into an argument of another. Since ★_n is non-associative, distinct parse trees over the same operand sequence may denote distinct elements, and a term is therefore individuated by its tree rather than by its leaves.":
    "Образование термов подстановкой значения одной операции в аргумент другой. Поскольку ★_n неассоциативна, различные деревья разбора над одной и той же последовательностью операндов могут обозначать различные элементы, и потому терм индивидуализируется своим деревом, а не своими листьями.",
  "The maps obtained by fixing one argument. In a group both are bijections, which is the content of Cayley's theorem for the additive reduct. For the second law the left translation by P_0 is constant, so it is not injective and the corresponding row of the table degenerates.":
    "Отображения, получаемые фиксацией одного из аргументов. В группе оба они биективны — в этом и состоит содержание теоремы Кэли для аддитивного обеднения. Для второго закона левый сдвиг на P_0 постоянен, а значит не инъективен, и соответствующая строка таблицы вырождается.",
  "The multiplication table of a finite magma: the n × n array whose (i, j) entry is the value of the operation on the ordered pair (P_i, P_j). Because the operation is total and the carrier is finite, the table determines the structure completely, and any property expressible in the signature can in principle be decided by exhaustive inspection of n² entries.":
    "Таблица умножения конечной магмы: массив размера n × n, элемент (i, j) которого есть значение операции на упорядоченной паре (P_i, P_j). Поскольку операция всюду определена, а носитель конечен, таблица полностью задаёт структуру, и любое свойство, выразимое в сигнатуре, в принципе разрешимо исчерпывающим просмотром n² клеток.",
  "The multiplicative group of residues coprime to n, of order given by Euler's totient function. Since Aut of the expansion is isomorphic to U(n), the totient counts the structure-preserving relabellings available at each level, and it is maximal relative to n precisely when n is prime.":
    "Мультипликативная группа вычетов, взаимно простых с n; её порядок задаётся функцией Эйлера. Так как группа автоморфизмов обогащения изоморфна U(n), функция Эйлера подсчитывает число структурно сохраняющих переобозначений, доступных на каждом уровне, и она максимальна относительно n в точности тогда, когда n просто.",
  "The notation table, understood as a declared object language: a finite list of symbols together with their intended readings. It is stated once so that every page can be read without appeal to an external convention, and it is closed — a symbol absent from the legend does not occur in the published text. Closure is what makes a claim on this site checkable without having to guess what a mark was meant to denote.":
    "Таблица обозначений, понимаемая как объявлённый предметный язык: конечный список символов вместе с их предполагаемыми прочтениями. Она приводится один раз, чтобы любую страницу можно было читать, не обращаясь к внешним соглашениям, и она замкнута — символ, отсутствующий в таблице, в опубликованном тексте не встречается. Именно замкнутость делает любое утверждение на сайте проверяемым без угадывания того, что должен был обозначать тот или иной знак.",
  "The orbit structure induced by the order-two automorphism given by index negation, which exists for every n ≥ 3. Its orbits have length two except at the fixed points of the involution, namely P_0 and, when n is even, the element of index n/2.":
    "Орбитная структура, порождённая автоморфизмом порядка два — обращением индекса, который существует при всяком n ≥ 3. Его орбиты имеют длину два, за исключением неподвижных точек этой инволюции, а именно P_0 и, при чётном n, элемента с индексом n/2.",
  "The orbit-counting lemma, a corollary of orbit–stabiliser obtained by double counting the set of pairs (g, x) with g · x = x. It converts an orbit count into an average of fixed-point counts, which is the form in which the counts published here are computed and can be independently recomputed.":
    "Лемма о числе орбит (лемма Бёрнсайда) — следствие теоремы об орбите и стабилизаторе, получаемое двойным подсчётом множества пар (g, x) с g · x = x. Она сводит подсчёт орбит к усреднению числа неподвижных точек, и именно в этой форме вычисляются публикуемые здесь количества, так что их можно независимо пересчитать.",
  "The order of an element is the least positive k with k copies of it summing to the identity. By Lagrange it divides the group order, and in the cyclic group of order n the element of index i has order n/gcd(i, n). Generators are exactly the indices coprime to n.":
    "Порядком элемента называется наименьшее натуральное k, при котором сумма k его копий равна нейтральному элементу. По теореме Лагранжа он делит порядок группы, а в циклической группе порядка n элемент с индексом i имеет порядок n/gcd(i, n). Образующие — это в точности индексы, взаимно простые с n.",
  "The requirement that the operation not leave the carrier — already implied by writing it as a map into Q_n. Closure over a finite carrier is what makes exhaustive verification a terminating procedure rather than an unbounded search.":
    "Требование, чтобы операция не выводила за пределы носителя, — уже заложенное в том, что она записана как отображение в Q_n. Именно замкнутость на конечном носителе делает исчерпывающую проверку завершающейся процедурой, а не неограниченным перебором.",
  "The set of images of a point under the whole group. Orbits are the classes of an equivalence relation and therefore partition the set acted upon. Two elements in the same orbit are indistinguishable by any property invariant under the action, so orbits — not labels — are the correct objects to enumerate.":
    "Множество образов точки под действием всей группы. Орбиты суть классы отношения эквивалентности и потому разбивают множество, на котором происходит действие. Два элемента одной орбиты неразличимы любым свойством, инвариантным относительно действия, поэтому перечислять следует орбиты, а не метки.",
  "The set of values actually attained. A map is surjective exactly when its image is the whole codomain, and for maps of a finite set into itself injectivity, surjectivity, and bijectivity coincide — which is why a non-injective translation is immediately detectable as a shrinking image.":
    "Множество фактически достигаемых значений. Отображение сюръективно в точности тогда, когда его образ совпадает со всей областью значений, а для отображений конечного множества в себя инъективность, сюръективность и биективность равносильны — поэтому неинъективный сдвиг сразу обнаруживается по уменьшению образа.",
  "The standard classification of maps. On a finite set of fixed cardinality the three notions collapse: a self-map is injective if and only if it is surjective if and only if it is bijective. Automorphisms must be bijections, since a non-injective relabelling would identify two distinct elements.":
    "Стандартная классификация отображений. На конечном множестве фиксированной мощности три понятия совпадают: отображение множества в себя инъективно тогда и только тогда, когда оно сюръективно, и тогда и только тогда, когда оно биективно. Автоморфизмы обязаны быть биекциями, поскольку неинъективное переобозначение отождествило бы два различных элемента.",
  "The standard hierarchy: closure alone gives a magma; adding associativity gives a semigroup; a two-sided identity gives a monoid; inverses give a group. The additive reduct is an abelian group, whereas the second law yields only a magma for n ≥ 2. Classifying precisely prevents the accidental import of stronger theorems.":
    "Стандартная иерархия: одна лишь замкнутость даёт магму; добавление ассоциативности даёт полугруппу; двусторонняя единица даёт моноид; обратные элементы дают группу. Аддитивное обеднение является абелевой группой, тогда как второй закон при n ≥ 2 даёт лишь магму. Точная классификация не позволяет по ошибке перенести сюда более сильные теоремы.",
  "The subgroup of elements fixing a given point. Stabilisers of points in one orbit are conjugate, and by orbit–stabiliser the index of the stabiliser equals the orbit length. The element P_0 has full stabiliser, since every automorphism of the expansion fixes the named constant.":
    "Подгруппа элементов, оставляющих данную точку неподвижной. Стабилизаторы точек одной орбиты сопряжены, а по теореме об орбите и стабилизаторе индекс стабилизатора равен длине орбиты. У элемента P_0 стабилизатор полон, поскольку всякий автоморфизм обогащения оставляет именованную константу неподвижной.",
  "Universal algebra": "Универсальная алгебра",
};

export const termAcademicZh: TranslationDictionary = {
  "What the word means in mathematics, before it means anything here.":
    "在这个词对本站有任何含义之前，它在数学中意味着什么。",
  "A bijection of the carrier onto itself that commutes with every operation. The automorphisms form a group under composition. For the full expansion the group is isomorphic to the unit group U(n) = (Z/nZ)^×, acting by multiplication of indices; the constant P_0 is fixed by every element, which is what rules out the additive translations.":
    "载体集到自身的双射，且与签名中每个运算可交换。全体自同构在复合下构成群。对完整的扩充结构，该群同构于单位群 U(n) = (Z/nZ)^×，其作用为指标的乘法；常元 P_0 被每个自同构固定，这正是排除加法平移的原因。",
  "A derived statement, not a further axiom: it follows from P_0 being a left zero that any left-normed term whose leftmost leaf is P_0 evaluates to P_0 regardless of the remaining operands. The rule is stated separately only because it is the form in which the fact is used.":
    "这是一条可推出的命题，而不是额外的公理：由 P_0 是左零元可知，任何最左叶为 P_0 的左规范项，其值都是 P_0，与其余操作数无关。之所以单列，只因实际使用时正是这个形式。",
  "A description of a software release, not a mathematical statement. The counts are cardinalities of declared finite sets fixed by the release contract, and they are reported for auditability. No theorem in this glossary depends on any of them.":
    "这是对一个软件发布版的描述，不是数学命题。这些数字是发布契约固定下来的、已声明有限集合的基数，公布它们是为了可核查。本词汇表中没有任何定理依赖于它们。",
  "A homomorphism from a group into the symmetric group of a set. Here Aut(Q_n) acts on Q_n and, diagonally, on ordered pairs. The orbit–stabiliser theorem then gives |G| = |Orb(x)| · |Stab(x)| for every x, which is the identity all orbit counts on this site reduce to.":
    "从一个群到某集合的对称群的同态。这里 Aut(Q_n) 作用在 Q_n 上，并对角地作用在有序对上。轨道–稳定子定理给出：对任意 x 有 |G| = |Orb(x)| · |Stab(x)|——本站所有轨道计数都归结为这个恒等式。",
  "A homomorphism from a structure to itself. Endomorphisms form a monoid under composition, and the automorphisms are exactly its invertible elements. An endomorphism need not be injective, so it may collapse distinct elements while still preserving both laws.":
    "从一个结构到它自身的同态。全体自同态在复合下构成幺半群，而自同构恰是其中的可逆元。自同态不必是单射，因此它可以在保持两条法则的同时把不同的元素合并起来。",
  "A homomorphism from the additive group into the multiplicative group of the complex numbers. The characters of a finite abelian group form a dual group of the same order, and orthogonality of characters supplies a second, independent route to counts obtained combinatorially.":
    "从加法群到复数乘法群的同态。有限交换群的全体特征标构成一个同阶的对偶群，而特征标的正交关系为组合方法所得的计数提供了第二条独立的求证路径。",
  "A map from the Cartesian square of the carrier into the carrier, hence total and single-valued by definition. Totality is what makes the Cayley table complete, and single-valuedness is what makes the entry at a given row and column unique. Both laws of the signature are binary operations in exactly this sense.":
    "从载体集的笛卡尔平方到载体集的映射，因而按定义处处有定义且单值。处处有定义使凯莱表完整，单值性使给定行列处的取值唯一。签名中的两条法则正是这个意义上的二元运算。",
  "A map preserving every operation of the signature. Composites of homomorphisms are homomorphisms, and the image of a homomorphism is a closed subset of the codomain. Preservation is required for all laws simultaneously; a map preserving ⊕ but not ★ is not a homomorphism of the expansion.":
    "保持签名中每一个运算的映射。同态的复合仍是同态，同态的像是陪域的一个封闭子集。保持性必须对所有法则同时成立：一个保持 ⊕ 却不保持 ★ 的映射，不是该扩充结构的同态。",
  "A project name for a binary operation obtained from ⊕_n by overriding the row indexed 0. The resulting structure (Q_n, ★_n) is a magma which for n ≥ 2 is neither associative nor commutative and possesses no two-sided identity; it is the deviation from the group law that carries all of the asymmetry the project relies on.":
    "这是对一个二元运算的项目命名：它由 ⊕_n 改写指标为 0 的那一行而得。所得结构 (Q_n, ★_n) 是一个原群，当 n ≥ 2 时既不结合也不交换，且没有双边单位元；正是这一处偏离群律，承载了本项目所依赖的全部不对称性。",
  "A project name for an element of the carrier. The label P_i is in bijective correspondence with the residue class i modulo n, so the labelling carries no order, magnitude, or metric: P_2 is not a larger object than P_1, and no expression on this site treats it as one.":
    "这是对载体集中一个元素的项目命名。标签 P_i 与模 n 的剩余类 i 一一对应，因此这套标号不携带序、大小或度量：P_2 并不是比 P_1 更大的对象，本站也没有任何表达式把它当作更大的对象。",
  "A project name for the group operation of the cyclic group Z/nZ transported onto Q_n along the labelling. The reduct (Q_n, ⊕_n) is therefore an abelian group of order n generated by P_1, and every group-theoretic statement about cyclic groups applies to it verbatim.":
    "这是对循环群 Z/nZ 的群运算沿标号搬到 Q_n 上之后的项目命名。因此约化结构 (Q_n, ⊕_n) 是由 P_1 生成的 n 阶交换群，关于循环群的每一条群论结论都逐字适用于它。",
  "A project name for the index n of the family, equivalently for the order of the carrier. The seven levels form a family of algebras rather than a chain of subalgebras: an inclusion between two of them exists only when the associated structure-preserving map does, which is a separate question settled by divisibility.":
    "这是对这一族的指标 n 的项目命名，等价地就是载体集的阶。七个层级构成的是一族代数，而不是一条子代数链：其中一个嵌入另一个，仅当相应的保结构映射存在时才成立，而那是由整除性单独决定的问题。",
  "A project name for the left argument of the operation in the intended reading of a step. Mathematically it is simply the first coordinate of the ordered pair; the name records the operational role the project assigns to it and carries no additional algebraic content.":
    "这是在“一步”的既定读法下，对该运算左侧参数的项目命名。在数学上它不过是有序对的第一个坐标；这个名字记录的是项目赋予它的操作角色，并不携带额外的代数内容。",
  "A project name for the right argument and, by extension, for the value of the operation on the pair. The distinction between the two argument positions is not algebraic — both are elements of Q_n — but it is recorded, because the operations are non-commutative and the ordered pair is therefore not recoverable from the unordered one.":
    "这是对右侧参数的项目命名，并引申指该运算在这一对上的取值。两个参数位置之间的区别并非代数性的——它们都是 Q_n 的元素——但仍被记录下来，因为这些运算不交换，有序对无法由无序对复原。",
  "A project-defined index consisting of a level, a law, an operand-role tag, and an ordered pair. It is not an algebraic invariant: two distinct typed coordinates may evaluate to the same element of Q_n. Counting typed coordinates therefore counts labelled records, not equivalence classes of behaviour.":
    "这是项目定义的一个指标，由层级、法则、操作数角色标记与一个有序对组成。它不是代数不变量：两个不同的类型化坐标可以取到 Q_n 中同一个元素。因此，数类型化坐标数的是带标记的记录，而不是行为的等价类。",
  "A publication convention marking the limit of an asserted claim. In logical terms it is the explicit restriction of a quantifier: assertions are made over a stated domain, and nothing is asserted outside it. The convention exists because unrestricted readings of restricted results are the project's main misuse risk.":
    "这是一项出版约定，用来标明所主张内容的界限。用逻辑的话说，它就是对量词的显式限制：断言是在一个写明的域上作出的，域外不作任何断言。之所以有这项约定，是因为把受限结果作无限制的解读，正是本项目被误用的主要风险。",
  "A reduct is obtained by deleting operations from the signature while keeping the carrier; an expansion is the converse. Truth is not preserved upwards: a sentence valid in the reduct need not be valid in the expansion, because the expansion admits terms the reduct cannot form. Every result on this site therefore names the signature it was proved over.":
    "约化是在保留载体集的前提下从签名中删去运算所得；扩充则相反。真值不会向上传递：在约化结构中成立的语句，未必在扩充结构中成立，因为扩充允许构造约化所不能构造的项。因此本站的每一条结论都写明它是在哪个签名上证明的。",
  "A separation of three distinct kinds of assertion: theorems about the algebras, verified properties of a running implementation, and specified but unimplemented architecture. None entails another. Conflating them is a category error, and the site is organised to make the error visible rather than convenient.":
    "这是对三类不同断言的区分：关于代数结构的定理、对运行中实现已验证的性质，以及已规定但尚未实现的架构。它们之间没有任何一方蕴涵另一方。把它们混为一谈是一种范畴错误，而本站的编排就是要让这种错误显眼，而不是让它方便。",
  "A signature is a set of operation symbols with declared arities; a constant is an operation of arity zero. The signature fixes which terms are well formed and therefore which statements are expressible at all. Naming P_0 as a constant is what makes it available to automorphism conditions.":
    "签名是一组带有声明元数的运算符号；常元就是元数为零的运算。签名决定了哪些项是良构的，从而决定了哪些命题根本可被表述。正是把 P_0 声明为常元，才使它进入自同构条件的约束范围。",
  "A subset closed under all operations of the signature; equivalently, the carrier of a subalgebra. Closed subsets form a lattice under intersection, and the closure of a set is the least closed subset containing it. For ⊕_n the closed subsets are exactly the subgroups, one for each divisor of n.":
    "对签名中所有运算封闭的子集；等价地说，就是某个子代数的载体集。封闭子集在交下构成格，而一个集合的闭包是包含它的最小封闭子集。对 ⊕_n 而言，封闭子集恰好就是各个子群，n 的每个因子对应一个。",
  "A torsor over a group is a set with a free and transitive action but no preferred base point; the holomorph is the semidirect product of the group with its automorphism group. The additive reduct is a torsor under translation, and naming the constant P_0 in the signature is exactly what selects a base point and reduces the symmetry group.":
    "群上的挠子是一个带有自由传递作用、却没有指定基点的集合；全形则是该群与其自同构群的半直积。加法约化结构在平移下是一个挠子，而正是在签名中给出常元 P_0，才挑出了一个基点并缩小了对称群。",
  "A two-sided identity is neutral from both sides, and it is unique whenever it exists: two identities e and e′ satisfy e = e ∘ e′ = e′. P_0 is a two-sided identity for ⊕_n; for ★_n it is right neutral only, so ★_n has no identity for n ≥ 2.":
    "双边单位元从两侧都是中性的，而且只要存在就唯一：两个单位元 e 与 e′ 满足 e = e ∘ e′ = e′。元素 P_0 是 ⊕_n 的双边单位元；对 ★_n 它只是右中性元，因此当 n ≥ 2 时 ★_n 没有单位元。",
  "A universally quantified identity in the two arguments. It holds for ⊕_n, so the additive reduct is abelian, and fails for ★_n at every level n ≥ 2. Failure is what makes the ordered pair, rather than the unordered pair, the correct index of a step.":
    "一条对两个参数都全称量化的恒等式。它对 ⊕_n 成立，故加法约化结构是交换的；而在每个 n ≥ 2 的层上对 ★_n 不成立。正是这种不成立，使有序对而非无序对成为一步的正确指标。",
  "A universally quantified identity. Where it holds, bracketing may be omitted and the generalised associative law licenses any parenthesisation of a product. It holds for ⊕_n and fails for ★_n, so bracket structure is semantically significant in the expansion.":
    "一条全称量化的恒等式。凡它成立之处，括号可以省略，而广义结合律允许乘积取任意的加括号方式。它对 ⊕_n 成立、对 ★_n 不成立，因此在扩充结构中括号结构是有语义意义的。",
  "A worked application of the orbit-counting lemma to the diagonal action of Aut on ordered pairs at level three. The automorphism group has order two, the identity fixes all nine pairs and the involution fixes one, so the number of orbits is five. Restoring the four role tags multiplies this to twenty.":
    "这是把轨道计数引理用到第三层上 Aut 对有序对的对角作用的一次完整演算。自同构群的阶为二：恒等映射固定全部九个有序对，对合固定一个，因此轨道数为五。把四个角色标记恢复回来，这个数就乘成二十。",
  "An element e is right neutral when x ∘ e = x for every x. For ★_n the element P_0 is right neutral and simultaneously a left zero, so it is not a two-sided identity for n ≥ 2 — the two one-sided conditions are satisfied by the same element in opposite directions, which is precisely why the structure is not a monoid.":
    "若对一切 x 都有 x ∘ e = x，则称 e 为右中性元。对 ★_n 而言，P_0 既是右中性元又是左零元，因此当 n ≥ 2 时它不是双边单位元：两个单侧条件由同一个元素在相反方向上满足，这正是该结构不构成幺半群的原因。",
  "An element z is a left zero (left absorbing element) when z ∘ y = z for every y in the carrier. For n ≥ 2 the element P_0 is the unique left zero of ★_n, and ⊕_n has none. Uniqueness follows immediately: two left zeros z and z′ satisfy z = z ∘ z′ = z′.":
    "若对载体集中一切 y 都有 z ∘ y = z，则称 z 为左零元（左吸收元）。当 n ≥ 2 时，P_0 是 ★_n 的唯一左零元，而 ⊕_n 没有左零元。唯一性立刻可得：两个左零元 z 与 z′ 满足 z = z ∘ z′ = z′。",
  "An elementary enumeration of the labelled index set defined above: the number of ordered pairs summed over the family, multiplied by the number of laws and of role tags. The figure is a cardinality of a syntactic set. It bounds no complexity measure and expresses no capability claim.":
    "这是对上面所定义的带标记指标集合的一次初等计数：把有序对的个数在整族上求和，再乘以法则数与角色标记数。这个数字是一个句法集合的基数。它不给出任何复杂度界，也不表达任何关于能力的主张。",
  "An engineering artefact rather than a mathematical object: a record sufficient to reproduce a bounded execution. It has no algebraic content, and no theorem on this site depends on it. It is listed among the concepts because the project's evidence claims are stated in terms of it.":
    "这是一件工程制品，而不是数学对象：一份足以复现一次受限执行的记录。它没有代数内容，本站也没有任何定理依赖于它。之所以列入概念表，是因为本项目的证据性主张是用它的语汇表述的。",
  "An equivalence relation compatible with every operation of the signature. Congruences are exactly the kernels of homomorphisms, and the quotient Q_n/θ carries a well-defined induced structure. The congruence lattice of the full expansion is trivial for n prime, which is why coarsening the state is not generally available.":
    "与签名中每个运算相容的等价关系。同余关系恰好就是同态的核，而商代数 Q_n/θ 带有良定义的诱导结构。当 n 为素数时，完整扩充结构的同余格是平凡的——这正是一般情况下无法对状态作粗化的原因。",
  "An equivalence relation partitions its domain, and the quotient is the set of classes. A quotient of an algebra carries a well-defined induced structure exactly when the relation is a congruence; without that compatibility the coarser view is a set-level construction only and proves nothing about the operations.":
    "等价关系把它的定义域划分开来，而商集就是这些类构成的集合。代数的商带有良定义的诱导结构，当且仅当该关系是同余关系；没有这种相容性，更粗的视图就只是集合层面的构造，对运算什么也证明不了。",
  "An injective homomorphism, equivalently an isomorphism onto a subalgebra of the codomain. For the additive reducts this is Lagrange's criterion for cyclic groups: a copy of Z/mZ sits inside Z/nZ exactly when m divides n, and the subgroup realising it is unique.":
    "单射同态，等价地说，就是到陪域某个子代数上的同构。对加法约化结构而言，这就是循环群的拉格朗日判据：Z/mZ 的一份副本落在 Z/nZ 内部，当且仅当 m 整除 n，而实现它的子群是唯一的。",
  "An operation is associative when (x ∘ y) ∘ z = x ∘ (y ∘ z) holds identically. A single counterexample refutes the identity, and the triple displayed above supplies one at every level n ≥ 2. Consequently (Q_n, ★_n) is a magma and not a semigroup, and no theorem requiring associativity may be invoked for it.":
    "若恒等式 (x ∘ y) ∘ z = x ∘ (y ∘ z) 处处成立，则称该运算结合。一个反例就足以推翻这条恒等式，而上面给出的三元组在每个 n ≥ 2 的层上都提供了一个。因此 (Q_n, ★_n) 是原群而非半群，任何需要结合律的定理都不能对它援引。",
  Combinatorics: "组合数学",
  "Congruence modulo n is the equivalence relation on Z whose classes are the residues 0, …, n−1. The quotient ring Z/nZ inherits a well-defined addition, and it is that addition which the first law realises. Finiteness of Q_n is a consequence of passing to the quotient, not an additional stipulation.":
    "模 n 同余是 Z 上的一个等价关系，其类恰是剩余 0, …, n−1。商环 Z/nZ 继承了良定义的加法，而第一条法则实现的正是这个加法。Q_n 的有限性是取商的结果，而不是另加的规定。",
  "For a self-map of a finite set, the rank is the cardinality of its image. Fixing the left argument of a law yields such a map, and its rank measures how many elements remain distinguishable after one application. Rank is non-increasing under composition, which is the precise sense in which information can only be lost.":
    "对一个有限集到自身的映射，秩就是其像的基数。固定法则的左参数便得到这样一个映射，它的秩衡量的是一次作用之后还有多少元素保持可区分。秩在复合下不增——这正是“信息只会丢失”的精确含义。",
  "For an odd prime p, the non-zero squares form an index-two subgroup of the unit group, and multiplication by a fixed residue either preserves or interchanges the two cosets according to the Legendre symbol. The block structure of the action follows, and it is a property of the modulus rather than of any design decision.":
    "对奇素数 p，非零平方元构成单位群中指数为二的子群；用一个固定剩余作乘法，或者保持这两个陪集，或者互换它们，取决于勒让德符号的取值。作用的分块结构由此而来：它是模数本身的性质，而非任何设计决定的产物。",
  "Group theory": "群论",
  "In a group every element has a unique inverse, and a generator is an element whose cyclic subgroup is the whole group. Q_n under ⊕_n is generated by P_1, so the additive reduct is cyclic and reachability of one element from another is never an obstruction.":
    "在群中每个元素都有唯一的逆元；生成元是指其所生成的循环子群等于整个群的元素。Q_n 在 ⊕_n 之下由 P_1 生成，因此加法约化是循环群，从一个元素到达另一个元素永远不构成障碍。",
  "Isomorphism is a bijective homomorphism and is strictly weaker than identity of objects: isomorphic structures satisfy the same sentences of the signature while remaining distinct as sets. Reporting an isomorphism as an equality would overstate the result, so the site uses the word only in its exact sense.":
    "同构是双射同态，它严格弱于对象的相等：同构的结构满足签名中相同的语句，但作为集合仍然彼此不同。把同构说成相等会夸大所得的结论，因此本站只在其精确含义下使用这个词。",
  "Number theory": "数论",
  "Project convention": "项目约定",
  "Project term, not standard mathematics": "项目术语，非标准数学术语",
  "Sets, maps, and relations": "集合、映射与关系",
  "Standard term, narrowed to this setting": "标准术语，在此语境中作了限定",
  "Standard term, standard meaning": "标准术语，标准含义",
  "Standing of the word": "该术语的地位",
  "Summation over the fibres of a map. Since the fibres of a function partition its domain, a total computed fibrewise is exact and admits decomposition back into its parts. Aggregates published on this site are computed this way so that any total can be audited against its summands.":
    "沿映射的纤维求和。由于函数的诸纤维构成其定义域的一个划分，逐纤维计算得到的总量是精确的，并且可以重新分解回各个分量。本站发布的汇总量都按此方式计算，使任何总数都能对照其被加项加以核验。",
  "THE DEFINITION AS A MATHEMATICIAN WOULD STATE IT": "数学家会怎样陈述这个定义",
  "The Catalan numbers count the parenthesisations of a sequence of k+1 operands, equivalently the binary trees with k internal nodes. Because the second law is non-associative, distinct parenthesisations may denote distinct values, so this count bounds the number of syntactically distinct terms of a given length.":
    "卡特兰数计数的是 k+1 个运算对象的加括号方式，等价地即含 k 个内部结点的二叉树的个数。由于第二条运算律不满足结合律，不同的加括号方式可能表示不同的值，因此这个数给出了给定长度下语法上互异的项的个数上界。",
  "The Chinese remainder theorem gives a ring isomorphism whenever the moduli are coprime, so composite levels decompose as direct products while prime levels are indecomposable. The distinction is a hard limit on what a single level can express and is not affected by any choice made in the project.":
    "当诸模两两互素时，中国剩余定理给出一个环同构，因此合数层可分解为直积，而素数层不可分解。这一区分是单个层级表达能力的硬性界限，不受项目中任何选择的影响。",
  "The affine group of Z/nZ, equal to the holomorph of the cyclic group, acts on the additive reduct by structure-preserving maps. Adjoining the constant P_0 to the signature forces v = 0, so the automorphism group of the expansion is the point stabiliser U(n) rather than the full affine group.":
    "Z/nZ 的仿射群，等于该循环群的全形，通过保结构映射作用在加法约化上。把常量 P_0 加入签名会迫使 v = 0，因此扩充结构的自同构群是点稳定子 U(n)，而不是整个仿射群。",
  "The carrier (underlying set) of an algebraic structure is the set on which its operations are defined. Here it is the finite set Q_n of cardinality n, indexed by the residues 0 through n−1. An algebra is the pair (Q_n, {⊕_n, ★_n}); statements about the algebra are statements about that pair, never about the carrier alone.":
    "代数结构的载体集（基础集）是其运算所定义于其上的那个集合。此处它是基数为 n 的有限集 Q_n，由剩余 0 到 n−1 编号。所谓代数即是序对 (Q_n, {⊕_n, ★_n})；关于该代数的陈述是关于这个序对的陈述，绝不是关于载体集本身的陈述。",
  "The constant map onto the named element. It preserves both laws trivially, hence Hom(Q_m, Q_n) is non-empty for every ordered pair of levels. Consequently the statement that two levels admit no homomorphism is false in general; the substantive question is whether a non-constant one exists.":
    "取值恒为指定元素的常值映射。它平凡地保持两条运算律，因此对任意有序的层级对，Hom(Q_m, Q_n) 都非空。于是「两个层级之间不存在同态」这一说法一般而言是错误的；有实质意义的问题是：是否存在非常值的同态。",
  "The equivalence class of an integer under congruence modulo n. The classes partition Z and inherit well-defined addition and multiplication, making Z/nZ a commutative ring. Elements of the carrier are identified with these classes, which is what makes the wrap-around an identity rather than a truncation.":
    "整数在模 n 同余关系下的等价类。这些类构成 Z 的一个划分，并继承了良定义的加法与乘法，从而使 Z/nZ 成为交换环。载体集的元素正是与这些类相认同的，这也正是「绕回」是一条恒等式而非一次截断的原因。",
  "The formation of terms by substituting the value of one operation into an argument of another. Since ★_n is non-associative, distinct parse trees over the same operand sequence may denote distinct elements, and a term is therefore individuated by its tree rather than by its leaves.":
    "把一个运算的值代入另一个运算的某个变元位置，由此构成项。由于 ★_n 不满足结合律，同一运算对象序列上不同的语法树可能表示不同的元素，因此一个项是由它的树而非由它的叶子来标定的。",
  "The maps obtained by fixing one argument. In a group both are bijections, which is the content of Cayley's theorem for the additive reduct. For the second law the left translation by P_0 is constant, so it is not injective and the corresponding row of the table degenerates.":
    "固定其中一个变元所得到的映射。在群中二者都是双射，这正是加法约化上凯莱定理的内容。对第二条运算律而言，由 P_0 给出的左平移是常值映射，因而不是单射，表中相应的一行随之退化。",
  "The multiplication table of a finite magma: the n × n array whose (i, j) entry is the value of the operation on the ordered pair (P_i, P_j). Because the operation is total and the carrier is finite, the table determines the structure completely, and any property expressible in the signature can in principle be decided by exhaustive inspection of n² entries.":
    "有限原群的乘法表：一个 n × n 的阵列，其 (i, j) 位置的元素是该运算作用在有序对 (P_i, P_j) 上的值。由于运算处处有定义且载体集有限，此表完全决定了整个结构，凡是能用签名表述的性质，原则上都可以通过穷举检视 n² 个表元来判定。",
  "The multiplicative group of residues coprime to n, of order given by Euler's totient function. Since Aut of the expansion is isomorphic to U(n), the totient counts the structure-preserving relabellings available at each level, and it is maximal relative to n precisely when n is prime.":
    "与 n 互素的剩余在乘法下构成的群，其阶由欧拉函数给出。由于扩充结构的自同构群同构于 U(n)，欧拉函数所计数的正是每一层上可用的保结构重新标号的数目；相对于 n 而言，它恰在 n 为素数时取到最大值。",
  "The notation table, understood as a declared object language: a finite list of symbols together with their intended readings. It is stated once so that every page can be read without appeal to an external convention, and it is closed — a symbol absent from the legend does not occur in the published text. Closure is what makes a claim on this site checkable without having to guess what a mark was meant to denote.":
    "记号表，可理解为一套声明在先的对象语言：一个有限的符号清单及其约定的读法。它只陈述一次，使每一页都能在不诉诸外部约定的情况下被读懂；并且它是封闭的——凡未列入记号表的符号，都不会出现在已发布的正文中。正是这种封闭性，使本站上的任何断言都无需猜测某个记号究竟指什么就可以核验。",
  "The orbit structure induced by the order-two automorphism given by index negation, which exists for every n ≥ 3. Its orbits have length two except at the fixed points of the involution, namely P_0 and, when n is even, the element of index n/2.":
    "由二阶自同构——指标取负——所诱导的轨道结构；该自同构对每个 n ≥ 3 都存在。除这个对合的不动点外，其轨道长度均为二；不动点即 P_0，以及当 n 为偶数时指标为 n/2 的那个元素。",
  "The orbit-counting lemma, a corollary of orbit–stabiliser obtained by double counting the set of pairs (g, x) with g · x = x. It converts an orbit count into an average of fixed-point counts, which is the form in which the counts published here are computed and can be independently recomputed.":
    "轨道计数引理（伯恩赛德引理）是轨道–稳定子定理的推论，由对满足 g · x = x 的序对集合 (g, x) 作双重计数而得。它把轨道数的计算化为不动点个数的平均值，本站所发布的计数正是按这一形式算出的，因而可以被独立地重新核算。",
  "The order of an element is the least positive k with k copies of it summing to the identity. By Lagrange it divides the group order, and in the cyclic group of order n the element of index i has order n/gcd(i, n). Generators are exactly the indices coprime to n.":
    "元素的阶是使其 k 个副本之和等于单位元的最小正整数 k。由拉格朗日定理，它整除群的阶；在 n 阶循环群中，指标为 i 的元素其阶为 n/gcd(i, n)。生成元恰好就是那些与 n 互素的指标。",
  "The requirement that the operation not leave the carrier — already implied by writing it as a map into Q_n. Closure over a finite carrier is what makes exhaustive verification a terminating procedure rather than an unbounded search.":
    "要求运算不把结果带出载体集之外——把它写成取值于 Q_n 的映射时，这一点其实已经蕴含在内。正是有限载体集上的封闭性，使穷举验证成为一个必定终止的过程，而不是一场无界的搜索。",
  "The set of images of a point under the whole group. Orbits are the classes of an equivalence relation and therefore partition the set acted upon. Two elements in the same orbit are indistinguishable by any property invariant under the action, so orbits — not labels — are the correct objects to enumerate.":
    "一个点在整个群作用下的像的集合。轨道是某个等价关系的等价类，因而构成被作用集合的一个划分。同一轨道中的两个元素，用任何在该作用下不变的性质都无法区分，所以应当枚举的是轨道而不是标签。",
  "The set of values actually attained. A map is surjective exactly when its image is the whole codomain, and for maps of a finite set into itself injectivity, surjectivity, and bijectivity coincide — which is why a non-injective translation is immediately detectable as a shrinking image.":
    "实际被取到的那些值构成的集合。一个映射是满射，当且仅当其像等于整个陪域；而对有限集到自身的映射，单射、满射与双射三者等价——这正是非单的平移可以立刻通过像的缩小而被察觉的原因。",
  "The standard classification of maps. On a finite set of fixed cardinality the three notions collapse: a self-map is injective if and only if it is surjective if and only if it is bijective. Automorphisms must be bijections, since a non-injective relabelling would identify two distinct elements.":
    "映射的标准分类。在基数固定的有限集上，这三个概念是重合的：集合到自身的映射是单射当且仅当它是满射，当且仅当它是双射。自同构必须是双射，因为非单的重新标号会把两个不同的元素等同起来。",
  "The standard hierarchy: closure alone gives a magma; adding associativity gives a semigroup; a two-sided identity gives a monoid; inverses give a group. The additive reduct is an abelian group, whereas the second law yields only a magma for n ≥ 2. Classifying precisely prevents the accidental import of stronger theorems.":
    "标准的层级：仅有封闭性给出原群；再加上结合律给出半群；再有双边单位元给出幺半群；再有逆元给出群。加法约化是阿贝尔群，而第二条运算律在 n ≥ 2 时只给出原群。精确的分类可以防止把更强的定理误引到这里。",
  "The subgroup of elements fixing a given point. Stabilisers of points in one orbit are conjugate, and by orbit–stabiliser the index of the stabiliser equals the orbit length. The element P_0 has full stabiliser, since every automorphism of the expansion fixes the named constant.":
    "使给定点保持不动的那些元素构成的子群。同一轨道中各点的稳定子彼此共轭，而由轨道–稳定子定理，稳定子的指数等于轨道的长度。元素 P_0 的稳定子是整个群，因为扩充结构的每一个自同构都保持这个具名常量不动。",
  "Universal algebra": "泛代数",
};

export const termAcademicAr: TranslationDictionary = {
  "What the word means in mathematics, before it means anything here.":
    "ما الذي يعنيه هذا اللفظ في الرياضيات، قبل أن يعني شيئًا هنا.",
  "A bijection of the carrier onto itself that commutes with every operation. The automorphisms form a group under composition. For the full expansion the group is isomorphic to the unit group U(n) = (Z/nZ)^×, acting by multiplication of indices; the constant P_0 is fixed by every element, which is what rules out the additive translations.":
    "تقابل من المجموعة الحاملة إلى نفسها يبادل كل عملية في التوقيع. وتشكّل التشاكلات الذاتية زمرة تحت التركيب. وبالنسبة للتوسيع الكامل تكون هذه الزمرة متماثلة مع زمرة الوحدات ‎U(n) = (Z/nZ)^×‎ بفعل ضرب الأدلة؛ والثابت P_0 صامد تحت كل عنصر، وهذا ما يستبعد الانسحابات الجمعية.",
  "A derived statement, not a further axiom: it follows from P_0 being a left zero that any left-normed term whose leftmost leaf is P_0 evaluates to P_0 regardless of the remaining operands. The rule is stated separately only because it is the form in which the fact is used.":
    "عبارة مستنتجة لا بديهية إضافية: من كون P_0 صفرًا أيسر يلزم أن أي حد منظوم يسارًا وطرفه الأيسر P_0 تكون قيمته P_0 مهما كانت بقية المعاملات. وقد أُفرِدت القاعدة لأن هذه هي الصيغة التي تُستعمل بها.",
  "A description of a software release, not a mathematical statement. The counts are cardinalities of declared finite sets fixed by the release contract, and they are reported for auditability. No theorem in this glossary depends on any of them.":
    "وصف لإصدار برمجي لا عبارة رياضية. والأعداد المذكورة هي مقادير مجموعات منتهية معلنة يثبّتها عقد الإصدار، وتُنشر لأغراض التدقيق. ولا تعتمد أي مبرهنة في هذا المسرد على أي منها.",
  "A homomorphism from a group into the symmetric group of a set. Here Aut(Q_n) acts on Q_n and, diagonally, on ordered pairs. The orbit–stabiliser theorem then gives |G| = |Orb(x)| · |Stab(x)| for every x, which is the identity all orbit counts on this site reduce to.":
    "تشاكل من زمرة إلى الزمرة التناظرية لمجموعة. وهنا تعمل ‎Aut(Q_n)‎ على ‎Q_n‎ وقطريًا على الأزواج المرتّبة. وتعطي مبرهنة المدار والمثبِّت ‎|G| = |Orb(x)| · |Stab(x)|‎ لكل x، وهي المتطابقة التي تُرَدّ إليها كل أعداد المدارات في هذا الموقع.",
  "A homomorphism from a structure to itself. Endomorphisms form a monoid under composition, and the automorphisms are exactly its invertible elements. An endomorphism need not be injective, so it may collapse distinct elements while still preserving both laws.":
    "تشاكل من بنية إلى نفسها. وتشكّل التشاكلات الذاتية الداخلية أحاديًا تحت التركيب، والتشاكلات الذاتية هي بالضبط عناصره القابلة للعكس. ولا يلزم أن يكون التشاكل الداخلي متباينًا، فقد يطوي عناصر مختلفة مع حفظه للقانونين.",
  "A homomorphism from the additive group into the multiplicative group of the complex numbers. The characters of a finite abelian group form a dual group of the same order, and orthogonality of characters supplies a second, independent route to counts obtained combinatorially.":
    "تشاكل من الزمرة الجمعية إلى الزمرة الضربية للأعداد المركّبة. وطوابع زمرة أبيلية منتهية تشكّل زمرة مزدوجة من الرتبة نفسها، وعلاقات تعامد الطوابع تمنح طريقًا ثانيًا مستقلًا إلى أعداد حُصّلت توافقيًا.",
  "A map from the Cartesian square of the carrier into the carrier, hence total and single-valued by definition. Totality is what makes the Cayley table complete, and single-valuedness is what makes the entry at a given row and column unique. Both laws of the signature are binary operations in exactly this sense.":
    "تطبيق من المربع الديكارتي للمجموعة الحاملة إلى المجموعة نفسها، ومن ثم فهو معرَّف كليًّا وأحادي القيمة بحكم التعريف. والتعريف الكلي هو ما يجعل جدول كايلي كاملًا، والأحادية هي ما تجعل القيمة عند صف وعمود معينين وحيدة. وقانونا التوقيع عمليتان ثنائيتان بهذا المعنى بالضبط.",
  "A map preserving every operation of the signature. Composites of homomorphisms are homomorphisms, and the image of a homomorphism is a closed subset of the codomain. Preservation is required for all laws simultaneously; a map preserving ⊕ but not ★ is not a homomorphism of the expansion.":
    "تطبيق يحفظ كل عملية في التوقيع. وتركيب التشاكلات تشاكل، وصورة التشاكل مجموعة جزئية مغلقة في المجال المقابل. والحفظ مطلوب لكل القوانين معًا؛ فالتطبيق الذي يحفظ ⊕ ولا يحفظ ★ ليس تشاكلًا للتوسيع.",
  "A project name for a binary operation obtained from ⊕_n by overriding the row indexed 0. The resulting structure (Q_n, ★_n) is a magma which for n ≥ 2 is neither associative nor commutative and possesses no two-sided identity; it is the deviation from the group law that carries all of the asymmetry the project relies on.":
    "تسمية اصطلاحية خاصة بالمشروع لعملية ثنائية تُستخرج من ‎⊕_n‎ بإعادة تعريف الصف ذي الدليل 0. والبنية الناتجة ‎(Q_n, ★_n)‎ ماغما ليست ترابطية ولا تبديلية عند ‎n ≥ 2‎ ولا محايد لها من الجهتين؛ وهذا الانحراف عن قانون الزمرة يحمل كل اللاتماثل الذي يعتمد عليه المشروع.",
  "A project name for an element of the carrier. The label P_i is in bijective correspondence with the residue class i modulo n, so the labelling carries no order, magnitude, or metric: P_2 is not a larger object than P_1, and no expression on this site treats it as one.":
    "تسمية اصطلاحية خاصة بالمشروع لعنصر من المجموعة الحاملة. والتسمية P_i في تقابل أحادي مع صف البواقي i بالمقياس n، فالتسمية لا تحمل ترتيبًا ولا مقدارًا ولا مسافة: فـP_2 ليس كائنًا أكبر من P_1، ولا تعامله أي عبارة في هذا الموقع كذلك.",
  "A project name for the group operation of the cyclic group Z/nZ transported onto Q_n along the labelling. The reduct (Q_n, ⊕_n) is therefore an abelian group of order n generated by P_1, and every group-theoretic statement about cyclic groups applies to it verbatim.":
    "تسمية اصطلاحية خاصة بالمشروع لعملية زمرة الدورية ‎Z/nZ‎ منقولةً إلى ‎Q_n‎ عبر التسمية. لذا فالاختزال ‎(Q_n, ⊕_n)‎ زمرة أبيلية من الرتبة n مولّدها P_1، وكل عبارة في نظرية الزمر عن الزمر الدورية تنطبق عليه حرفيًا.",
  "A project name for the index n of the family, equivalently for the order of the carrier. The seven levels form a family of algebras rather than a chain of subalgebras: an inclusion between two of them exists only when the associated structure-preserving map does, which is a separate question settled by divisibility.":
    "تسمية اصطلاحية خاصة بالمشروع لدليل العائلة n، أي لرتبة المجموعة الحاملة. والمستويات السبعة تشكّل عائلة جبور لا سلسلة جبور جزئية: فالغرس بين اثنين منها لا يوجد إلا بوجود التطبيق الحافظ للبنية المقابل، وتلك مسألة منفصلة تحسمها القابلية للقسمة.",
  "A project name for the left argument of the operation in the intended reading of a step. Mathematically it is simply the first coordinate of the ordered pair; the name records the operational role the project assigns to it and carries no additional algebraic content.":
    "تسمية اصطلاحية خاصة بالمشروع للمعامل الأيسر للعملية في القراءة المقصودة للخطوة. ورياضيًا هو الإحداثي الأول للزوج المرتّب فحسب؛ والاسم يسجّل الدور التشغيلي الذي يسنده المشروع إليه ولا يحمل مضمونًا جبريًا إضافيًا.",
  "A project name for the right argument and, by extension, for the value of the operation on the pair. The distinction between the two argument positions is not algebraic — both are elements of Q_n — but it is recorded, because the operations are non-commutative and the ordered pair is therefore not recoverable from the unordered one.":
    "تسمية اصطلاحية خاصة بالمشروع للمعامل الأيمن، وبالتوسّع لقيمة العملية على الزوج. والتمييز بين موضعَي المعاملين ليس جبريًا — فكلاهما عنصر في ‎Q_n‎ — لكنه يُسجَّل لأن العمليتين غير تبديليتين ولا يمكن استرجاع الزوج المرتّب من غير المرتّب.",
  "A project-defined index consisting of a level, a law, an operand-role tag, and an ordered pair. It is not an algebraic invariant: two distinct typed coordinates may evaluate to the same element of Q_n. Counting typed coordinates therefore counts labelled records, not equivalence classes of behaviour.":
    "دليل يعرّفه المشروع ويتألف من مستوى وقانون ووسم لدور المعامل وزوج مرتّب. وليس ثابتًا جبريًا: فقد يعطي إحداثيان محددا النوع مختلفان العنصر نفسه من ‎Q_n‎. لذا فعدّ هذه الإحداثيات يعدّ سجلات موسومة لا صفوف تكافؤ سلوكية.",
  "A publication convention marking the limit of an asserted claim. In logical terms it is the explicit restriction of a quantifier: assertions are made over a stated domain, and nothing is asserted outside it. The convention exists because unrestricted readings of restricted results are the project's main misuse risk.":
    "عرف نشري يعلّم حدود الادعاء المؤكَّد. ومنطقيًا هو تقييد صريح للمُسوِّر: تُطلَق التأكيدات على مجال معلن، ولا يُؤكَّد شيء خارجه. ووُجد هذا العرف لأن القراءة غير المقيَّدة لنتائج مقيَّدة هي الخطر الرئيسي لإساءة استعمال المشروع.",
  "A reduct is obtained by deleting operations from the signature while keeping the carrier; an expansion is the converse. Truth is not preserved upwards: a sentence valid in the reduct need not be valid in the expansion, because the expansion admits terms the reduct cannot form. Every result on this site therefore names the signature it was proved over.":
    "يُحصَل الاختزال بحذف عمليات من التوقيع مع إبقاء المجموعة الحاملة؛ والتوسيع عكسه. والصدق لا ينتقل صعودًا: فالعبارة الصادقة في الاختزال ليست بالضرورة صادقة في التوسيع، لأن التوسيع يقبل حدودًا لا يستطيع الاختزال تكوينها. ولهذا تذكر كل نتيجة في هذا الموقع التوقيع الذي بُرهنت عليه.",
  "A separation of three distinct kinds of assertion: theorems about the algebras, verified properties of a running implementation, and specified but unimplemented architecture. None entails another. Conflating them is a category error, and the site is organised to make the error visible rather than convenient.":
    "فصل بين ثلاثة أنواع من التأكيدات: مبرهنات عن الجبور، وخصائص متحقَّق منها لتنفيذ عامل، وبنية محدَّدة غير منفَّذة. ولا يستلزم أيٌّ منها الآخر. وخلطها خطأ في المقولة، والموقع منظَّم ليجعل الخطأ ظاهرًا لا مريحًا.",
  "A signature is a set of operation symbols with declared arities; a constant is an operation of arity zero. The signature fixes which terms are well formed and therefore which statements are expressible at all. Naming P_0 as a constant is what makes it available to automorphism conditions.":
    "التوقيع مجموعة من رموز العمليات برُتَب معلنة؛ والثابت عملية رتبتها صفر. والتوقيع يحدد أي الحدود مبنية بشكل سليم، ومن ثم أي العبارات قابلة للتعبير أصلًا. وتسمية P_0 ثابتًا هي ما يجعله متاحًا لشروط التشاكلات الذاتية.",
  "A subset closed under all operations of the signature; equivalently, the carrier of a subalgebra. Closed subsets form a lattice under intersection, and the closure of a set is the least closed subset containing it. For ⊕_n the closed subsets are exactly the subgroups, one for each divisor of n.":
    "مجموعة جزئية مغلقة تحت كل عمليات التوقيع؛ أي مكافئةً حاملُ جبر جزئي. والمجموعات المغلقة تشكّل شبكة تحت التقاطع، وانغلاق مجموعة هو أصغر مجموعة مغلقة تحتويها. وبالنسبة لـ‎⊕_n‎ فالمجموعات المغلقة هي الزمر الجزئية بالضبط، واحدة لكل قاسم من قواسم n.",
  "A torsor over a group is a set with a free and transitive action but no preferred base point; the holomorph is the semidirect product of the group with its automorphism group. The additive reduct is a torsor under translation, and naming the constant P_0 in the signature is exactly what selects a base point and reduces the symmetry group.":
    "الفضاء المتجانس الرئيسي فوق زمرة مجموعةٌ ذات فعل حر ومتعدٍّ دون نقطة مميّزة؛ والهولومورف هو الجداء شبه المباشر للزمرة مع زمرة تشاكلاتها الذاتية. والاختزال الجمعي فضاء متجانس رئيسي تحت الانسحاب، وتسمية الثابت P_0 في التوقيع هي بالضبط ما يختار نقطة أساس ويقلّص زمرة التناظر.",
  "A two-sided identity is neutral from both sides, and it is unique whenever it exists: two identities e and e′ satisfy e = e ∘ e′ = e′. P_0 is a two-sided identity for ⊕_n; for ★_n it is right neutral only, so ★_n has no identity for n ≥ 2.":
    "المحايد من الجهتين محايد من كلا الطرفين، وهو وحيد متى وُجد: فمحايدان e وe′ يحققان ‎e = e ∘ e′ = e′‎. والعنصر P_0 محايد من الجهتين لـ‎⊕_n‎؛ أما لـ‎★_n‎ فهو محايد من اليمين فقط، فلا محايد لـ‎★_n‎ عند ‎n ≥ 2‎.",
  "A universally quantified identity in the two arguments. It holds for ⊕_n, so the additive reduct is abelian, and fails for ★_n at every level n ≥ 2. Failure is what makes the ordered pair, rather than the unordered pair, the correct index of a step.":
    "متطابقة مسوَّرة كليًّا في المعاملين. تتحقق لـ‎⊕_n‎ فيكون الاختزال الجمعي أبيليًا، وتخفق لـ‎★_n‎ عند كل مستوى ‎n ≥ 2‎. والإخفاق هو ما يجعل الزوج المرتّب، لا غير المرتّب، الدليل الصحيح للخطوة.",
  "A universally quantified identity. Where it holds, bracketing may be omitted and the generalised associative law licenses any parenthesisation of a product. It holds for ⊕_n and fails for ★_n, so bracket structure is semantically significant in the expansion.":
    "متطابقة مسوَّرة كليًّا. وحيث تتحقق يجوز حذف الأقواس، ويجيز قانون الترابطية المعمَّم أي توزيع للأقواس في جداء. تتحقق لـ‎⊕_n‎ وتخفق لـ‎★_n‎، فتكون بنية الأقواس ذات دلالة في التوسيع.",
  "A worked application of the orbit-counting lemma to the diagonal action of Aut on ordered pairs at level three. The automorphism group has order two, the identity fixes all nine pairs and the involution fixes one, so the number of orbits is five. Restoring the four role tags multiplies this to twenty.":
    "تطبيق محلول للمّة عدّ المدارات على الفعل القطري لـAut على الأزواج المرتّبة عند المستوى الثالث. زمرة التشاكلات الذاتية رتبتها اثنان: المطابق يثبّت الأزواج التسعة كلها، والتقابل التبادلي يثبّت واحدًا، فيكون عدد المدارات خمسة. وإعادة أوسمة الأدوار الأربعة تضرب هذا العدد ليصير عشرين.",
  "An element e is right neutral when x ∘ e = x for every x. For ★_n the element P_0 is right neutral and simultaneously a left zero, so it is not a two-sided identity for n ≥ 2 — the two one-sided conditions are satisfied by the same element in opposite directions, which is precisely why the structure is not a monoid.":
    "يسمّى العنصر e محايدًا من اليمين إذا كان ‎x ∘ e = x‎ لكل x. وبالنسبة لـ‎★_n‎ فالعنصر P_0 محايد من اليمين وصفر أيسر في آنٍ واحد، فلا يكون محايدًا من الجهتين عند ‎n ≥ 2‎: إذ يحقق العنصر نفسه الشرطين الأحاديين في اتجاهين متعاكسين، وهذا بالضبط ما يمنع البنية من أن تكون أحاديًا.",
  "An element z is a left zero (left absorbing element) when z ∘ y = z for every y in the carrier. For n ≥ 2 the element P_0 is the unique left zero of ★_n, and ⊕_n has none. Uniqueness follows immediately: two left zeros z and z′ satisfy z = z ∘ z′ = z′.":
    "يسمّى العنصر z صفرًا أيسر (عنصرًا ماصًّا من اليسار) إذا كان ‎z ∘ y = z‎ لكل y في المجموعة الحاملة. وعند ‎n ≥ 2‎ يكون P_0 الصفر الأيسر الوحيد لـ‎★_n‎، ولا أصفار يسرى لـ‎⊕_n‎. والوحدانية تتبع مباشرة: صفران أيسران z وz′ يحققان ‎z = z ∘ z′ = z′‎.",
  "An elementary enumeration of the labelled index set defined above: the number of ordered pairs summed over the family, multiplied by the number of laws and of role tags. The figure is a cardinality of a syntactic set. It bounds no complexity measure and expresses no capability claim.":
    "تعداد أوّلي لمجموعة الأدلة الموسومة المعرَّفة أعلاه: عدد الأزواج المرتّبة مجموعًا على العائلة، مضروبًا في عدد القوانين وعدد أوسمة الأدوار. وهذا الرقم مقدار مجموعة نحوية. لا يحدّ أي مقياس تعقيد ولا يعبّر عن أي ادعاء بشأن القدرة.",
  "An engineering artefact rather than a mathematical object: a record sufficient to reproduce a bounded execution. It has no algebraic content, and no theorem on this site depends on it. It is listed among the concepts because the project's evidence claims are stated in terms of it.":
    "أثر هندسي لا كائن رياضي: سجل يكفي لإعادة إنتاج تنفيذ مقيَّد. لا مضمون جبري له، ولا تعتمد عليه أي مبرهنة في هذا الموقع. وقد أُدرج بين المفاهيم لأن ادعاءات المشروع المتعلقة بالأدلة تُصاغ بمفرداته.",
  "An equivalence relation compatible with every operation of the signature. Congruences are exactly the kernels of homomorphisms, and the quotient Q_n/θ carries a well-defined induced structure. The congruence lattice of the full expansion is trivial for n prime, which is why coarsening the state is not generally available.":
    "علاقة تكافؤ متوافقة مع كل عملية في التوقيع. وعلاقات التطابق هي بالضبط أنوية التشاكلات، ويحمل جبر القسمة ‎Q_n/θ‎ بنية مستحثّة معرَّفة جيدًا. وشبكة التطابقات للتوسيع الكامل تافهة عندما يكون n أوليًا، ولهذا لا يكون تخشين الحالة متاحًا عمومًا.",
  "An equivalence relation partitions its domain, and the quotient is the set of classes. A quotient of an algebra carries a well-defined induced structure exactly when the relation is a congruence; without that compatibility the coarser view is a set-level construction only and proves nothing about the operations.":
    "علاقة التكافؤ تجزّئ مجالها، وجبر القسمة هو مجموعة الأصناف. ويحمل خارج قسمة جبرٍ بنية مستحثّة معرَّفة جيدًا إذا وفقط إذا كانت العلاقة تطابقًا؛ ودون هذا التوافق يبقى العرض الأخشن إنشاءً على مستوى المجموعات ولا يثبت شيئًا عن العمليات.",
  "An injective homomorphism, equivalently an isomorphism onto a subalgebra of the codomain. For the additive reducts this is Lagrange's criterion for cyclic groups: a copy of Z/mZ sits inside Z/nZ exactly when m divides n, and the subgroup realising it is unique.":
    "تشاكل متباين، أي مكافئةً تماثل على جبر جزئي من المجال المقابل. وبالنسبة للاختزالات الجمعية هذا هو معيار لاغرانج للزمر الدورية: توجد نسخة من ‎Z/mZ‎ داخل ‎Z/nZ‎ إذا وفقط إذا قسم m العدد n، والزمرة الجزئية المحقِّقة لذلك وحيدة.",
  "An operation is associative when (x ∘ y) ∘ z = x ∘ (y ∘ z) holds identically. A single counterexample refutes the identity, and the triple displayed above supplies one at every level n ≥ 2. Consequently (Q_n, ★_n) is a magma and not a semigroup, and no theorem requiring associativity may be invoked for it.":
    "تكون العملية ترابطية إذا تحققت المتطابقة ‎(x ∘ y) ∘ z = x ∘ (y ∘ z)‎ على العموم. ومثال مضاد واحد يكفي لنقض المتطابقة، والثلاثية المعروضة أعلاه تقدّمه عند كل مستوى ‎n ≥ 2‎. ومن ثم فإن ‎(Q_n, ★_n)‎ ماغما لا شبه زمرة، ولا يجوز استدعاء أي مبرهنة تتطلب الترابطية من أجلها.",
  Combinatorics: "التوافقيات",
  "Congruence modulo n is the equivalence relation on Z whose classes are the residues 0, …, n−1. The quotient ring Z/nZ inherits a well-defined addition, and it is that addition which the first law realises. Finiteness of Q_n is a consequence of passing to the quotient, not an additional stipulation.":
    "التطابق بالمقياس n علاقة تكافؤ على Z أصنافها هي البواقي ‎0, …, n−1‎. ويرث حلقة القسمة ‎Z/nZ‎ جمعًا معرَّفًا جيدًا، وهذا الجمع هو ما يحققه القانون الأول. وانتهاء ‎Q_n‎ نتيجة للانتقال إلى خارج القسمة لا اشتراط إضافي.",
  "For a self-map of a finite set, the rank is the cardinality of its image. Fixing the left argument of a law yields such a map, and its rank measures how many elements remain distinguishable after one application. Rank is non-increasing under composition, which is the precise sense in which information can only be lost.":
    "بالنسبة لتطبيق من مجموعة منتهية إلى نفسها، الرتبة هي مقدار صورته. وتثبيت المعامل الأيسر لقانون يعطي تطبيقًا كهذا، ورتبته تقيس كم عنصرًا يبقى قابلًا للتمييز بعد تطبيق واحد. والرتبة غير متزايدة تحت التركيب، وهذا هو المعنى الدقيق لكون المعلومات لا تُكتسب بل تُفقَد.",
  "For an odd prime p, the non-zero squares form an index-two subgroup of the unit group, and multiplication by a fixed residue either preserves or interchanges the two cosets according to the Legendre symbol. The block structure of the action follows, and it is a property of the modulus rather than of any design decision.":
    "من أجل عدد أوّلي فردي p، تُشكِّل المربَّعات غير المعدومة زمرة جزئية دليلها اثنان داخل زمرة الوحدات، والضرب في باقٍ ثابت إمّا يحفظ الصنفين المشاركَين وإمّا يبادل بينهما تبعًا لقيمة رمز لوجاندر. ومن هنا تأتي البنية الكتلية للتأثير: فهي خاصية للمقياس نفسه لا نتيجةَ أي قرار تصميمي.",
  "Group theory": "نظرية الزمر",
  "In a group every element has a unique inverse, and a generator is an element whose cyclic subgroup is the whole group. Q_n under ⊕_n is generated by P_1, so the additive reduct is cyclic and reachability of one element from another is never an obstruction.":
    "في أي زمرة يملك كل عنصر نظيرًا وحيدًا، ويُسمّى العنصر مولِّدًا إذا كانت زمرته الجزئية الدورية هي الزمرة كلّها. المجموعة Q_n المزوَّدة بالعملية ⊕_n مولَّدة بالعنصر P_1، ومن ثمّ فإنّ الاختزال الجمعي دوري ولا يشكّل بلوغ عنصر انطلاقًا من آخر عائقًا بحال.",
  "Isomorphism is a bijective homomorphism and is strictly weaker than identity of objects: isomorphic structures satisfy the same sentences of the signature while remaining distinct as sets. Reporting an isomorphism as an equality would overstate the result, so the site uses the word only in its exact sense.":
    "التماثل هو تشاكل تقابلي، وهو أضعف تمامًا من تساوي الكائنات: البنى المتماثلة تحقّق العبارات نفسها المصوغة في التوقيع، ومع ذلك تبقى مجموعات متمايزة. والإخبار عن تماثل بوصفه مساواة مبالغةٌ في النتيجة، لذلك لا يُستعمل هذا اللفظ في الموقع إلّا بمعناه الدقيق.",
  "Number theory": "نظرية الأعداد",
  "Project convention": "اصطلاح خاص بالمشروع",
  "Project term, not standard mathematics": "مصطلح خاص بالمشروع، لا مصطلح رياضي معياري",
  "Sets, maps, and relations": "المجموعات والتطبيقات والعلاقات",
  "Standard term, narrowed to this setting": "مصطلح معياري، مضيَّق إلى هذا السياق",
  "Standard term, standard meaning": "مصطلح معياري بمعناه المعياري",
  "Standing of the word": "وضع المصطلح",
  "Summation over the fibres of a map. Since the fibres of a function partition its domain, a total computed fibrewise is exact and admits decomposition back into its parts. Aggregates published on this site are computed this way so that any total can be audited against its summands.":
    "الجمع على ألياف تطبيقٍ ما. ولمّا كانت ألياف الدالة تُجزّئ مجالها، فإنّ المجموع المحسوب ليفًا ليفًا مجموعٌ مضبوط ويقبل التفكيك رجوعًا إلى مركّباته. وتُحسب كل الحصائل المنشورة في هذا الموقع بهذه الطريقة حتى يمكن مراجعة أي مجموع في ضوء حدوده.",
  "THE DEFINITION AS A MATHEMATICIAN WOULD STATE IT": "التعريف كما يصوغه عالِم الرياضيات",
  "The Catalan numbers count the parenthesisations of a sequence of k+1 operands, equivalently the binary trees with k internal nodes. Because the second law is non-associative, distinct parenthesisations may denote distinct values, so this count bounds the number of syntactically distinct terms of a given length.":
    "تَعُدّ أعداد كاتالان أوجهَ وضع الأقواس على متتالية من k+1 معاملًا، وهي مكافئة لعدد الأشجار الثنائية ذات k عقدة داخلية. ولأنّ القانون الثاني غير تجميعي، فقد تدلّ أوجهُ وضعِ أقواسٍ مختلفة على قيم مختلفة، ومن ثمّ يَحُدّ هذا العدد عددَ الحدود المتمايزة نحويًا عند طول معطى.",
  "The Chinese remainder theorem gives a ring isomorphism whenever the moduli are coprime, so composite levels decompose as direct products while prime levels are indecomposable. The distinction is a hard limit on what a single level can express and is not affected by any choice made in the project.":
    "تمنح مبرهنة الباقي الصيني تماثلَ حلقاتٍ كلّما كانت المعاملات أوّلية فيما بينها، ولذلك تتفكّك المستويات المؤلَّفة إلى جداءات مباشرة بينما تبقى المستويات الأوّلية غير قابلة للتفكيك. وهذا التمييز حدٌّ صارم لما يستطيع مستوىً واحد التعبير عنه، ولا يتأثّر بأي اختيار اتُّخذ داخل المشروع.",
  "The affine group of Z/nZ, equal to the holomorph of the cyclic group, acts on the additive reduct by structure-preserving maps. Adjoining the constant P_0 to the signature forces v = 0, so the automorphism group of the expansion is the point stabiliser U(n) rather than the full affine group.":
    "الزمرة الأفينية للحلقة Z/nZ، وهي عينها هولومورف الزمرة الدورية، تؤثّر على الاختزال الجمعي بتطبيقات حافظة للبنية. وإدراجُ الثابت P_0 في التوقيع يفرض v = 0، ولذلك فإنّ زمرة التقابلات الذاتية للتوسيع هي مثبِّت النقطة U(n) لا الزمرةَ الأفينية بأكملها.",
  "The carrier (underlying set) of an algebraic structure is the set on which its operations are defined. Here it is the finite set Q_n of cardinality n, indexed by the residues 0 through n−1. An algebra is the pair (Q_n, {⊕_n, ★_n}); statements about the algebra are statements about that pair, never about the carrier alone.":
    "المجموعة الحاملة (المجموعة الأساسية) لبنية جبرية هي المجموعة التي تُعرَّف عليها عملياتها. وهي هنا المجموعة المنتهية Q_n ذات العدد الأصلي n، المفهرسة بالبواقي من 0 إلى n−1. ويُسمّى جبرًا الزوجُ (Q_n, {⊕_n, ★_n})؛ والعبارات المقولة عن الجبر عباراتٌ عن هذا الزوج، لا عن المجموعة الحاملة وحدها أبدًا.",
  "The constant map onto the named element. It preserves both laws trivially, hence Hom(Q_m, Q_n) is non-empty for every ordered pair of levels. Consequently the statement that two levels admit no homomorphism is false in general; the substantive question is whether a non-constant one exists.":
    "التطبيق الثابت الذي يأخذ العنصر المذكور قيمةً له. وهو يحفظ القانونين حفظًا بديهيًا، ومن ثمّ فإنّ Hom(Q_m, Q_n) ليست خالية من أجل كل زوج مرتَّب من المستويات. وعليه فالقولُ بأنّ مستويين لا يقبلان أي تشاكل قولٌ خاطئ في العموم؛ والسؤال الجوهري هو: هل يوجد تشاكل غير ثابت.",
  "The equivalence class of an integer under congruence modulo n. The classes partition Z and inherit well-defined addition and multiplication, making Z/nZ a commutative ring. Elements of the carrier are identified with these classes, which is what makes the wrap-around an identity rather than a truncation.":
    "صنف تكافؤ عددٍ صحيح تحت التطابق بالمقياس n. تُجزّئ هذه الأصنافُ المجموعةَ Z وترث جمعًا وضربًا معرَّفين تعريفًا سليمًا، فتغدو Z/nZ حلقةً تبادلية. وتُطابَق عناصر المجموعة الحاملة مع هذه الأصناف، وهذا بعينه ما يجعل الالتفافَ متطابقةً لا اقتطاعًا.",
  "The formation of terms by substituting the value of one operation into an argument of another. Since ★_n is non-associative, distinct parse trees over the same operand sequence may denote distinct elements, and a term is therefore individuated by its tree rather than by its leaves.":
    "تكوين الحدود بإحلال قيمة عملية في موضع وسيطٍ لعملية أخرى. ولأنّ ★_n غير تجميعية، فقد تدلّ أشجارُ تحليلٍ مختلفة فوق المتتالية نفسها من المعاملات على عناصر مختلفة، ومن ثمّ يتعيّن الحدُّ بشجرته لا بأوراقه.",
  "The maps obtained by fixing one argument. In a group both are bijections, which is the content of Cayley's theorem for the additive reduct. For the second law the left translation by P_0 is constant, so it is not injective and the corresponding row of the table degenerates.":
    "التطبيقات الناتجة عن تثبيت أحد الوسيطين. في أي زمرة يكون كلاهما تقابلًا، وهذا هو مضمون مبرهنة كايلي في حالة الاختزال الجمعي. أمّا في القانون الثاني فالانسحاب الأيسر بالعنصر P_0 ثابتٌ، ومن ثمّ فهو غير متباين، فينحلّ السطر الموافق له في الجدول.",
  "The multiplication table of a finite magma: the n × n array whose (i, j) entry is the value of the operation on the ordered pair (P_i, P_j). Because the operation is total and the carrier is finite, the table determines the structure completely, and any property expressible in the signature can in principle be decided by exhaustive inspection of n² entries.":
    "جدول الضرب لماغما منتهية: مصفوفة من الرتبة n × n عنصرُها الواقع في الموضع (i, j) هو قيمة العملية عند الزوج المرتَّب (P_i, P_j). ولمّا كانت العملية معرَّفة في كل موضع والمجموعة الحاملة منتهية، فإنّ الجدول يحدّد البنية تحديدًا تامًّا، وكلّ خاصية قابلة للصياغة في التوقيع قابلة من حيث المبدأ للبتّ فيها بفحصٍ شاملٍ للخلايا n².",
  "The multiplicative group of residues coprime to n, of order given by Euler's totient function. Since Aut of the expansion is isomorphic to U(n), the totient counts the structure-preserving relabellings available at each level, and it is maximal relative to n precisely when n is prime.":
    "زمرة الضرب المؤلَّفة من البواقي الأوّلية مع n، ورتبتها معطاة بدالة أويلر. ولمّا كانت زمرة التقابلات الذاتية للتوسيع متماثلة مع U(n)، فإنّ دالة أويلر تَعُدّ إعاداتِ التسمية الحافظة للبنية المتاحة عند كل مستوى، وهي أعظم ما تكون نسبةً إلى n عندما يكون n أوّليًا بالضبط.",
  "The notation table, understood as a declared object language: a finite list of symbols together with their intended readings. It is stated once so that every page can be read without appeal to an external convention, and it is closed — a symbol absent from the legend does not occur in the published text. Closure is what makes a claim on this site checkable without having to guess what a mark was meant to denote.":
    "جدول الرموز، مفهومًا بوصفه لغة موضوع مُعلَنة: قائمة منتهية من الرموز مع قراءاتها المقصودة. يُذكر مرّة واحدة كي تُقرأ كل صفحة دون الرجوع إلى اصطلاح خارجي، وهو مُغلَق — فأيّ رمز لا يرد في الجدول لا يظهر في النص المنشور. وهذا الإغلاق هو ما يجعل أي ادّعاء في هذا الموقع قابلًا للتحقق دون تخمين ما الذي أُريد للعلامة أن تدلّ عليه.",
  "The orbit structure induced by the order-two automorphism given by index negation, which exists for every n ≥ 3. Its orbits have length two except at the fixed points of the involution, namely P_0 and, when n is even, the element of index n/2.":
    "بنية المدارات التي يولّدها التقابل الذاتي من الرتبة اثنين، أي نفيُ الدليل، وهو موجود من أجل كل n ≥ 3. طول مداراته اثنان إلّا عند النقاط الصامدة لهذا التقابل من الرتبة اثنين، وهي P_0 والعنصر ذو الدليل n/2 عندما يكون n زوجيًا.",
  "The orbit-counting lemma, a corollary of orbit–stabiliser obtained by double counting the set of pairs (g, x) with g · x = x. It converts an orbit count into an average of fixed-point counts, which is the form in which the counts published here are computed and can be independently recomputed.":
    "لمّة عدّ المدارات (لمّة برنسايد) نتيجةٌ لمبرهنة المدار والمثبِّت، تُستخرج بالعدّ المزدوج لمجموعة الأزواج (g, x) التي تحقّق g · x = x. وهي تُحيل عدّ المدارات إلى متوسط أعداد النقاط الصامدة، وبهذه الصيغة بعينها تُحسب الأعداد المنشورة هنا، فيمكن إعادة حسابها على نحوٍ مستقل.",
  "The order of an element is the least positive k with k copies of it summing to the identity. By Lagrange it divides the group order, and in the cyclic group of order n the element of index i has order n/gcd(i, n). Generators are exactly the indices coprime to n.":
    "رتبة العنصر هي أصغر عدد صحيح موجب k يجعل مجموع k نسخة منه مساويًا للعنصر المحايد. وبمقتضى مبرهنة لاغرانج فهي تقسم رتبة الزمرة، وفي الزمرة الدورية ذات الرتبة n تكون رتبة العنصر ذي الدليل i مساوية لـ n/gcd(i, n). والمولِّدات هي بالضبط الأدلّة الأوّلية مع n.",
  "The requirement that the operation not leave the carrier — already implied by writing it as a map into Q_n. Closure over a finite carrier is what makes exhaustive verification a terminating procedure rather than an unbounded search.":
    "شرطُ ألّا تُخرج العملية النتيجة عن المجموعة الحاملة، وهو شرط متضمَّن أصلًا في كتابتها تطبيقًا نحو Q_n. والانغلاق فوق مجموعة حاملة منتهية هو ما يجعل التحقّق الشامل إجراءً منتهيًا لا بحثًا غير محدود.",
  "The set of images of a point under the whole group. Orbits are the classes of an equivalence relation and therefore partition the set acted upon. Two elements in the same orbit are indistinguishable by any property invariant under the action, so orbits — not labels — are the correct objects to enumerate.":
    "مجموعة صور نقطةٍ تحت تأثير الزمرة كلّها. والمدارات هي أصناف علاقة تكافؤ ومن ثمّ فهي تُجزّئ المجموعة المؤثَّر عليها. وعنصران في المدار نفسه لا يمكن التمييز بينهما بأي خاصية صامدة تحت التأثير، ولذلك فالمدارات — لا التسميات — هي الكائنات الصحيحة التي تُعَدّ.",
  "The set of values actually attained. A map is surjective exactly when its image is the whole codomain, and for maps of a finite set into itself injectivity, surjectivity, and bijectivity coincide — which is why a non-injective translation is immediately detectable as a shrinking image.":
    "مجموعة القيم المبلوغة فعلًا. يكون التطبيق غامرًا إذا وفقط إذا كانت صورته هي المجموعة المستقرّة كلّها، وفي تطبيقات مجموعة منتهية إلى نفسها يتكافأ التباين والغمر والتقابل — ولهذا يُكشف الانسحابُ غيرُ المتباين فورًا من تقلّص صورته.",
  "The standard classification of maps. On a finite set of fixed cardinality the three notions collapse: a self-map is injective if and only if it is surjective if and only if it is bijective. Automorphisms must be bijections, since a non-injective relabelling would identify two distinct elements.":
    "التصنيف المعياري للتطبيقات. فوق مجموعة منتهية ذات عدد أصلي ثابت تنهار المفاهيم الثلاثة في واحد: تطبيق المجموعة إلى نفسها متباينٌ إذا وفقط إذا كان غامرًا، وإذا وفقط إذا كان تقابلًا. ويلزم أن تكون التشاكلات الذاتية تقابلات، إذ إنّ إعادة تسمية غير متباينة تُطابق بين عنصرين متمايزين.",
  "The standard hierarchy: closure alone gives a magma; adding associativity gives a semigroup; a two-sided identity gives a monoid; inverses give a group. The additive reduct is an abelian group, whereas the second law yields only a magma for n ≥ 2. Classifying precisely prevents the accidental import of stronger theorems.":
    "التسلسل المعياري: الانغلاق وحده يعطي ماغما؛ وإضافة التجميعية تعطي شبه زمرة؛ ووجود عنصر محايد من الجهتين يعطي أحاديًا؛ ووجود النظائر يعطي زمرة. والاختزال الجمعي زمرة تبادلية، بينما لا يعطي القانون الثاني سوى ماغما من أجل n ≥ 2. والتصنيف الدقيق يمنع الاستيراد العَرَضي لمبرهنات أقوى.",
  "The subgroup of elements fixing a given point. Stabilisers of points in one orbit are conjugate, and by orbit–stabiliser the index of the stabiliser equals the orbit length. The element P_0 has full stabiliser, since every automorphism of the expansion fixes the named constant.":
    "الزمرة الجزئية المؤلَّفة من العناصر التي تُبقي نقطةً معطاة صامدة. مثبِّتات نقاط المدار الواحد متقارنة، وبمبرهنة المدار والمثبِّت يساوي دليلُ المثبِّت طولَ المدار. أمّا العنصر P_0 فمثبِّته هو الزمرة كلّها، لأنّ كل تقابل ذاتي للتوسيع يُبقي الثابت المسمّى صامدًا.",
  "Universal algebra": "الجبر الشامل",
};
